### ISSUE TITLE
Random input generator doesn't work for a `decimal` column

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1006]
Using the `PRICE` table from the tutorial, I get all zeros in the `PRICE` column:

![image](https://github.com/feldera/feldera/assets/8323135/8d2ce5dc-a71e-43e4-8304-cfc0b06b3760)

**Comment by ryzhyk** [comment]
It works when I set non-default configuration for that column in the RNG, e.g., Normal or Uniform. So it appears that the default setting for the decimal type is constant 0.  It should probably be  Uniform within 0..100 range similar to other types.

**Comment by Karakatiza666** [comment]
Fixed with https://github.com/feldera/feldera/issues/1006
