### ISSUE TITLE
Image optimization warning

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1017]
I caught this when running yarn build as part of some Docker workflows.

```
 => => # - info Creating an optimized production build...
 => => # Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optim
 => => # ization.
 => => # Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```

Is this something we should be fixing?

**Comment by Karakatiza666** [comment]
This is relevant for projects where image assets are actively used, so I don't see the need for it in Web Console. I'd just ignore the warning until there is a reason to follow the suggestion

**Comment by lalithsuresh** [comment]
Not applicable with new UI.
