### ISSUE TITLE
WebUI Home Screen

### ISSUE THREAD

**Issue by gz** [feldera/feldera#102]
- [ ] Home Screen
    - [ ] UI: Design and define what goes on the first screen
    - [ ] UI: Should have a brief overview of everything that’s going on (running pipelines, etc.)
      - e.g., the Active Pipelines tab
    - [ ] UI: Should also have intro/screen to see what should be first steps
      - Configure links in "Kick start your project 🚀"
    - [ ] Configure links in "Welcome to dbsp!"
    - [ ] Configure links in the footer page to go to the right place
      - About -> feldera.com
      - Contact -> feldera.com/contact
      - Documentation docs.feldera.com
      - Support https://github.com/feldera/dbsp/issues
    - Replace Logo in top right with feldera logo
    - Remove User button top right (for now)
    - Remove notification button (top right for now)
    - DBSP Health: Maybe drop for now as we don't have notifications yet; or leave warnings and other notification at 0 and just count errors

**Comment by Karakatiza666** [comment]
Home UI includes these features and changes as of today
