### ISSUE TITLE
Unable to update Pipeline Resources via REST API

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#1026]
1) Create an example pipeline:
`curl -s -X 'POST' -H "Content-Type: application/json" http://localhost:8080/v0/pipelines -d '{"config":{ "workers": 6, "resources": { "cpu_cores_min": 2, "storage_mb_max": 2000 }}, "connectors": [], "name": "some name", "description": "some description", "program_id": null }'`
Substitute {pipeline_id} in the subsequent requests with the id in the response
2) Retrieve API config:
`curl -s -X 'GET' http://localhost:8080/v0/pipelines/{pipeline_id}/config`
3) Observe `workers` field is set as expected, but `cpu_cores_min` and `storage_mb_max` are null
4) Update pipeline configiration:
`curl -s -X 'PATCH' -H "Content-Type: application/json" http://localhost:8080/v0/pipelines/{pipeline_id} -d '{"config":{ "workers": 7, "resources": { "cpu_cores_min": 2, "storage_mb_max": 2000 }}, "name": "a new name", "description": "a new description"}'`
5) Follow step 2, observe the same result as in step 3

**Comment by mohsinbeg** [comment]
Can we please add the end-to-end steps in a new doc page at https://www.feldera.com/docs/tutorials/admin?
