### ISSUE TITLE
SQL Program Compilation Status

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#1032]
If multiple programs are in the queued, their status is "COMPILING" rather than some status indicating they are queued (see screenshot).
Proposals: "COMPILATION QUEUED", "QUEUED", "QUEUED FOR COMPILATION", "AWAITING COMPILATION"

![compilation_queue](https://github.com/feldera/feldera/assets/4954603/e04baf31-d4e3-4170-b929-cf725715d179)

**Comment by snkas** [comment]
Idea for more extensive compilation status moved to https://github.com/feldera/feldera/issues/1034

**Comment by mihaibudiu** [comment]
I don't see any todos for the compiler.

**Comment by mihaibudiu** [comment]
Should we close this in favor of #1034?

**Comment by snkas** [comment]
Yes, the compiler-related things were moved to #1034 -- I'll close this one once the corresponding PR is merged. I've removed the compiler tag.
