### ISSUE TITLE
Pipeline table UI sorting

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#1036]
- Sorting does not always work (clicking the little arrows sometimes works, but not always)
- When sorting on records or traffic, it does not sort on integer value rather it seems string comparison
- Action column does not need sorting
- Number of records is rounded to `.3s` rather than keeping the exact number of records using `,` as format, which is not as handy when wanting to double check via UI all records were indeed input

**Comment by ryzhyk** [comment]
No longer applicable to the new UI.
