### ISSUE TITLE
First part of service probing support

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1039]
API changes:
* [x] Add a new API entity called `ExternalService` (name=bikeshed). Decide on the shape of such an object.
* [x] Update connector API objects to use references to `ExternalService` where appropriate (e.g. Kafka, Kafka Connect, MySQL etc).
* [ ] Similar to how the pipeline API constructs a `PipelineRevision` object out of connectors and programs, we might need the concept of a  `ConnectorRevision` object.

Probing:
* [ ] Support probing an `ExternalService`. It might better to do this behind-the-scenes rather than via the API. The API should only read the status of an ExternalService which includes its health, similar to how we report the health of a pipeline today.

**Comment by lalithsuresh** [comment]
Bullet two/three is still WIP.

**Comment by snkas** [comment]
Major design difference from original issue is that services are not attached via separate table but are part of the connector itself.

The following is done this milestone:
- [x] Separate ConnectorConfig and PipelineConnectorConfig, of which the former resolves to the latter when combined with the services upon pipeline deployment, which is stored in the pipeline revision
- [x] Basic tests (integration, database) for new connectors
- [x] Update feldera demos to make use new connectors

The following is left for next milestone:
- [ ] Update demos in cloud repo to make use of the new connectors (only 3, all HTTP, so relatively small task)
- [ ] Further tests of the various connectors, extra consideration for how to expose connectors
- [ ] Initial design for service probing

For next next milestone:
- [ ] Initial design for connector probing

**Comment by snkas** [comment]
Moving this issue to the next sprint for the remaining tasks.

**Comment by snkas** [comment]
Updated above TODOs for this and next milestone separating service probing from connector service-integration and probing

**Comment by lalithsuresh** [comment]
@snkas good to merge?

**Comment by snkas** [comment]
Yes
