### ISSUE TITLE
WebUI Tutorial/New User experience

### ISSUE THREAD

**Issue by gz** [feldera/feldera#104]
- [ ] Have a good UI learning experience for users
    - [ ] Have Interactive/guided Tutorial for new users to learn the UI
        - [ ] If a user logs in the first time, opens editor/pipeline analytics etc. the first time; have pop-ups that guide the user through what they should do on this page (can be embedded YouTube videos in the beginning or animated pictures for example)
        - [ ] Backend: User settings: Need to know if user has seen a certain page (does not want dialog again)
    - [ ] Incorporate documentation in UI (This is pretty open-ended as our documentation is not yet existent)
        - [ ] UI: Start with SQL compiler documentation, need to browse existing docs
        - [ ] UI: On Errors (from Editor): we need to point/link to the right place in the documentation

**Comment by blp** [comment]
The documentation contains the start of a tour now: https://docs.feldera.io/docs/tour/. It is not interactive and it is not specific and it will require updates as the UI progresses.

**Comment by gz** [comment]
awesome <3
