### ISSUE TITLE
Disallow empty program/pipeline/connector names.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1042]
This has come up before.  While using empty strings as names doesn't technically break anything, it causes confusing user experience. For example after creating a pipeline with an empty name, an attempt to create another new pipeline keeps showing the "name exists" error in the webconsole until the new pipeline is assigned a non-empty name. As another example, an empty pipeline name is impossible to click in breadcrumb navigation.

A better user experience would be:
- When creating a new entity, the webconsole assigns a default name to it, e.g., `<Untitled pipeline 1>`
- The webconsole (and possibly the backend) don't allow creating entities with empty names or changing names to "".

@lalithsuresh , @gz, @Karakatiza666 , what do you think?

**Comment by lalithsuresh** [comment]
Strongly in favor of disallowing empty names.

To assign a default name, the web-console would need to check if the name is used by another instance first. And hopefully that workflow doesn't involve a full scan or we'll hit performance problems.

It might be better to prompt the user to enter a name first when creating a program (or checking whether there is a name when attempting to save a program). The UI can show an error when the name is missing or is used.

I'm also hoping we can go further via a separate PR and restrict names to only contain alpha-numeric characters + some characters like spaces, hyphens or underscores with a length limit. This will make them compatible as YAML keys throughout the API and backends, which is also convenient for the cloud FF. We could consider this during our API rework.

**Comment by lalithsuresh** [comment]
@snkas does the new API disallows empty names? If so let's close this issue.

**Comment by snkas** [comment]
Yes, it does not allow empty pipeline, API key or connector names.
