### ISSUE TITLE
Unable to insert TIME ARRAY values in a table

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#1050]
Steps to reproduce:
1) Create and start a pipeline with the following SQL program:
```SQL
create table table_1 (
    id integer not null primary key,
    field_a TIME ARRAY not null
);
```
2) Try to insert a row in any format:
- `curl 'http://localhost:8080/v0/pipelines/{pipeline_id}/ingress/TABLE_1?force=false&format=csv' -X POST -H 'Content-Type: application/json'  -d '1302962400,"[""03:47:09""]"'`
- `curl 'http://localhost:8080/v0/pipelines/{pipeline_id}/ingress/TABLE_1?force=false&format=csv' -X POST -H 'Content-Type: application/json'  -d '1302962400,"[03:47:09]"'`
- `curl 'http://localhost:8080/v0/pipelines/{pipeline_id}/ingress/TABLE_1?force=false&format=csv' -X POST -H 'Content-Type: application/json'  -d '1302962400,"["03:47:09"]"'`
- `curl 'http://localhost:8080/v0/pipelines/{pipeline_id}/ingress/TABLE_1?force=false&format=csv' -X POST -H 'Content-Type: application/json'  -d '1302962400,"[\"03:47:09\"]"'`
- `curl 'http://localhost:8080/v0/pipelines/{pipeline_id}/ingress/TABLE_1?force=false&format=csv' -X POST -H 'Content-Type: application/json'  -d '1302962400,["03:47:09"]'`
3) Observe error response: `failed to deserialize CSV record: error parsing field 'FIELD_A': invalid time string ...`

Please clarify if none of the above contain correct formatting for a CSV with an array of TIME values.

**Comment by ryzhyk** [comment]
This is a duplicate of #435

**Comment by Karakatiza666** [comment]
Closing as a duplicate.
The current soultion is to use JSON update format to insert rows containing ARRAY values

**Comment by ryzhyk** [comment]
Ideally, we should be using JSON everywhere in the WebConsole. It is generally better supported than CSV.
