### ISSUE TITLE
Starting a pipeline which is compiling crashes compiler service

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1057]
So here is a fun bug that leads to the compiler service crashing:

[Screencast from 11-21-2023 01:32:23 PM.webm](https://github.com/feldera/feldera/assets/127654/ef4f1721-8649-4eaf-a8ca-cb197afb85ec)

The error message is:

2023-11-21 21:28:32 ERROR [manager] Pipeline automaton '018bcac3-9d70-7097-a88e-4dcec174277d' terminated with error: 'Failed to fetch binary executable for running pipeline 018bcac3-9d70-7097-a88e-4dcec174277d: Did not receieve a compiled binary URL for 018bcac3-9d70-7097-a88e-4dcec174277d'

So it goes here: https://github.com/feldera/feldera/blob/d326a6c1feb795009988eecfb8017dae6d38beee/crates/pipeline_manager/src/pipeline_automata.rs#L144

There a few fixes for this:

- In the UI: If the pipeline is compiling, the start button should probably just be disabled in the Modifcations dialog
- In the backend: IMO if we go [here](https://github.com/feldera/feldera/blob/d326a6c1feb795009988eecfb8017dae6d38beee/crates/pipeline_manager/src/pipeline_automata.rs#L144) a better solution is probably to try to restart the service, or just panic as the compiler service will be gone for good afterwards (and the service is mostly unusable until a restart -- however the user won't realize this)
- The fix in the backend probably involves rejecting starts for pipelines which are compiling.. an alternative is to allow start and wait for the binary

**Comment by lalithsuresh** [comment]
@gz it's hard to tell from the video what exactly the repro is.

Is it to just start pipeline that is not yet compiled?

**Comment by lalithsuresh** [comment]
By the way, this is not the compiler service crashing, but the pipeline not being able to start.

**Comment by gz** [comment]
repro is 

1. modify program
2. start pipeline before compilation is done
3. (IN the UI this is normally disabled but the start button when looking at modifications is not so it's possible to send start)
4. (the api will allow start too)

**Comment by gz** [comment]
> By the way, this is not the compiler service crashing, but the pipeline not being able to start.

agree I think I missed the loop here https://github.com/feldera/feldera/blob/d326a6c1feb795009988eecfb8017dae6d38beee/crates/pipeline_manager/src/pipeline_automata.rs#L138 but it still seems after it ends up in the error the compilation for the program does not finish

**Comment by lalithsuresh** [comment]
The API allowing start here is definitely the issue. I'll take a look.
