### ISSUE TITLE
WebUI Connector Format/Parsing

### ISSUE THREAD

**Issue by gz** [feldera/feldera#106]
- [ ] Connector Formats (this is a big project, needs to be defined more explicitly as some exploration will be required to come up with a good solution)
    - [ ] UI: Add ability to define a data schema for existing (input) connectors
    - [ ] UI+Backend: Add ability to sample connectors and store samples for a connector or paste-in/write your own samples
        - [ ] UI: need to be able to store/view sampled data
    - [ ] UI+Backend: Ability to define parsers to construct a data format for connectors interactively with the help of sampled data (e.g., fields + their types)
    - [ ] UI: Add good ergonomics of matching connectors with tables (e.g., give better error in case of mismatch, field ambiguity etc.)
    - [ ] Backend: Error reporting/handling if parsing doesn’t work
    - [ ] Ability to inspect format/parsing errors for running pipelines

**Comment by gz** [comment]
In discussion with one of the test subjects: He would've expected that we define the data-format as part of the connector and then be able to either generate the table schema from that or don't have to write the sql table schema at all. 

This is consistent with what we discussed internally before and got as feedback from others as well.

**Comment by mihaibudiu** [comment]
this is true for people who don't already have an app and just kick the tires.

**Comment by gz** [comment]
I think it's the other way around, for people who already have data-source they expect to define the schema in teh data source/connector

**Comment by mohsinbeg** [comment]
> I think it's the other way around, for people who already have data-source they expect to define the schema in the data source/connector

An interactive way is to allow all data to come from the data source as-is. Then inspect it in the UI. Then add a table definition for the data. Repeat / edit schema in sql until schema is acceptable.
