### ISSUE TITLE
UI should show Input Source properties when adding it to a pipeline

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1089]
Without knowing the details, it's confusing to know which connector can be used.

![image](https://github.com/feldera/feldera/assets/28739668/ea0ffaee-dc3d-45a4-b078-f2749ebcd5a7)

**Comment by Karakatiza666** [comment]
I have added a button to inspect configuration of the connector. Is this sufficient, or is there any specific info you would like to see directly in the list of connectors?
![image](https://github.com/feldera/feldera/assets/8537259/3ec998cd-e14f-44f4-813b-ea51b47d044c)
![image](https://github.com/feldera/feldera/assets/8537259/c766fced-d025-444f-bd8a-11190a8e67a0)

**Comment by mohsinbeg** [comment]
> I have added a button to inspect configuration of the connector. Is this sufficient, or is there any specific info you would like to see directly in the list of connectors?

This looks good. I hope this dialog is modal and view-only when invoked from `Pipelines > <pipeline> > Add Input Source` flow.

**Comment by Karakatiza666** [comment]
It is
