### ISSUE TITLE
Re-implement all DBSP operators using dynamic dispatch.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1095]
This task is part of migrating the DBSP crate to use dynamic dispatch using hand-crafted vtables.  I've already implemented dynamic versions of all Z-set types and Spine.  The next step is to port all operators to the new API.

- [x] aggregation
- [x] `shard`, `gather`
- [x] `lag`
- [x] `topk`
- [x] rolling aggregates
- [x] `waterline`
- [x] `window`
- [x] `consolidate`
- [x] `count`
- [x] `index`
- [x] input operators
- [x] output operators
- [x] `distinct`
- [x] `FilterMap` trait
- [x] `join`
- [x] `join_range`
- [x] `neighborhood`
- [x] `sample`
- [x] `semijoin`
- [x] `trace`
- [x] `upsert`

**Comment by mihaibudiu** [comment]
You imply that we cannot have the dynamic objects implement Fn traits?

**Comment by mihaibudiu** [comment]
Or this is about iterating?

**Comment by ryzhyk** [comment]
@mihaibudiu , are you asking about why we need hand-crafted vtables? We do not use standard Rust trait objects (`dyn Trait`) inside Z-sets, because that would require allocating each object on the heap. But that's internal to the implementation.  At the API level not much will change.

**Comment by mihaibudiu** [comment]
Can you show the signature for one of the new operator versions?
Do we keep the old ones around?

**Comment by ryzhyk** [comment]
So far, the signature is the same as what we have today for the two operators I implemented.  I was not planning to keep both implementations around, but we can reconsider that before merging this work.

**Comment by ryzhyk** [comment]
I have initial implementation of all operators in a [branch](https://github.com/feldera/feldera/tree/dynamic).  It compiles but hasn't been tested or benchmarked. There's a lot more work to do before this is ready for prime time, including building a strongly typed abstraction layer on top of dynamically typed operators, rkyv serialization support, etc. I will create separate issues for these tasks.

**Comment by mihaibudiu** [comment]
Are you brave enough to rebase on main?

**Comment by ryzhyk** [comment]
Nothing works yet, so I'd rather not.
