### ISSUE TITLE
API documentation should use URLs and bearer token from current session

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1102]
Clicking the documentation option from the WebConsole should render the API documentation using the source WebConsole's URL and bearer token.

**Comment by mohsinbeg** [comment]
I prefer the API docs or Swagger be included in the WebConsole UI itself.

**Comment by lalithsuresh** [comment]
Every pipeline manager instance exposes a /swagger-ui endpoint which I find way more useful than the docusaurus version on feldera.com. @Karakatiza666 maybe you can just load the swagger-ui instead.

**Comment by lalithsuresh** [comment]
https://github.com/feldera/feldera/pull/1126 embeds auth and security scheme info into the OpenAPI spec, which should simplify this task.
