### ISSUE TITLE
Document NeighborhoodQuery arguments

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#1110]
NeighborhoodQuery is a key type for HTTP based input/output, but is under-documented. https://github.com/feldera/feldera/blob/75419a52f76a3627090eda32fe2bf0ce3ea22232/crates/pipeline-types/src/query.rs#L34

We need to document each argument and also provide an example using utoipa constructs. In particular, what is an example anchor and what after/before mean.

**Comment by ryzhyk** [comment]
We no longer support neighborhoods.
