### ISSUE TITLE
Webconsole UI should not copy customer content to post to github issue without authorization or interactive prompts

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1120]
We do not have authorization to POST to feldera public repo, customer's private content from their feldera product.

The copy function must provide user ability to obfuscate, redact or remove parts of the content that user disagrees with before posting it to a issue.

For now please disable this feature in the UI.

**Comment by Karakatiza666** [comment]
The information is not being submitted automatically, but merely placed in a text field on Github new issue page. So there is no risk until the user actually submits proposed issue, and they can edit the pasted issue description.

Shall I add a popup before submitting issue to Github to warn about copied issue description potentially containing sensitive data?

**Comment by gz** [comment]
> Shall I add a popup before redirecting to Github to warn about the copied issue description potentially containing sensitive data?

I think that's a good way to solve this for now.

**Comment by lalithsuresh** [comment]
Stale issue.
