### ISSUE TITLE
[SQL] Add all remaining trigonometric functions supported by Calcite

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1124]
asin, acos, atan, atan2, cos, cot, degrees, radians, tan, cbrt
cbrt may be different on decimal and double

**Comment by abhizer** [comment]
The Postgres docs say: 
```sql
cbrt ( double precision ) → double precision
    Cube root
cbrt(64.0) → 4
```

Do we want to type cast decimal to double and perform the cube root, or have a separate implementation for decimal?

**Comment by mihaibudiu** [comment]
If rust_decimal has a cube root and if Calcite does not insert casts, we can use it.
Otherwise we should only support double.

**Comment by abhizer** [comment]
rust_decimal doesn't seem to support cube root.
