### ISSUE TITLE
[SQL] Complete the Postgres numeric tests

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1125]
There are several classes of fixes required:
- make sure that the existing tests do what they are supposed to do. For example, is LN defined for double and decimal, or just for double? In the latter case we probably don't need tests for decimal
- re-enable the tests that were disabled because of precision problems
- port additional tests from Postgres. 
An important obstacle to porting tests is the fact that Postgres supports essentially unlimited precision, whereas we are limited to 128 bits. So many tests may need to be adjusted.

**Comment by abhizer** [comment]
`rust_decimal` currently doesn't support Infinity or NaN. Tests that use them have been converted to FPs. I think we should move them either to a separate file, or remove them and import FP tests from Postgres. 
All the functions used in Postgres Numeric Tests seem to be defined for both numeric and double.

**Comment by mihaibudiu** [comment]
@abhizer can we close this issue?

**Comment by abhizer** [comment]
I think we can. There are some other tests for things we don't support yet. And some involving inf, nan etc which we don't support. They also have some miscellaneous tests for things that have been broken in the past. 

And for a lot of things we cast to double and don't run it on DECIMAL. 

Closing this.
