### ISSUE TITLE
URL hash (anchor) reappears in URL bar after closing popups and hovering over a link

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#1138]
In attached video the issue manifests as unexpected reopening of a popup (controlled by URL hash) after page reload:
[Screencast from 12-11-2023 12:28:31 PM.webm](https://github.com/feldera/feldera/assets/127654/4714fde1-e55d-442a-bbcf-844cef136c81)

**Comment by ryzhyk** [comment]
No longer relevant with the new WebConsole.
