### ISSUE TITLE
Webconsole UI return error when looking at view output

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1142]
I occasionally see this error when viewing view output. Workaround is to refresh the browser which does not work all the time. The auth token is valid.

![image](https://github.com/feldera/feldera/assets/28739668/d6c8f58e-1870-403e-9497-0d5ba5e11abf)

**Comment by mohsinbeg** [comment]
API works ok.
```
> curl -s -L -N -X 'POST' "https://sandbox-staging.feldera.com/v0/pipelines/$PIPELINE_ID/egress/EVENT_V?format=json" -H "Authorization: Bearer $BEARER_TOKEN" | jq -C | head -n20

{
  "sequence_number": 0,
  "json_data": [
    {
      "insert": {
        "ID": 232005,
        "SITE_ID": 4667,
        "EQID": null,
        "SERIAL_NUM": "143967814558",
        "EVENT_TYPE_ID": null,
        "EVENT_DATE": 0,
        "EVENT_DATE_TIMESTAMP": null,
        "EMU_EVENT_ID": null,
        "MESSAGE_KEY": null,
        "MESSAGE_PARAMS": null,
        "ALARM_ID": null,
        "EVENT_CLEAR_DATE": null,
        "EVENT_CLEAR_DATE_TIMESTAMP": null,
        "UPDATED_AT": null,
        "STANDING": null,
```

**Comment by gz** [comment]
@Karakatiza666 this is a sandbox problem I think the bearer token isn't forwarded for the streaming http calls

**Comment by mohsinbeg** [comment]
> Does this happen with any specific program / content of input tables? If so, could you provide an example?

Insert 10 rows into a table. Click on Inspect Table for any table in the pipeline.

![image](https://github.com/feldera/feldera/assets/28739668/53d53189-8c0b-4e65-871f-daae51798971)

**Comment by lalithsuresh** [comment]
This is fixed in main, hasn't been deployed to the sandbox yet. I'll do a sync.
