### ISSUE TITLE
Generate mermaid code for SQL Program for Webconsole UI to render mermaid ER diagram

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1147]
It would be nice to render a ER diagram for the SQL Program in the WebConsole UI. We can decide how to render the views also.

https://mermaid.js.org/syntax/entityRelationshipDiagram.html

cc: @gz

**Comment by gz** [comment]
@mihaibudiu I think we can generate this once we have the foreign key relationship in your json schema from the compiler

**Comment by mihaibudiu** [comment]
That should be easy

**Comment by mihaibudiu** [comment]
But notice that a table can have multiple foreign keys and each foreign key can have multiple columns
