### ISSUE TITLE
[SQL] Invalid integer casts cause Compiler Error

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1153]
Performing an invalid cast such as: `SELECT CAST(256 AS TINYINT)` causes the following compiler error: 
```
error: This is a bug in the compiler (please report it to the developers): Value 256 out of range
```

I think this should be a compilation error. Writing a test as following and printing the error in the implementation of `shouldFail` should show the compiler error. 
```
    @Test
    public void testTinyIntCast() {
        this.shouldFail("SELECT CAST(256 AS TINYINT)", "Compilation error: java.lang.ArithmeticException: Value 256 out of range");
    }
```

The error originates while the compiler frontend (CalciteCompiler) parses SQL.
The exact point of error:  
https://github.com/feldera/feldera/blob/4e27e64eeda34bb293caecb1c80758c1599c04f4/sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/frontend/calciteCompiler/CalciteCompiler.java#L860

**Comment by mihaibudiu** [comment]
This is indeed a bug in Calcite, which I just filed: https://issues.apache.org/jira/browse/CALCITE-6168

**Comment by mihaibudiu** [comment]
Fix available in https://github.com/apache/calcite/pull/3588
