### ISSUE TITLE
`https://www.feldera.com/docs/demo/` needs connector options update

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1159]
The Kafka input connector has four screens to update now, and the second one has changed (new group.id field).

Similarly for the Kafka output connector.

**Comment by lalithsuresh** [comment]
The group.id field is going to become optional as soon as https://github.com/feldera/feldera/pull/1131 gets merged.

**Comment by lalithsuresh** [comment]
After that, we can regenerate the screenshots.
