### ISSUE TITLE
surprising expanders in web console

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1160]
The expander in the webui initially shows `v` then changes to `^` after expanding. I'm more used to `>` showing before expansion and `v` afterward. I don't know whether this is a new convention that is becoming widely used (if it is, then we should keep it the way we have it) or just something that we picked ourselves (in which case I argue to change it).

**Comment by Karakatiza666** [comment]
It looks like this is a convention (see the reasoning in https://ux.stackexchange.com/questions/87350/which-way-should-arrows-point-for-a-dropdown-button), and this matches the default behavior of a Dropdown component in the UI library (MUI) we currently use
