### ISSUE TITLE
Add SQL examples in SQL documentation

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1182]
For example, it was not clear to me how to use the `Extract` function in a SQL DDL.
Also, `EPOCH` was not listed as a keyword in https://www.feldera.com/docs/sql/datetime/#operations-on-timestamps.

**Comment by mihaibudiu** [comment]
I would suggest making a list of the documentation pages that need improvement.
Some pages do have examples, but they may be insufficient.

**Comment by mohsinbeg** [comment]
> I would suggest making a list of the documentation pages that need improvement.

Lets start with the ones you already know. We can incrementally improve.
