### ISSUE TITLE
[SQL] create an analysis which provides warnings for expressions that will certainly produce runtime errors

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1187]
- [ ] abs(INT_MIN)
- [ ] INT_MIN / -1
- [x] #1195

**Comment by abhizer** [comment]
Example issue: 

https://github.com/feldera/feldera/blob/a3e1b361bd817d2767d2c0a35fc2111234aaa73d/sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/postgres/PostgresInt2Tests.java#L350

**Comment by mihaibudiu** [comment]
@abhizer please add more such expressions as you find them to this issue

**Comment by mihaibudiu** [comment]
I will close this particular issue, we should do this every time we add new optimizations that can simplify expressions that generate runtime errors
