### ISSUE TITLE
Issues with manual connector editing

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1239]
The "Edit JSON" feature behaves in a surprising way in some circumstances:
- Corrupted JSON (e.g., with unbalanced parens) gets quietly discarded (the UPDATE button succeeds, but when I open the connector again, I see the previous valid config)
- Invalid values get rejected without an error message, e.g., when I set the "auto.offset.reset" field in Kafka config to something invalid, e.g., "xxx", the UPDATE button no longer works, so the dialog knows that the config is not good, but it doesn't say why.

**Comment by Karakatiza666** [comment]
Fixed with commit 962d8147ed3bfeb054add27c0b39e58176436e9c - you cannot switch to another view until the JSON syntax and known field types are valid
