### ISSUE TITLE
[DBSP] integrate_trace_retain_bounds panics when using multiple worker threads

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1260]

**Comment by mihaibudiu** [comment]
```
thread 'dbsp-worker-1' panicked at /home/mbudiu/git/dbsp/crates/dbsp/src/operator/trace.rs:123:14:
At least one trace bound must be set
```

**Comment by ryzhyk** [comment]
We have [tests](https://github.com/feldera/feldera/blob/7d6c59963f5b56c059f130d808f200f49286c835/crates/dbsp/src/operator/trace.rs#L943) for it that use multiple workers. Do you have a reproduction?

**Comment by mihaibudiu** [comment]
My last Pr has a disabled test

**Comment by mihaibudiu** [comment]
Do you want me to post the failing Rust here?

**Comment by ryzhyk** [comment]
Haven't looked at the PR yet. Rust would certainly help, thanks.
