### ISSUE TITLE
[CI] "benchmark" jobs are not cancelled when new commits are merged

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1269]
Seems that each PR merged into main causes a new run of the "benchmark" CI job.
However, I believe that newer commits should cancel older queued jobs.

**Comment by gz** [comment]
Not a good idea to cancel IMO .. idea is to spot performance regression so we want to benchmark them as we also preserve the results.

https://feldera.github.io/benchmarks/
