### ISSUE TITLE
Web Console allows saving empty program name

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1275]
- Create a new program, enter non-empty program name.  The program gets saved.
- Erase the name, the program gets saved successfully with the empty name.  The resulting program cannot be deleted using the Delete button.

**Comment by lalithsuresh** [comment]
Captured here: https://github.com/feldera/feldera/issues/1141

**Comment by ryzhyk** [comment]
As far as I can tell, the Web Console side of the issue is a separate bug. The latest web console PR introduced checks for empty program and pipeline names, but there is this one situation where I was able to get around the check. I can see that #1141 is supposed to make it impossible to set an empty name of the server side, but in this case the WebConsole should have solved the issue before sending the request to the manager.

**Comment by Karakatiza666** [comment]
Absolutely, I will solve it on UI side, too
