### ISSUE TITLE
Pipeline editort overlaps with "Add a new output"

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1276]
- Create a new pipeline using the program from the Feldera tutorial
- Save the pipeline, switch to the pipeline list view.
- Click edit pipeline. The pipeline editor now overlaps with the Add a new output control 

![image](https://github.com/feldera/feldera/assets/8323135/6ba46a71-dc47-4677-af69-8ddebd999b1d)

**Comment by Karakatiza666** [comment]
This issue only happens when PipelineManager returns data when GETting a pipeline with an empty name. This will no longer reproduce after fixes pipeline with an empty name can no longer be created
