### ISSUE TITLE
Ergonomics of pushing sample data from files or URLs

### ISSUE THREAD

**Issue by gz** [feldera/feldera#129]
We need to figure out ergonomics of working with files as data-sources in the MVP

- [x] Backend part (use pure HTTP or a nice wrapper around websockets or HTTP2 or gRPC) (@ryzhyk)
- [ ] UI: upload .csv, push them through HTTP connector (@gz)
- [ ] Modify all Python demos to use HTTP connector (@ryzhyk)
- [ ] Examples in the documentation (@lalithsuresh)

**Comment by blp** [comment]
There's some question of whether we want to have a file connector at all.

**Comment by blp** [comment]
We discussed supporting HTTP connections without websockets.

**Comment by ryzhyk** [comment]
HTTP connectors are now supported. I will add support for them in Python in #88 and will use that in demos instead of the file connector.

**Comment by lalithsuresh** [comment]
With the HTTP connector, python SDK and upcoming ad-hoc query interface, we can close this.
