### ISSUE TITLE
Program name ending with space not encoded in URL

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#1301]
**Steps to reproduce:**
1. Go to SQL programs
2. Create a program named "a " (i.e., the letter a with a space after it)

The URL for the program is:
`http://localhost:8080/analytics/editor/?program_name=a `

... whereas it should be:
`http://localhost:8080/analytics/editor/?program_name=a%20`

**Comment by Karakatiza666** [comment]
@lalithsuresh what's the set of requirements / regex you would like to settle with for the names of API entities?

**Comment by lalithsuresh** [comment]
@Karakatiza666 I would ideally make it alphanumeric and hyphens only. But I'd rather handle this throughout the API rather than make it a UI only change. Otherwise, the API will permit names that conflict with the restrictions the UI imposes.

**Comment by Karakatiza666** [comment]
We are waiting to decide on a set of rules for allowed API entity names, which would get enforced both client and server side

**Comment by Karakatiza666** [comment]
@lalithsuresh @snkas bump

**Comment by snkas** [comment]
Created PR: https://github.com/feldera/feldera/pull/2331

**Comment by snkas** [comment]
Names no longer permit spaces, as such closing this.
