### ISSUE TITLE
PersistentSpine implementation

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1316]
Implement a persistent spine using the persistent Ord* implementations according to storage design.

- Should persist state of spine
- Should have a strategy to deal with merges

**Comment by blp** [comment]
This needs a file-based OrdValBatch. I have written one and I am testing it today.

**Comment by lalithsuresh** [comment]
@gz @blp Is this done? If not, can we update the milestone.

**Comment by blp** [comment]
I'm rebasing my part of this against Leonid's recent changes. There's a decent chance of it being finished for this milestone so I set that as the new one.

**Comment by blp** [comment]
I believe that this is complete with @gz's recent changes.
