### ISSUE TITLE
[DBSP] The compiler should be able to provide some metadata about operators to DBSP

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1323]
There is nothing tying the compiler representation of operators to the runtime representation of operators, and also to the source position of operators in the SQL program. The DBSP APIs for creating graphs do not allow for passing any metadata about operators. At the least the compiler should be able to specify its own internal node IDs to the DBSP runtime.

**Comment by ryzhyk** [comment]
Superseded by #2284
