### ISSUE TITLE
[SQL] Calcite optimizes log(POSITIVE_NUMBER, 0) down to 0, when it should be an error

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1348]
The `PostgresFloat8Tests#testLogFail2` test in PR #1344: 

```java
    // Calcite optimized version returns 0
    @Test @Ignore
    public void testLogFail2() {
        this.qf("select log(2, 0)", "Unable to calculate log(2, 0)");
        this.qf("select log(1, 0)", "Unable to calculate log(1, 0)");
    }
```

Calcite optimizes the log of a positive number with base 0 to 0, instead of returning an error.

**Comment by mihaibudiu** [comment]
This is actually not unreasonable. It uses the formula log(a, b) = ln(a) / ln(b). ln(0) evaluates to -infinity. So the result is actually -0.

**Comment by abhizer** [comment]
Hmm. So what should we do for it? 

Return errors like Postgres, or return 0 like Calcite?

**Comment by mihaibudiu** [comment]
Unless it's clearly wrong calcite wins

**Comment by abhizer** [comment]
Rust seems to agree: `[src/main.rs:2] 2.0_f64.log(0.0) = -0.0`

Although, MySQL and Spark return NULL and Postgres gives an error. 
I'll switch to match Calcite.

**Comment by mihaibudiu** [comment]
if there is a function ln(decimal) -> decimal in Calcite we can give an error
If Calcite returns double we can return -infinity
Let's follow Calcite again.
