### ISSUE TITLE
Logging from `ctor`

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1353]
The `feldera-storage` crate has a [`ctor`](https://docs.rs/ctor/latest/ctor/) that increases the fd limit, see https://github.com/feldera/feldera/blob/main/crates/feldera-storage/src/lib.rs. If it can't raise the fd limit (enough), then it logs about it.

However, I can't see any way that that log message will hit any real log, because logging is a no-op before a log implementation is configured. It isn't reasonable to try to configure logging from a ctor, because [ctors can't use Rust stdio](https://github.com/mmastrac/rust-ctor):

> Rust's philosophy is that nothing happens before or after main and this library explicitly subverts that. The code that runs in the ctor and dtor functions should be careful to limit itself to libc functions and code that does not rely on Rust's stdlib services.
>
> For example, using stdout in a dtor function is a guaranteed panic. Consider using the [libc-print crate](https://crates.io/crates/libc-print) for output to stderr/stdout during #[ctor] and #[dtor] methods. Other issues may involve signal processing or panic handling in that early code.

I think that it would be better to avoid using `ctor` for this. I think it would be better to raise the fd limit from the backend implementations as a once-only kind of action. Then it would still happen before it was needed and it could log usefully in the normal way.

(I discovered this while [adding a ctor to raise the locked memory limit](https://github.com/feldera/feldera/commit/31738e3d1a4818290b2cc8693a9a3c338c9fa458); I couldn't get it to log.)

I'm perfectly happy to do this myself but I want to get feedback, especially from @gz or @ryzhyk, before I do, in case I'm missing something.

**Comment by gz** [comment]
Any kind of "constructor before main" ala ctor is generally an anti-pattern in the rust world. We should probably just do those things when we initialize the dbsp runtime.. maybe it can call feldera_storage::init() somewhere in main. This is similar to what env logger does with require call env_logger::init() or try_init

**Comment by gz** [comment]
putting the code in a https://doc.rust-lang.org/std/sync/struct.LazyLock.html might do it

**Comment by blp** [comment]
I revised my `memlimit` branch to fix this too. Currently building, will submit PR when it passes CI.

**Comment by blp** [comment]
PR #1356 submitted

**Comment by blp** [comment]
PR merged, closing.
