### ISSUE TITLE
[SQL] Floating-point literals can be lossy

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1367]
The SQL compiler generates Rust code using floating-point literals represented as strings. However, the serialization of a compiler-internal FP value into a string is lossy. The compiler should use a different constructor which takes the exact 32/64-bit representation of the FP value in the generated code: https://doc.rust-lang.org/std/primitive.f64.html#method.to_ne_bytes

**Comment by blp** [comment]
Probably better to use `from_le_bytes` or `from_be_bytes`, for portability, or `from_bits` (which would be shorter), or [hexf](https://crates.io/crates/hexf) for readability.
