### ISSUE TITLE
Improved Kafka config and diagnostics

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#137]
- [x] Kafka error reporting (should be solved for now when #369 lands).
- [ ] Additional config options we want to support in 0.1
  - [ ] Password-based authentication.
  - [ ] ???

**Comment by ryzhyk** [comment]
Settings supported by rdkafka: https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

**Comment by blp** [comment]
I like the lists of settings here a bit better (under CONFIGURATION, section 3, divided by type of config): https://kafka.apache.org/documentation/#configuration

**Comment by ryzhyk** [comment]
Closing.  Will create a separate issue for Kafka configuration options.
