### ISSUE TITLE
NULL's show up as NaN's

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1392]
Create a SQL program:
```sql
create table t (
    x int,
    y decimal
);

create view v as select * from t;
```

Create a pipeline without connectors, feed a record where `x` and `y` are `null`, e.g., using the UI table editor.  The record shows up with `NaN` in `x` and `y` columns instead of `NULL`. 

![image](https://github.com/feldera/feldera/assets/8323135/be2f4f4e-cdf0-476d-8600-ff3d64fc15ae)

**Comment by Karakatiza666** [comment]
Related to https://github.com/feldera/feldera/issues/1169

**Comment by mihaibudiu** [comment]
It looks very different from 1169, why is it related?

**Comment by mihaibudiu** [comment]
It would be very good to fix this before the next release.

**Comment by Karakatiza666** [comment]
In different places, it likely is going to be a big PR

**Comment by mihaibudiu** [comment]
I think it doesn't even assume NULL is null, it assumes it's a string.
