### ISSUE TITLE
Have a top level /stats API that return values for all things in running Feldera instance

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1402]
While this is useful.
> `GET` /v0/pipelines/:pipeline_name/stats

It would be more convenient to have it at the top level and let user optionally filter

> `GET` /v0/stats
> `GET` /v0/stats?pipelines=:pipeline_name

**Comment by lalithsuresh** [comment]
That's a good suggestion.

What else would you like to see in /stats?

**Comment by mohsinbeg** [comment]
> What else would you like to see in /stats?

The union of all stats apis for all REST resource in the tenancy, including system level counters, gauges and histograms.
