### ISSUE TITLE
[SQL] array literal should be Vec<Option<T>> but we get Vec<T>

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1414]
While implementing `array_append`, for the following test case: 

```java
    @Test
    public void testArrayNull() {
        this.q("""
                SELECT array_append(ARRAY [1, 2], null::int);
                 array_append
                --------------
                 {1, 2, NULL}"""
        );
    }
```

The generated rust code calls the `array_append` function with parameters `Vec<T>` and `None::<i32>` and expects `Vec<Option<T>>`. 

Generated code: 

```rust
            Tup1::new(array_append_vec_N(vec!(
                1i32, 2i32, ), None::<i32>))
```

It should be `vec![ Some(1i32), Some(2i32)]` instead. 

I'm not sure how to cast the inner type to be nullable in the compiler.

**Comment by mihaibudiu** [comment]
This is how the type inference works in Calcite for this function. In the case that the vector elements have a different nullability than the appended value we'll have to convert both to the same type before we perform the append. The type of the result is correct, so we should insert casts on both sides to the type of the element of the result.

**Comment by mihaibudiu** [comment]
I will take care of this.

**Comment by abhizer** [comment]
While inserting data to an `INTEGER ARRAY` column, we get errors related to the array type. 

Consider an input as such: 
```java
    @Override
    public void prepareInputs(DBSPCompiler compiler) {
        String prepare = """
                CREATE TABLE ARR_TBL (vals INT ARRAY, id INT NOT NULL);
                INSERT INTO ARR_TBL VALUES(NULL, 1);
                INSERT INTO ARR_TBL VALUES(ARRAY [0, 1, NULL, 3, NULL], 3);
                """;

        compiler.compileStatements(prepare);
    }
```

The error:
```rust
(no input file): Compiler error
(no input file):1:1: error: Compiler error: Added zsets do not have the same type Tup2<Vec<i32>?, i32> vs Tup2<Vec<i32?>, i32>
    1|CREATE TABLE ARR_TBL (vals INT ARRAY, id INT NOT NULL);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


org.dbsp.sqlCompiler.compiler.errors.InternalCompilerError: Added zsets do not have the same type Tup2<Vec<i32>?, i32> vs Tup2<Vec<i32?>, i32>

	at org.dbsp.sqlCompiler.ir.expression.literal.DBSPZSetLiteral.add(DBSPZSetLiteral.java:117)
	at org.dbsp.sqlCompiler.compiler.frontend.TableContents.addToTable(TableContents.java:103)
	at org.dbsp.sqlCompiler.compiler.frontend.CalciteToDBSPCompiler.compile(CalciteToDBSPCompiler.java:1546)
```

Some what related but not quite the same, for input `ARRAY [NULL]` ( `INSERT INTO ARR_TBL VALUES(ARRAY [NULL], 2)`)
We get: ` Added zsets do not have the same type Tup2<Vec<i32>?, i32> vs Tup2<Vec<null?>, i32>`

I feel like as the type of the element is known, it should know that `null` is infact `null::int`.

**Comment by abhizer** [comment]
https://issues.apache.org/jira/browse/CALCITE-6275

**Comment by mihaibudiu** [comment]
Fix in Calcite https://github.com/apache/calcite/pull/3698, not sure whether it will be accepted

**Comment by mihaibudiu** [comment]
We can solve this problem without getting Calcite involved, it's a matter of improving the spec and fixing the compiler. This is mostly a question of DDL.
