### ISSUE TITLE
Fix StreamingTests Assertion for Storage

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1440]
https://github.com/feldera/feldera/blob/f69c5bcd50b97065dd50d8f5f5b1fad18bd5ad65/sql-to-dbsp-compiler/SQL-compiler/src/test/java/org/dbsp/sqlCompiler/compiler/sql/streaming/StreamingTests.java#L382

**Comment by mihaibudiu** [comment]
This will need help from the profiling infrastructure to collect data for storage too.
The right way to disable the test is to use `@Ignore`. But this will work too for now.

**Comment by blp** [comment]
> This will need help from the profiling infrastructure to collect data for storage too. The right way to disable the test is to use `@Ignore`. But this will work too for now.

I prefer commenting out the assertion because the part that comes before it triggered a bug in the storage implementation that wasn't triggered by other tests.
