### ISSUE TITLE
[SQL] support different but comparable types of arguments in array functions like (array_position, array_contains, array_remove)

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1475]
The current implementation of array functions in https://github.com/feldera/feldera/pull/1468 doesn't support parameters of different types in the following array functions: 
- [ ] array_position
- [ ] array_contains
- [ ] array_remove
- [x] arrays_overlap

One approach to solving this would be to cast the second argument to the type of the element in the array, and this would work for most cases. 

However, there's an edge case where the array only has NULL (single or multiple of them) elements. 
Consider `SELECT ARRAY_POSITION(ARRAY [NULL], 1)`. Here, NULL is translated to `None::<()>` as there is no other type information about the type of elements in the array. Here, trying to cast `1` to `()` would not be ideal. 

For `array_position` and `array_contains` we could probably handle this edge case by converting the element type from `None::<()>` to `None:<i32>`. 
And for `array_remove` we might be able to solve this by casting to the expected output type from Calcite.

**Comment by abhizer** [comment]
For `array_position(ARRAY [1, 2, 3, 4], 1e0)` the Calcite optimized version returns 0, while it should actually be 1 (and Spark agrees). 

However, for `array_position(ARRAY [1, 2, 3, 4], 1.0)` Spark gives an error: 
```sql
spark-sql (default)> select array_position(array(cast(1 as int),2,3,4), 1.0);
[DATATYPE_MISMATCH.ARRAY_FUNCTION_DIFF_TYPES] Cannot resolve "array_position(array(CAST(1 AS INT), 2, 3, 4), 1.0)" due to data type mismatch: Input to `array_position` should have been "ARRAY" followed by a value with same element type, but it's ["ARRAY<INT>", "DECIMAL(2,1)"].; line 1 pos 7;
'Project [unresolvedalias(array_position(array(cast(1 as int), 2, 3, 4), 1.0), None)]
+- OneRowRelation
```

This is weird and inconsistent in Spark. It works for `ARRAY<INT>, FLOAT32` but fails for `ARRAY<INT>, DECIMAL(2,1)`. 

cc: @mihaibudiu

**Comment by abhizer** [comment]
Similar to the previous comment regarding `array_position`, for `arrays_overlap`: 
`SELECT ARRAYS_OVERLAP(ARRAY [1, 2, 3], ARRAY [2e0, 4e0])` Calcite returns `false` while it should be `true` (Spark agrees). 

However, for `arrays_overlap([1, 2, 3], ARRAY[2.0, 4.0])` Spark gives a type mismatch error.

**Comment by mihaibudiu** [comment]
We should document that the value on the right must have the same type as the array's elements.
Otherwise the result is undefined.
That's the easy way to do this.
In the compiler we should check this and reject programs where this isn't true.
Calcite will accept constant expressions which we deem illegal and simplify them, but we can claim that these are undefined, so any result is ok.
I don't like this, but being bug-compatible with both Spark and Calcite may be too difficult.
