### ISSUE TITLE
[RFC] JSON

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1478]
## Problem 

Currently, the SQL compiler doesn't support JSON.
It would be really useful to be able to traverse and query JSON data. 

While Calcite does support the JSON type, and has functions to operate on it (see: [JSON Functions](https://calcite.apache.org/docs/reference.html#json-functions)), we can probably do better. 

## Proposed Approach 

In the Rust side of things, the idea is to use `serde_json::Value` or a potential wrapper type for it. 
`serde` is a popular choice in the Rust community, is actively maintained, and normally nice to work with. 

In the Java side of things, we would likely be using [UDFs](https://github.com/feldera/feldera/blob/main/docs/sql/udf.md) to implement functions that deal with JSON.

Looking at current implementation of JSON in Snowflake, the proposal is start with the following functions (the actual names during implementation may be different): 
- `json_field(x: JSON, y: fieldName) -> JSON` 
- ~`json_nested_field(x: FieldName, y: InnerFieldName) -> JSON`~

This is the function equivalent to the [Dot Notation](https://docs.snowflake.com/user-guide/querying-semistructured#dot-notation) in Snowflake. 

Perhaps we could also support something like: 

- `json_get(x: JSON, [y: level1FieldName, z: level2FieldName ... ]) -> JSON`

This would be the functional equivalent of the [Bracket Notation](https://docs.snowflake.com/user-guide/querying-semistructured#bracket-notation) in Snowflake. 

The result of these functions may be cast to a type using the `::` operator or `CAST()` method. 

To parse a string as JSON, we could: 
- try casting a string to JSON type using `CAST()` or `::` operator
- call `parse_json(value: String) -> JSON` similar to the [this](https://docs.snowflake.com/sql-reference/functions/parse_json). 

Additionally, we could support: 
- `check_json(value: String) -> bool` that is `true` if the given String is valid JSON
- `try_parse_json(value: String) -> JSON?` that returns `NULL` instead of erroring in case of malformed JSON as input. 

Ideally: 
- a function such as [flatten](https://docs.snowflake.com/en/sql-reference/functions/flatten) 

I think something like `flatten` would be an incredibly useful addition, however, at the time of writing this, I am unsure of what the exact implementation would be. 

### Amendment

For indexing array literals in JSON: 
- `json_index(x: JSON, index: usize) -> JSON`
  - the `index` would start at 1 to keep consistent with array indexing
  - panic if the JSON argument isn't a JSON array

- `check_schema(x: JSON, schema: JSON_SCHEMA) -> bool`

## Open Questions 
- Is this a good idea? 
- What do you think about the proposed functions and the developer experience that comes with it? 
- What are your opinions on the `flatten` function? 
- Any alternative approaches that should be considered?

**Comment by mihaibudiu** [comment]
I don't think json_nested_field is necessary.

**Comment by mihaibudiu** [comment]
flatten is of secondary value, it can be done later if someone really wants it.

**Comment by gz** [comment]
> In the Rust side of things, the idea is to use serde_json::Value or a potential wrapper type for it.

We probably want our own value type so we can control the serialization/deserialization for storage.
e.g., https://github.com/rkyv/rkyv/blob/main/examples/json/src/main.rs#L67 something like this seems to resemble serde_json::Value

**Comment by ryzhyk** [comment]
`serde_json::Value` is also pretty inefficient as it uses a lot of small allocations. In particular, every field name in the JSON document is a separate allocation. In DDlog, we used a data structure similar to `serde_json::Value`, but using interned strings instead of `String`.

**Comment by ryzhyk** [comment]
- Can `flatten` be achieved by extracting an array from JSON and calling `unnest` on it?
- How do we treat JSON arrays and array indexing?
- `json_nested_field` indeed seems unnecessary, since it can be achieved by calling `json_field` multiple times. A better generalization would be `json_path(x: FieldName, y: JsonPathQuery) -> JSON`, which is similar to the `json_get` suggestion in the RFC, but JSON path can also include array indexing.

**Comment by mihaibudiu** [comment]
we already have arrays, so array indexing can be obtained by casting the object to `JSON ARRAY`

**Comment by ryzhyk** [comment]
Another performance consideration: if we use a type like `serde_json::Value` to represent JSON documents, then every time we extract a field, the entire JSON subtree will get cloned. A better design would wrap each JSON node in an `Arc` or `Rc` and return that instead.

**Comment by ryzhyk** [comment]
> we already have arrays, so array indexing can be obtained by casting the object to `JSON ARRAY`

That makes sense, but this means that in order to extract an element from an array we will need to first clone the entire array to convert it to a SQL array.

**Comment by mihaibudiu** [comment]
The compiler will support a polimorphic indexing operation, with different implementations for arrays and json arrays.
I was talking about the surface syntax.

**Comment by ryzhyk** [comment]
> The compiler will support a polymorphic indexing operation, with different implementations for arrays and json arrays. I was talking about the surface syntax.

That would be very nice. But this means that functions like `json_field()` and `json_get` must return JSON fields by reference rather than by value.

**Comment by abhizer** [comment]
https://github.com/Diggsey/ijson might be useful as an alternative for `serde_json::Value`.

**Comment by mihaibudiu** [comment]
This is not completed by any means, the compiler still does not support JSON

**Comment by mihaibudiu** [comment]
I will close this RFC and open a new issue with items
