### ISSUE TITLE
A file connector can not be added to a pipeline

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1488]
I can make a file connector using the generic editor:

![Screenshot from 2024-03-03 19-57-45](https://github.com/feldera/feldera/assets/127654/ff806265-f5d4-4647-ae6c-a078f396fa15)

but then I can't add them through the console because it doesn't really know about this mysterious connector here:
![Screenshot from 2024-03-03 19-58-22](https://github.com/feldera/feldera/assets/127654/7e52d2ae-3c64-48a8-bc99-36815f5cc54b)

(ideally, the file connector should still show up as under a category that lists all the unknown/generic connectors  so it can be selected here)

**Comment by lalithsuresh** [comment]
I ran into this while testing the S3 connector too.

Do we need the breakdown here, as opposed to a list of connectors that also have an icon next to them about the type?
