### ISSUE TITLE
WebConsole stops responding under load or results in error

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1504]
1. Run https://try.feldera.com/demos/#setup/Product%20Availability
2. Navigate to https://try.feldera.com/streaming/inspection/?pipeline_name=product-availability-pipeline&relation=product_stored
3. Confirm constantly updating numbers
4. Click on Demo or SQL Programs does not do anything for a few secs
5. Browser back works but doing back and forward results in an error displayed at https://try.feldera.com/streaming/inspection/?pipeline_name=product-availability-pipeline&relation=product_stored

**Comment by lalithsuresh** [comment]
@mohsinbeg could you share the screenshot from 5?

**Comment by mohsinbeg** [comment]
> @mohsinbeg could you share the screenshot from 5?

I didn't save it. But I got the spinning icon for a 10+ seconds and then an error in the section where the view output is rendered.

**Comment by ryzhyk** [comment]
Closing, as this version of the webconsole has been decommissioned.
