### ISSUE TITLE
[SQL] distinct aggregates can give wrong results

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1506]

**Comment by blp** [comment]
There are no details here, so I do not have a way to guess, but it could possibly be related to or even fixed by [commit a70e8599e ("dbsp: Mark filter output as distinct using correct logic.", 2024-03-06)](https://github.com/feldera/feldera/commit/a70e8599e895b105492c77747409db36327bfa87).

**Comment by mihaibudiu** [comment]
I have a failing test. Will add it when I get near a computer

**Comment by mihaibudiu** [comment]
```
                select deptno,
                 count(distinct job) as dj,
                 count(job) as j,
                 count(distinct mgr) as m,
                 sum(sal) as s
                from emp
                group by deptno
```

**Comment by mihaibudiu** [comment]
Actually this happens because we run tests both with and without optimizations.0
The optimizer expands the distinct aggregates into something we handle correctly, so this test should only be run with optimizations.
