### ISSUE TITLE
Demo cleanup hangs in try.feldera.com

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#1521]
![image](https://github.com/feldera/feldera/assets/28739668/b539a2bf-6447-4a44-9507-82ab5ea604fa)

**Comment by mohsinbeg** [comment]
There is no close dialog button or icon after it hangs, however clicking anywhere outside the dialog closes it. Invoking the Clean Up results in same issue.

**Comment by lalithsuresh** [comment]
@Karakatiza666 any idea what's going on? I'm not able to reproduce.

**Comment by snkas** [comment]
One way to reproduce the screenshot is:
- Create demo
- Create another pipeline which uses the demo program
- Cleanup the demo

**Comment by mohsinbeg** [comment]
> One way to reproduce the screenshot is:
> 
> * Create demo
> * Create another pipeline which uses the demo program
> * Cleanup the demo

This was not my case.

**Comment by gz** [comment]
https://github.com/feldera/feldera/issues/1458
