### ISSUE TITLE
connector editor doesn't work

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1538]
- I can't edit a connector anymore with the generic JSON editor (the editor text shows up as empty)
- This is a regression from services PR since it's working on d8c8f017

<img width="931" alt="image" src="https://github.com/feldera/feldera/assets/127654/7b8b7206-ca53-4e4d-9c06-526f95806cc4">

**Comment by Karakatiza666** [comment]
Closed by https://github.com/feldera/feldera/pull/1540
