### ISSUE TITLE
A basic UI for single-shot service probing

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#1543]
In a service list, each service should have a button to trigger connectivity probe, and an icon on the right displaying probe result - accessible, inaccessible or probe-in-progress

**Comment by snkas** [comment]
For the naming (when hovering over the icon for example), I would advocate for keeping the terms and four stages pending, running, success and failure related to the probe itself, such that the API documentation matches the UI. I also would recommend keeping pending and running separate for the same reason.

**Comment by ryzhyk** [comment]
Closing as part of the transition to the new API. We may still implement some form of service probing, but it will be a very different design.
