### ISSUE TITLE
Hello: Is there slack or discord for communication?

### ISSUE THREAD

**Issue by caicancai** [feldera/feldera#1546]
I am very interested in this project. It is very cool. Is there any slack or discord where we can communicate, or can I ask questions directly on the issue?
Thank you

**Comment by ryzhyk** [comment]
Hello, @caicancai ! We do have a slack community, you can sign up for it [here](https://www.feldera.com/slack). You are also welcome to submit your questions as issues.

**Comment by caicancai** [comment]
> Hello, @caicancai ! We do have a slack community, you can sign up for it [here](https://www.feldera.com/slack). You are also welcome to submit your questions as issues.

Thank you
