### ISSUE TITLE
[sql] JIT compiler TODOs

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#158]
- [x] String operations
- [ ] Rich datatypes
  - [x] Dates
  - [ ] Numeric
  - [x] Timestamps
  - [ ] Long and short intervals
  - [ ] Dates with timezone
  - [ ] Timestamps with timezones
  - [ ] Vectors
  - [ ] Structs
  - [ ] Geographic data types
  - [ ] Blobs
  - [ ] JSON
- [x] Run end-to-end tests
- [ ] Functions producing nested tuples
- [ ] Window queries
- [ ] Order-by
- [ ] Figure out how to re-implement the runtime library

**Comment by Kixiron** [comment]
These most of the intrinsics I've implemented, they're in various states of use on your side
- `@dbsp.str.bit_length()`
- `@dbsp.str.char_length()`
- `@dbsp.str.byte_length()`
- `@dbsp.str.is_lowercase()`
- `@dbsp.str.is_uppercase()`
- `@dbsp.str.is_nfc()` (unicode string normalization)
- `@dbsp.str.is_nfd()` (unicode string normalization)
- `@dbsp.str.is_nfkc()` (unicode string normalization)
- `@dbsp.str.is_nfkd()` (unicode string normalization)
- `@dbsp.str.is_ascii()`
- `@dbsp.math.is_sign_positive()` (Floats and integers)
- `@dbsp.math.is_sign_negative()` (Floats and integers)
- `@dbsp.math.acos()`
- `@dbsp.math.cosh()`
- `@dbsp.math.acosh()`
- `@dbsp.math.sin()`
- `@dbsp.math.asin()`
- `@dbsp.math.tan()`
- `@dbsp.math.atan()`
- `@dbsp.math.cot()`
- `@dbsp.math.sinh()`
- `@dbsp.math.cosh()`
- `@dbsp.math.tanh()`
- `@dbsp.math.asinh()`
- `@dbsp.math.atanh()`
- `@dbsp.math.is_power_of_two()`
- `@dbsp.math.log()`
- `@dbsp.math.log2()`
- `@dbsp.math.log10()`
- `@dbsp.math.log1p()`
- `@dbsp.math.sqrt()` 
- `@dbsp.math.cbrt()`
- `@dbsp.math.tgamma()`
- `@dbsp.math.lgamma()`
- `@dbsp.math.exp()`
- `@dbsp.math.exp2()`
- `@dbsp.math.exp10()`
- `@dbsp.math.expm1()`
- `@dbsp.math.fdim()`
- `@dbsp.math.radians_to_degrees()`
- `@dbsp.math.degrees_to_radians()`

**Comment by mihaibudiu** [comment]
Here is the list of Calcite functions and operators: https://calcite.apache.org/docs/reference.html
But more are added every day, and I am not sure if all commits modify this list.
Notice that many of the arithmetic functions are supposed to work with decimals as well, so they should probably be polymorphic.

**Comment by mihaibudiu** [comment]
I will start working on implementing the FP functions, which will use many of these. But some of them seem to have no counterpart in SQL.

**Comment by Kixiron** [comment]
I found most of them in (Postgres' docs)[https://www.postgresql.org/docs/current/functions-math.html#FUNCTIONS-MATH-FUNC-TABLE], they're functions that are standard in most languages and can't really be emulated by hand (no one's going to manually write `sqrt()` or `log10()` in SQL and even if they could it'd have atrocious performance)

**Comment by mihaibudiu** [comment]
Calcite's support for Postgres is meager at best. But we'll use the numeric ones.
