### ISSUE TITLE
Error message for invalid interval constants are hard to understand

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1588]
![Screenshot from 2024-03-29 17-23-19](https://github.com/feldera/feldera/assets/127654/edc8aa01-cfc4-4c92-9c37-11646455f0e0)

**Comment by mihaibudiu** [comment]
This is because the message is too long to display entirely.
The error comes from JavaCC, the parser generator, so it's very difficult to improve it.
But what we need is to have a pane where all errors are enumerated and can be seen in detail. I think there's an issue for that.

**Comment by gz** [comment]
The full error is

```
Encountered "MINUTE" at line 15, column 23.
Was expecting one of:
    <EOF> 
    "ORDER" ...
    "LIMIT" ...
    "OFFSET" ...
    "FETCH" ...
    ";" ...
    "," ...
    "FROM" ...
    "UNION" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
```

The problem I have with it is that it doesn't tell me the format for this interval is wrong (if I just put '1' instead of '1 1:1'

**Comment by mihaibudiu** [comment]
As I said, errors generated by code generated by a parser generator are very hard to improve.

**Comment by mihaibudiu** [comment]
I will close this one because there is nothing we can do about it.
