### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1589]
the docs say: `INTERVAL YEAR TO MONTH` and the example is `INTERVAL '2021-07' YEAR TO MONTH`

But when I try that I get an error:

![Screenshot from 2024-03-29 17-27-28](https://github.com/feldera/feldera/assets/127654/e29e91ca-de4c-430a-bc04-5f8a235ff31b)

**Comment by mihaibudiu** [comment]
This is a new bug in Calcite: https://issues.apache.org/jira/browse/CALCITE-6345
I will change the example for now.

**Comment by mihaibudiu** [comment]
I filed a fix with Calcite too, I think it should accept the rejected expressions. No one looked at it yet.
