### ISSUE TITLE
[WEBUI] Clicking on the "lock" icon should offer the option to authenticate

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1596]
At least in the image started by docker the icon has no action associated

**Comment by gz** [comment]
It should not appear in docker form factor

**Comment by mihaibudiu** [comment]
you mean the icon should not appear at all?

**Comment by gz** [comment]
not in the docker form factor, since we don't have authentication there

**Comment by Karakatiza666** [comment]
The icon specifically communicates to the user that there is no authenticcation configured. Would you like to update the hover popup message to "No authentication configured" for better clarity?

**Comment by mihaibudiu** [comment]
yes, but no authentication is possible either.
maybe you should convey that
