### ISSUE TITLE
[WEBUI] There is no way for users to "setup" a demo

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1597]
The demo page says:
"Setup and explore pre-made demos on this Feldera instance"

What is "setup"? There is no way to "add" a new demo.

**Comment by gz** [comment]
@Karakatiza666 ideally we either have the demos also in docker or we remove this menu option in docker if there are no demos to choose from

**Comment by lalithsuresh** [comment]
Should be fixed with the new UI
