### ISSUE TITLE
[WEBUI] missing schema

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1598]
This happens with the latest docker image ready for release:
- I add a new SQL program
- It seems to compile fine (get a green checkmark)
- add it to the pipeline
- get an error about missing schema:
>  "Missing Schema?
>  We didn't find the schema for the program of the config you are trying to load. Either the program has not been compiled yet or the compilation had errors. Continue to the program editor to resolve the issue."
- I am offered to edit the program, but there are no errors whatsoever

**Comment by mihaibudiu** [comment]
Even deleting the pipeline and creating a new one doesn't solve this problem.

**Comment by gz** [comment]
you also need to add that this is on WSL/Windows :)

**Comment by ryzhyk** [comment]
Closing, as this should no longer happen with the new API.
