### ISSUE TITLE
[sql] Buggy calcite optimization rule

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#160]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Thu Apr 13 18:49:11 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/148_

----

The rule CoreRules.PROJECT_JOIN_TRANSPOSE is unsound and should not be used by the optimizer.
Have to find a way to create an easy reproduction for the Calcite project.
With this rule the following query from SLT select2.test produces incorrect results:
```
SELECT abs(b-c),
       a+b*2+c*3,
       (SELECT count(*) FROM t1 AS x WHERE x.b<t1.b),
       a-b,
       a+b*2+c*3+d*4+e*5,
       CASE WHEN a<b-3 THEN 111 WHEN a<=b THEN 222
        WHEN a<b+3 THEN 333 ELSE 444 END
  FROM t1
```

**Comment by mihaibudiu** [comment]
This is really a Calcite bug. This rule has been disabled in our compiler. So I will close the issue.
If the rule is ever fixed in Calcite we can re-enable it.
