### ISSUE TITLE
Make Feldera version number available from the deployed product

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1611]
# Summary
[summary]: #summary

The Feldera version number, and possibly the commit number, should be available from the API and possibly the web console.

# Motivation
[motivation]: #motivation

Making the version number available lets users know what features to expect, whether their deployment has been upgraded, and whether they need to initiate or request an upgrade.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

I would expect that we would add:
- An API endpoint that reports the version number (and possibly the commit number).
- Something in the web console that reports the same thing.

# Drawbacks
[drawbacks]: #drawbacks

There could be caching implications for our CI system in some implementations, especially for commit numbers that change on every commit. A thoughtful implementation presumably could avoid this problem.

There are security implications of making the version number visible to the Internet at large, so it might be wise to make this an authenticated endpoint.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

There's a philosophical debate in the realm of software between checking for features and checking for versions. Checking for features can be more reliable (since you know for sure whether the feature is there if you check for it), but it's also more difficult (each feature check has to be written individually and they can be difficult to write sometimes). Without exposing a version number, users have to check for features. I think it's likely that for Feldera, checking its version number is going to be much easier, so I lean toward exposing it. Also, feature checks are more reliable mostly in software that has been widely forked or for standards that have multiple implementations, and Feldera is neither one.

# Prior art
[prior-art]: #prior-art

- [GNU standards for `--version`](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion)

# Unresolved questions
[unresolved-questions]: #unresolved-questions

Dunno.

# Future possibilities
[future-possibilities]: #future-possibilities

Doesn't seem super-extensible.

**Comment by ryzhyk** [comment]
This is fixed now
