### ISSUE TITLE
[sql] Dates BC are not supported

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#162]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Wed Jan 25 18:04:11 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/97_

----

This seems to be a Calcite limitation.

**Comment by mihaibudiu** [comment]
Since Calcite cannot do this, we can't either, so I will just close it for now.
We have documented this behavior.
