### ISSUE TITLE
Support incremental AsOf joins in DBSP

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1643]
https://docs.snowflake.com/en/sql-reference/constructs/asof-join

**Comment by lalithsuresh** [comment]
@ryzhyk good to close?

**Comment by mihaibudiu** [comment]
No, we need more, including Calcite, compiler, and GC support.

**Comment by ryzhyk** [comment]
#1998

**Comment by ryzhyk** [comment]
> No, we need more, including Calcite, compiler, and GC support.

I created separate issues for compiler and GC work.
