### ISSUE TITLE
[sql] The use of .clone() in Rust should be revisited

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#165]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Fri Mar  3 22:49:42 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/127_

----

Clone should be called when the caller requires it, not when the callee thinks it's needed.

**Comment by mihaibudiu** [comment]
I have removed the "bug" label, this is now just a performance concern.

**Comment by mihaibudiu** [comment]
I will close this issue for now, we should look at the quality of the generated code at some point, but if the Rust backend is not the main one, perhaps this doesn't matter.
