### ISSUE TITLE
Sanity check removal of this line

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1651]
https://github.com/feldera/feldera/pull/1650 removed `sasl_oauthbearer_method: 'default'` from the default JSON list. I don't know what the negative implications of it are (aside from that it fixes connectors with PLAINTEXT auth). I do think we shouldn't add any configuration options by default. 
See also https://github.com/feldera/feldera/issues/1649 for a related problem.

**Comment by Karakatiza666** [comment]
This does not affect UI currently as OAUTHBEARER sasl mechanism is not an allowed in the UI
