### ISSUE TITLE
Support for Avro output format

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1663]
Implement Avro output adapter, including the following minimal set of features
- Support Kafka-compatible Avro format (which has a different envelope than the standard Avro file format)
- No schema registry support yet. The user specifies the schema as part of connector configuration.
- Only Kafka value schema is supported; no Kafka key schema yet.
- No support for multiple schema with cross-references.
- Support raw encoding of output records, i.e., each Avro object describes a single output record, but not its weight or any other metadata (hence there's no way to produce deletes)

**Comment by mihaibudiu** [comment]
We have to use a more precise description of such objects than just "Avro".

**Comment by ryzhyk** [comment]
More precise in what way?

**Comment by mihaibudiu** [comment]
The bullet points make it very precise, but when we refer to the thing we can't just say "Avro output connector".
That's exactly why you have the bullet points.
Maybe we can call it Kafka-compatible Avro output connector?
Avro is similar to JSON, it doesn't really mean anything by itself.

Speaking of this, I think we should have documentation for all the adapters we support, which describe exactly what they do.
