### ISSUE TITLE
[sql] There is no documentation on how to run the sql compiler

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#167]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Thu Mar  2 00:34:43 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/124_

----

We need a small "hello world" example which 
1. creates a SQL script
2. sends it to the compiler
3. generates rust
4. have a tester function in Rust that calls the generated circuit
5. feed the circuit some change, get the output change and print it

**Comment by ryzhyk** [comment]
We have documentation now in the compiler README.

**Comment by blp** [comment]
> We have documentation now in the compiler README.

Also in the website: https://www.feldera.com/docs/contributors/compiler

**Comment by mihaibudiu** [comment]
That documentation is inadequate.
For example, the compiler flags need to be documented.
Moreover, there is still no documentation showing how to use the produced rust.

**Comment by gz** [comment]
>, the compiler flags need to be documented
You document them here https://www.feldera.com/docs/contributors/compiler/#command-line-compiler

**Comment by mihaibudiu** [comment]
I would like people to be able to write sql, compile it, and run it without the web UI.

**Comment by gz** [comment]
> I would like people to be able to write sql, compile it, and run it without the web UI.

we have the python scripts that do this. what other ways are you thinking of?

**Comment by mihaibudiu** [comment]
A README.
Can you point me to a script which does this?

**Comment by gz** [comment]
this one here:

https://github.com/feldera/feldera/blob/main/demo/project_demo00-SecOps/run.py

it uses some functionality defined in
https://github.com/feldera/feldera/blob/main/demo/__init__.py

and also in our dbsp python library (under python/); but shouldn't be too hard to write a self-contained script from these two links. let me know if you need some help with it

**Comment by mihaibudiu** [comment]
No kafka, just plain rust

**Comment by gz** [comment]
kafka is just a connector this script happens to attach to the program. You can also use the binary without kafka and instead use e.g., HTTP to communicate with the process.

**Comment by mihaibudiu** [comment]
No http, no services, just a Rust file that you want to link against and test.
I don't know how to do this, I'd like to know.

**Comment by gz** [comment]
the rust file/binary will listen on a port and accept http requests. It's just a form of IPC what other communication mechanism do you want/need. I don't think we have good support for other forms of IPC except http atm (but @ryzhyk might know more).
