### ISSUE TITLE
LATENESS processing has to be performed before aggregating data into Z-sets

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1675]
Standard streaming engines process each "event" individually.
This means that notions such as lateness are evaluated for each new record, and late records are dropped immediately.
However, the current implementation batches records in the input operators and applies lateness to a whole batch.
The semantics of the two implementations is different.

**Comment by ryzhyk** [comment]
We have established that records were dropped due to a different issue fixed in #1679. While buffering can indeed make out-of-order records appear in order, I don't think we've seen a use case where this causes problems.

**Comment by mihaibudiu** [comment]
I will close this for now.
