### ISSUE TITLE
Renaming a pipeline breaks insert

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1691]
This is mostly likely due to a stale cache in react-query?

https://github.com/feldera/feldera/assets/127654/f3537d69-8ed8-4ae6-aab6-d27a3af75a77

**Comment by gz** [comment]
Hm you're saying maybe it shouldn't since we refer to things by name now?

**Comment by lalithsuresh** [comment]
It might be a factor. Could you see if the same workflow does what you expect with just the API?

**Comment by lalithsuresh** [comment]
We've removed these features in the new UI. Closing.
