### ISSUE TITLE
SecOps Demo creates (too) many files in storage mode

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1712]
0. start manager `RUST_LOG=info cargo run --bin=pipeline-manager --features pg-embed -- --compilation-profile dev`
1. Make a "secops" pipeline with SQL in UI [SQL code](https://raw.githubusercontent.com/feldera/feldera/main/demo/project_demo00-SecOps/project.sql) (using "secops" for program/pipeline name)
2. Enable "Storage" checkmark in pipeline table  
4. Enable metrics in pipeline (this needs to be done with a curl command currently):
```
curl -X 'PATCH' \
  'http://127.0.0.1:8080/v0/pipelines/secops' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "config": {
  "workers": 8,
  "storage": true,
  "cpu_profiler": false,
  "tcp_metrics_exporter": true,
  "min_batch_size_records": 0,
  "max_buffering_delay_usecs": 0,
  "resources": {
    "cpu_cores_min": null,
    "cpu_cores_max": null,
    "memory_mb_min": null,
    "memory_mb_max": null,
    "storage_mb_max": null }
  },
  "name": "secops",
  "description": "secops",
  "program_name": "secops"
}'
```
5. Start pipeline
FYI the log will print the storage directory when the pipeline starts up e.g., you should see a line like this in the log `storage_location: /Users/gerdzellweger/.feldera/pipelines/pipeline018f3adf-98ba-7e6c-b1c3-c91b760c5806/data`
6. Connect to pipeline with `metrics-observer`
7. View any (currently empty) Table/View in WebUI
8. Insert one row in any table in WebUI

(If you look at created files it should be in the few hundreds for both step 7 and 8; step 7 is especially strange since it's "read-only" you're only looking at a view with nothing in it, inserts in the spine should be at '1' after step 8)

**Comment by blp** [comment]
We might find that using a nonzero min_storage_threshold just magically makes this go away. I'll investigate.

**Comment by blp** [comment]
To-do: check whether this solves the problem with browsing mentioned by @gz in PR #1773 .

**Comment by ryzhyk** [comment]
I believe this has been addressed by the numerous recent improvements to the storage layer.
