### ISSUE TITLE
[sql] Calcite constant-folds EXTRACT expressions without regards to SQL dialect

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#173]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Thu Jan 26 21:05:15 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/98_

----

Asked a question about it on the Calcite Jira
https://issues.apache.org/jira/browse/CALCITE-759

**Comment by mihaibudiu** [comment]
I will close this issue, we have documented the expected behavior.
