### ISSUE TITLE
SQL checking waits for everything queued to compile to binary

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1741]
When there are one or more programs compiling, the SQL compiler isn't invoked to check syntax until everything in the queue has finished compiling, so the user receives no feedback until then.

It would be better to check SQL syntax immediately even if the Rust binary won't be made available until later.

**Comment by mihaibudiu** [comment]
I don't think this is an issue with the SQL compiler, so I will remove this tag

**Comment by lalithsuresh** [comment]
Related issue: https://github.com/feldera/feldera/issues/1482
