### ISSUE TITLE
CREATE TYPE generates invalid rust code

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1755]
As reported in  https://felderacommunity.slack.com/archives/C05P08AS74K/p1715737686619809

```
CREATE TYPE ADDRESS AS (
   address_type    VARCHAR,
   address         VARCHAR
);

CREATE TYPE CustomType AS (
    version TINYINT not null,
    address ADDRESS
);


CREATE TABLE Data (
    id BIGINT not null primary key,
    msg CustomType
);
```

leads to a rust compilation error

**Comment by mihaibudiu** [comment]
Can you paste the error here? I don't have a laptop handy

**Comment by mihaibudiu** [comment]
We have similar code in tests that pass, but I don't know whether we tested these with the pipeline manager

**Comment by mihaibudiu** [comment]
@ryzhyk this is due to the table having a primary key.
The difficulties arise in the add_input_map and register_input_map functions.
When using user-defined structs, the compiler internally converts them to tuples, but here the structs are visible in the signatures of these methods.
