### ISSUE TITLE
Renaming pipeline does not propagate to row insertion

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#1758]
**Describe the bug**
Renaming pipeline does not propagate to row insertion

**To reproduce**

1. Create any program, e.g. named `supply-chain-program`:
   ```
   CREATE TABLE product (
       pid INT PRIMARY KEY,
       name VARCHAR,
       price DOUBLE
   );

   CREATE VIEW average_price AS SELECT AVG(price) FROM product;
   ```

2. Create and start pipeline (e.g., named `supply-chain-pipeline`)
3. Rename pipeline to something else (e.g., `supply-chain-pipeline2`)
4. Try to insert rows into table via the UI

**Screenshot**
![error](https://github.com/feldera/feldera/assets/4954603/498b6ba4-04e0-4c07-8aea-583f7b5870fd)

**Expected behavior**
UI should use the new name.

Doing it directly via curl works:
```
curl -i -X 'POST' \
  http://localhost:8080/v0/pipelines/supply-chain-pipeline2/ingress/product?format=json \
  -d '{"insert": {"pid": 0, "name": "hammer", "price": 5.0}}'
```
... gives:
```
HTTP/1.1 200 OK
transfer-encoding: chunked
date: Wed, 15 May 2024 14:50:23 GMT
access-control-allow-credentials: true
access-control-expose-headers: content-length, date
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
```

**Comment by snkas** [comment]
Duplicate of https://github.com/feldera/feldera/issues/1691 though with more reproducibility steps.

**Comment by lalithsuresh** [comment]
Not applicable to new UI.
