### ISSUE TITLE
Use text labels for storage status

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1766]
Instead of using "x" in the WebConsole to indicate that storage is disabled, use a text label, e.g., "MEMORY" for disabled storage and "DISK" for enabled storage.

**Comment by ryzhyk** [comment]
We've discussed that a better option is to make it a `spill to disk` toggle switch.

**Comment by ryzhyk** [comment]
cc @gz

**Comment by lalithsuresh** [comment]
No longer needed with new UI, as the pipeline configuration is supplied as JSON.
