### ISSUE TITLE
Float Semantics

### ISSUE THREAD

**Issue by Kixiron** [feldera/feldera#177]
We have a decision to make in regards to floating point semantics, we use somewhat "incorrect" ordering semantics for sorting floating point values (IEEE, except NaN is greater than all other values and equal to itself (`OrderedFloat`'s semantics)) which contrasts to what most things use, IEEE.
The decision is this: Should floats act like `OrderedFloat` within JIT code or should they act like `f32` (IEEE). IEEE is much more efficient, but `OrderedFloat` has consistency with how we sort sets/indices

**Comment by blp** [comment]
I think that anything non-IEEE by default will surprise people. `OrderedFloat` order for collections etc. makes sense to me.

**Comment by mihaibudiu** [comment]
What we think is not as important as what the standard requires.
Unfortunately SQL 92 seems to say nothing about NaN :https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt.
In fact the standard does not even mention IEEE FP.
Postgres has made a choice: https://www.postgresql.org/docs/16/datatype-numeric.html, which we should probably follow:
"In most implementations of the “not-a-number” concept, NaN is not considered equal to any other numeric value (including NaN). In order to allow numeric values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values."

**Comment by Kixiron** [comment]
Postgres uses IEEE-745 <https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-FLOAT>
> these types are implementations of IEEE Standard 754 for Binary Floating-Point Arithmetic

**Comment by mihaibudiu** [comment]
That was the section for FP, so my quote is good.
IEEE does not define comparisons for NaN. That's one reason the Rust f32 type does not work for us.

**Comment by Kixiron** [comment]
I think Postgres does exactly what I'm proposing, your quotation talks about what Postgres does *internally to build indices*. However it's not really clear which behavior it chooses for user defined operations, I again think that IEEE is the least surprising thing for us to do

**Comment by mihaibudiu** [comment]
I bet the same choice applies to operations like `<`.

**Comment by blp** [comment]
It's easy enough to test this behavior in postgres:

```
[blp@sigxcpu dbsp]$ psql test
psql (15.1)
Type "help" for help.

test=> CREATE TABLE floats (a NUMERIC, b NUMERIC);
CREATE TABLE
test=> INSERT INTO floats VALUES ('NaN', 5);
INSERT 0 1
test=> SELECT * FROM floats;
  a  | b 
-----+---
 NaN | 5
(1 row)

test=> SELECT a + b FROM floats;
 ?column? 
----------
      NaN
(1 row)

test=> SELECT a < b, b < a FROM floats;
 ?column? | ?column? 
----------+----------
 f        | t
(1 row)

test=> SELECT a = a, b = b FROM floats;
 ?column? | ?column? 
----------+----------
 t        | t
(1 row)
```

Thus, Postgres has non-IEEE behavior for comparisons overall. It treats NaN as greater than other values and it considers NaN=Nan to be true.

**Comment by mihaibudiu** [comment]
Well, one test does not prove anything, #146 was filed exactly because often, but not always, in the JIT NaN == NaN.
I can make a similar statement about the Rust code we generate.
But I am willing to bet that Postgres is consistent, anything else would drive people crazy.

**Comment by mihaibudiu** [comment]
Ieee is a nightmare https://en.m.wikipedia.org/wiki/NaN
Maybe it's good for matrix algebra
