### ISSUE TITLE
Python SDK should use per-instance variables instead of class variables.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1770]
Variables declared [this way](https://github.com/feldera/feldera/blob/0e24687474aa1dc137ddd7ce6f9147bcf6fe8c75/python/feldera/sql_context.py#L42) are static variables shared by all instances of the class, so we end up with all programs sharing the same set of connectors and tables.

**Comment by abhizer** [comment]
Woah, I didn't know that they were static. 
Will fix, thanks!
