### ISSUE TITLE
`listen_to_pipeline` does not handle ndjson correctly

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1775]
The problem with this design is that the last input buffer may never end at a chunk boundary, so it will keep accumulating data even though it could yield all but the last incomplete chunk.
https://github.com/feldera/feldera/blob/54eca45d3c8b1a6d13bfc114ac29381b50183df9/python/feldera/rest/client.py#L463

When using ndjson, json.loads() will always fail if you have >1 chunks, since ndjson is not valid json.

The simplest solution would be to read response line-by-line and parse each line into a json object if python allows this.  In Rust, I search for the last new-line in the input buffer, and yield everything accumulated up to that offset, and only store the remainder of the buffer.

**Comment by abhizer** [comment]
Closing as this has been fixed as we use `iter_lines` now.
