### ISSUE TITLE
Rolling aggregation requires unsigned timestamp type

### ISSUE THREAD

**Issue by blp** [feldera/feldera#179]
The following program adds a Z-set with values 0..30 as input, then uses `partitioned_rolling_aggregate_linear` to do rolling aggregation across a `Before(0), Before(0)` relative range, then it runs one step and prints the output.

```
use dbsp::{
    operator::{time_series::RelOffset, time_series::RelRange, FilterMap},
    IndexedZSet, RootCircuit,
};

fn main() {
    let (circuit, (input, pre, post)) = RootCircuit::build(|circuit| {
        let (stream, handle) = circuit.add_input_zset::<i32, isize>();
        let pre = stream.map_index(|&k| ((), (k, 10)));
        let post = pre.partitioned_rolling_aggregate_linear(
            |&v| v,
            |x| x,
            RelRange::new(RelOffset::Before(0), RelOffset::After(0)),
        );
        Ok((handle, pre.output(), post.output()))
    })
    .unwrap();

    for k in 0..30 {
        input.push(k, 1);
    }

    circuit.step().unwrap();

    for (pre, post) in pre.consolidate().iter().zip(post.consolidate().iter()) {
        let ((), (t, pre_k), w) = pre;
        let ((), (t2, post_k), w2) = post;
        assert_eq!(w, 1);
        assert_eq!(w2, 1);
        assert_eq!(t, t2);
        let post_k = post_k.unwrap();
        println!("time={t}: {pre_k} vs {post_k}");
    }
}
```

The output I get is below. I expected every line to say `time={t}: 10 vs 10`. The lines that say `10 vs 300` and `10 vs 140` surprise. I think they are bugs.

```
time=0: 10 vs 300
time=1: 10 vs 10
time=2: 10 vs 10
time=3: 10 vs 10
time=4: 10 vs 10
time=5: 10 vs 10
time=6: 10 vs 10
time=7: 10 vs 10
time=8: 10 vs 10
time=9: 10 vs 10
time=10: 10 vs 10
time=11: 10 vs 10
time=12: 10 vs 10
time=13: 10 vs 10
time=14: 10 vs 10
time=15: 10 vs 10
time=16: 10 vs 140
time=17: 10 vs 10
time=18: 10 vs 10
time=19: 10 vs 10
time=20: 10 vs 10
time=21: 10 vs 10
time=22: 10 vs 10
time=23: 10 vs 10
time=24: 10 vs 10
time=25: 10 vs 10
time=26: 10 vs 10
time=27: 10 vs 10
time=28: 10 vs 10
time=29: 10 vs 10
```

**Comment by ryzhyk** [comment]
Yep, definitely looks wrong.  I'll have a look.

**Comment by ryzhyk** [comment]
Turns out there is an undocumented assumption in the code that the timestamp type is unsigned. The bit-level arithmetic in the radix tree implementation breaks otherwise. I am going to document it + enforce using the `num::Unsigned` trait.

Generalizing the implementation to support signed timestamps is not completely trivial, so I'd rather not spend time on this now.

Thanks for reporting!

**Comment by blp** [comment]
> Turns out there is an undocumented assumption in the code that the timestamp type is unsigned. 

Oh wow, thanks for pointing that out. I confirmed that changing
```
        let (stream, handle) = circuit.add_input_zset::<i32, isize>();
```
to
```
        let (stream, handle) = circuit.add_input_zset::<u32, isize>();
```
(that is, `i32` to `u32`) fixed the problem.

> The bit-level arithmetic in the radix tree implementation breaks otherwise. I am going to document it + enforce using the num::Unsigned trait.
Works for me.
