### ISSUE TITLE
WebConsole error when adding rows: "e.toFixed is not a function"

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1795]
- added three default rows
- click on a cell, but don't actually change it
- leave the cell and single-click on any row in the table
-  press `1` on the keybord (or any other number), the error pops up

![toFixed](https://github.com/feldera/feldera/assets/8323135/6cb2b581-bd27-44fa-8ad4-b5c32c8325bd)

**Comment by Karakatiza666** [comment]
Easier reproduction:
1) Single-click on a BIGINT cell
2) Press any alphanumeric key
