### ISSUE TITLE
SQLContext and other module docs are missing in the API reference

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1796]
Published [Python SDK docs](https://www.feldera.com/python/feldera.html) don't show any methods under `SQLContext` and other top-level modules, except `Feldera.rest`.

Not sure if this is related, but individual bullet points under [Key concepts](https://www.feldera.com/python/introduction.html#key-concepts) should be hyperlinks to corresponding sections in the reference.

**Comment by abhizer** [comment]
Closing as this has now been fixed.
