### ISSUE TITLE
`SQLContext.run_to_completion`, `SQLContext.start` do not correctly check pipeline status

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1797]
This check, and the one below verifies that `self.state`, which at this point is always equal to SHUTDOWN, regardless of the actual state of the pipeline:

https://github.com/feldera/feldera/blob/089a9fda03cbe860112caaf9e3ae9622252f5b53/python/feldera/sql_context.py#L324

A minimal fix would be to retrieve the pipeline state before this check.  But I actually think that we shouldn't try to track pipeline state in a local variable and should just always request it from the pipeline.

**Comment by ryzhyk** [comment]
Let's keep it open. #1792 removes the incorrect logic, but we still need to implement those check correctly.

**Comment by abhizer** [comment]
The new API always checks the state with the backend. 

Closing as no longer applicable for the newer API.
