### ISSUE TITLE
Make min_storage_rows based on bytes instead of the count

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1812]
Currently a given batch within a spine is kept in memory or on storage based on its row count. It would be better to use the byte count as a threshold instead.

_Originally posted by @gz in https://github.com/feldera/feldera/issues/1785#issuecomment-2140172620_

**Comment by ryzhyk** [comment]
Good idea, but I'm not sure how to achieve this. The `SizeOf` trait can be used to determine the memory usage of a batch, but it can be expensive to use in the critical path as it iterates over all elements of the batch.

**Comment by mihaibudiu** [comment]
Clearly, it has to be maintained Incrementally as part of some Metadata

**Comment by gz** [comment]
It ahouldnt change after the batchnis built. Maybe wr can store it in the header of the file. The LSM tree impls I read say one should use the uncompressed size for it...
