### ISSUE TITLE
Timeouts in Python SDK

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#1832]
* The operations related to program status (waiting for compilation) and pipeline status (e.g., starting, stopping, pausing) should all have a timeout associated to them
* Timeouts should be set with a reasonable margin
* Debug logging should be printed showing the elapsed time so far

**Comment by abhizer** [comment]
This feels tricky. We'd need to figure out a reasonable timeout duration. 

For compilation specially, the timeout could be too short based on the program.
