### ISSUE TITLE
Nexmark SQL benchmark runs out of memory on CI with 100 million max events

### ISSUE THREAD

**Issue by aehmttw** [feldera/feldera#1874]
**Describe the bug**
When run on CI servers with 100 million events, the Nexmark SQL benchmark fails. Currently, bench.bash tests SQL tests with only 10 million events because of this: https://github.com/feldera/feldera/commit/03881b7d6201022e4c635baf8a69f6cd3fcdf73b. @mihaibudiu mentioned that the SQL and Rust benchmarks should run the same test, which they currently aren't, so I was recommended to file this issue.

**To Reproduce**

Change bench.bash to run 100 million events for SQL tests and run CI via GitHub actions

**Expected behavior**

The benchmark should complete successfully with 100 million events

**Screenshots**

N/A

**Context (please complete the following information):**
This is a problem in CI servers

**Additional context**
A failed run's log can be found here. We investigated the system logs and found it had died because it ran out of memory. https://github.com/feldera/feldera/actions/runs/9452519772/job/26035900931

**Comment by mihaibudiu** [comment]
An issue should be as specific as possible to enable someone reproducing the actual bug.
In this case it seems that q9 fails.
It would be nice to have a single command-line one could run to reproduce the failure without being familiar with the details of the benchmarking script.

**Comment by aehmttw** [comment]
If you wish to run this locally, use the following commands:
(this is adapted from https://github.com/feldera/feldera/tree/main/benchmark/feldera-sql but with a modified event count and only with query q9)

In one window:
docker run --name redpanda -p 9092:9092 --rm -itd docker.redpanda.com/vectorized/redpanda:v23.2.3 redpanda start --smp 2
cargo run -p pipeline-manager --features pg-embed

In another:
KAFKA_BROKER=localhost:9092
rpk topic -X brokers=$KAFKA_BROKER delete bid auction person
cargo run  -p dbsp_nexmark --example generate --features with-kafka -- --max-events 100000000 -O bootstrap.servers=$KAFKA_BROKER
FELDERA_API=http://localhost:8080
python3 benchmark/feldera-sql/run.py --api-url $FELDERA_API --kafka-broker $KAFKA_BROKER --query q9
