### ISSUE TITLE
SQL: STDDEV(DOUBLE) sometimes panics because SQRT cannot be taken of a negative number

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#1904]
In the Hopsworks integration: #1901, when we try to take STDDEV on double, we get errors like:
```
Unable to compute sqrt of -0.0000000000009094947017729282
```

I think this is to do with the precision of doubles. 
This doesn't happen when cast to DECIMAL. 

SQL query:

```sql
    SELECT
        STDDEV(amount) as stddev_amt -- amount is DOUBLE
    FROM hop
```

**Comment by mihaibudiu** [comment]
I can reproduce this with three values of .1e0
