### ISSUE TITLE
Add metrics from dbsp to grafana/prometheus endpoint

### ISSUE THREAD

**Issue by gz** [feldera/feldera#1925]

**Comment by blp** [comment]
@gz I don't know how grafana/prometheus work, what kind of work is this? Is it configuring those systems, adding something to dbsp to output to them, or something else?

**Comment by gz** [comment]
we already have support for them .. My plan was to extend our `/metrics` endpoint of the pipeline manager to also report the metrics we added for storage so we can view them in grafana

**Comment by blp** [comment]
Oh, I didn't know why /metrics was there separate from /stats. I see there was a comment, didn't notice that before.

Should we use https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/?

**Comment by gz** [comment]
>Should we use https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/?
yes that was my plan

It's this one, we haven't used it much in the last x months.. so maybe it no longer works but it should be made to work again I hope
https://github.com/feldera/feldera/blob/main/crates/pipeline_manager/src/metrics.rs

**Comment by blp** [comment]
> yes that was my plan

I like that plan.
