### ISSUE TITLE
Output buffer attributes required even when the output buffer is disabled

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1931]
![output_buffer](https://github.com/feldera/feldera/assets/8323135/40829a85-a8cd-40a2-b167-88d6ff05e471)

**Comment by gz** [comment]
this looks like it's still a string?
![image](https://github.com/feldera/feldera/assets/127654/6c827d3d-fbf6-4260-a83b-13ee5b7cf88f)
