### ISSUE TITLE
Too many program versions are compiled when program is edited in the UI

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#1937]
As I type in the UI modifying a program I see this in the logs:

```
pipeline-manager-1  | 2024-06-24 20:25:29 INFO [manager] Updated program maps to version 2 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:25:52 INFO [manager] Updated program maps to version 2 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:26:03 INFO [manager] Updated program maps to version 3 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:26:05 INFO [manager] Updated program maps to version 4 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:26:10 INFO [manager] Updated program maps to version 5 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:26:12 INFO [manager] Updated program maps to version 6 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:26:14 INFO [manager] Updated program maps to version 7 (tenant: 00000000-0000-0000-0000-000000000000)
pipeline-manager-1  | 2024-06-24 20:27:26 INFO [manager] 2024-06-24 20:27:26.129 UTC [46] LOG:  checkpoint starting: time
```

When I finish typing the final version of the program is queued:

![image](https://github.com/feldera/feldera/assets/19397042/8fb10f84-9f30-4139-9535-840120dd5068)

I presume that all other versions are being compiled. But these versions don't even exist anymore.

**Comment by ryzhyk** [comment]
Ongoing compilation gets canceled when a new program version is uploaded

**Comment by mihaibudiu** [comment]
5 minutes later the status is still "queued"

**Comment by ryzhyk** [comment]
Then it's a bug, but the bug is not that too many versions get compiled. What is the status of the program in the program list?

**Comment by mihaibudiu** [comment]
whatever edits I make to the program, it never changes from "queued"

**Comment by mihaibudiu** [comment]
and this was the only program in the list

**Comment by lalithsuresh** [comment]
This might be a backend issue tbh. What do you see in the logs?

**Comment by gz** [comment]
I assume the real issue here is https://github.com/feldera/feldera/issues/1935
