### ISSUE TITLE
Table browser seems flaky

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1962]
Run the secops demo, try browsing various tables/views.  Some of them appear empty, although they actually contain data. The issue is non-deterministic, but I can always reproduce it with a few clicks, e.g., right now the VULNERABILITY table is refusing to show up. I am not sure if this is a frontend or a backend issue.

**Comment by gz** [comment]
Is this with storage?

**Comment by ryzhyk** [comment]
Nope
