### ISSUE TITLE
SQL vs Rust performance in Nexmark

### ISSUE THREAD

**Issue by blp** [feldera/feldera#1982]
I ran Nexmark q9 with 10 million events and 16 cores in both SQL and Rust and dumped a profile afterward in each case. Storage was not enabled. I'm attaching the profile for thread 0 for each one: [sql.pdf](https://github.com/user-attachments/files/16059910/sql.pdf) [rust.pdf](https://github.com/user-attachments/files/16059911/rust.pdf).

Here is some analysis:
* SQL took 13.1 seconds, Rust took 6.0 seconds.
* SQL spent 1.1 seconds waiting, Rust actually waited long at 1.9 s. (I think this number is the amount of time waiting between steps or perhaps for an exchange operator to receive all the data from the other threads.)
* The SQL version took fewer steps (86) than the Rust version (251). I imagine that's because more input data could accumulate while the SQL version was running since it ran slower.
* The Rust version had the following operators that took >= 100 ms (total of 3.7 s):
  - An initial FlatMap: 415 ms.
  - An initial join: 1927 ms
  - Flatmap following join: 404 ms
  - Merging shards following exchange: 304 ms
  - TraceAppend in an aggregation: 314 ms
  - Upsert just before output: 386 ms
* The SQL version had the following operators that took >= 100 ms (total of 11.1 s):
  - An Apply2 operator on the input, followed by FilterKeys and Map: 735 ms
  - An initial join (including the output of the above chain): 3,934 ms
  - FilterKeys, Map, Map on the output of the join: 2,924 ms
  - Exchange and merging shards on the output of the above mapping: 2,864 ms
  - integrate_trace on the output of the exchange: 666 ms

My tentative conclusion is that it's not input that's slowing the Nexmark SQL performance the most. It's the query plan: the 3.9 second join in the SQL version is by itself longer than the major operators in the Rust version.

This does lead to the question of whether the two queries are doing the same thing. I haven't verified that.

**Comment by ryzhyk** [comment]
> SQL spent 1.1 seconds waiting, Rust actually waited long at 1.9 s. (I think this number is the amount of time waiting between steps or perhaps for an exchange operator to receive all the data from the other threads.)

I think it's mostly the latter.

**Comment by mihaibudiu** [comment]
The Rust code reads from a single table, which is a "union" table.
The SQL code reads from 3 tables, one of which is unused.
IN SQL there is an "output" operator attached to every input table, which takes a non-negligeable time.
If any apply takes time it should be the ones next to the input. It makes 0 sense for Apply2 to take a long time, since it executes always on a single small value.
The Rust code uses "inspect" for output, whereas Sql uses "Output".
I don't think the programs are equivalent; the join input counts are different. This may be due to the LATENESS annotation.

**Comment by ryzhyk** [comment]
> IN SQL there is an "output" operator attached to every input table, which takes a non-negligeable time.

Yep, all it does is clone the input batch to put it in the mailbox. 

> If any apply takes time it should be the ones next to the input. It makes 0 sense for Apply2 to take a long time, since it executes always on a single small value.

Yeah, I think it's the apply that implements the conditional filter, which also basically clones all data. We may want to have the compiler generate a region around it, so it's easier to identify in the graph.

**Comment by mihaibudiu** [comment]
But in Ben's SQL graph an apply2 in the middle of the graph takes a long time.

**Comment by ryzhyk** [comment]
I think this is the only expensive one (bottom left corner) and it looks like the conditonal filter:
![image](https://github.com/feldera/feldera/assets/8323135/2ce8e756-db51-475b-a524-ae85adc031c0)

**Comment by ryzhyk** [comment]
My best guess is that a lot of the overhead is related to the compiler not dropping unused columns. For example the SQL version seems to include all columns of the `BID` table in the output of the join, including a couple of unused string columns. Looking at the flamegraph of the SQL pipeline, I see a lot of string manipulation (you need to focus on individual workers, not the background thread).
![flamegraph](https://github.com/feldera/feldera/assets/8323135/2e8af693-7446-46a3-b23e-978cc256bf3c)

**Comment by mihaibudiu** [comment]
I will hopefully push soon a PR which will make some small quality improvements for this query.
The main difference may be that fewer strings will be cloned, by combining several stages (join-filter-map, map-mapindex).

(Unfortunately Calcite has an optimization to push projections before joins, but it is unsound, so we can't use it.
I may need to implement this myself at our level.)

Q9 is also not GC-able given the current compiler analysis. It relies on a comparison between monotone values in a join, which the compiler doesn't take advantage of. Until we can GC Q9 I don't think we can claim to implement it in a satisfactory way. Any performance measurements done on a prefix of the stream are not sustainable. I will have to think about how to do this properly using our program representation.

**Comment by mihaibudiu** [comment]
@blp can we close this issue?
