### ISSUE TITLE
mvn package build fails. SQL-compiler, invalid target release: 19

### ISSUE THREAD

**Issue by tigermatos** [feldera/feldera#1987]
**Describe the bug**
Attempting to build project (mvn package -DskipTests) fails. Invalid target release 19 for SQL-compiler.    

**To Reproduce**
 Steps to reproduce the behavior e.g., Curl commands or steps in the UI such as:  
1. install all dependencies  
2. run "mvn package -DskipTests"  
3. error  

**Expected behavior**
expected the build to go through. But it's my first time building this project.  

**Context (please complete the following information):**
 - Feldera Version: v0.19.0  
 - Environment: from source, on Ubuntu  
 - Browser: didn't get that far  
 - Pipeline Configuration/SQL code: didn't get that far  

**Additional context**
Just my first time building this project to try it out. But get error. I don't know if it's a bug. It could just be me.

**Comment by gz** [comment]
Hi, you'll need at least at least Java 19 installed. 

e.g., if you're on ubuntu `apt-get install openjdk-19-jre-headless`
on macos `brew install openjdk`
or downloading it from here https://jdk.java.net


let me know if that works, thanks!

**Comment by tigermatos** [comment]
I installed 19 before trying. (from https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.deb)

```
$ java -version
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

Does it have to be openjdk?
thanks

**Comment by gz** [comment]
There isn't anything that makes it only run on openjdk so others should work too -- we're installing this package from the ubuntu repository for our integration tests: https://github.com/feldera/feldera/blob/main/Earthfile#L20


fwiw this is my `java --version`, it's identical to yours, so the fact that you're getting this error is a bit puzzling.

```
java 19.0.2 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

Maybe try and restart the terminal you're running the command in after the java installation and try to delete the `target` folder in `sql-to-dbsp-compiler/SQL-compiler` before re-running.
