### ISSUE TITLE
benchmarks: generalize the nexmark benchmark script to support other benchmarks

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#1989]
I am not familiar with the details of our benchmark setup, so will leave it to @aehmttw  and @abhizer to fill in the details, but the goal is to reuse the nexmark script to run and plot other benchmarks, including the TikTok 1M records/s benchmark.

**Comment by blp** [comment]
I'm not sure that it makes sense to generalize the benchmark script itself. It doesn't do much. If it's a useful start for a script to run other benchmarks, that's great. I also wonder whether I should rewrite it in Python; it might be too much Bourne shell for the average person.

**Comment by ryzhyk** [comment]
@abhizer , can you describe what you need to do for the TikTok demo and which parts of the benchmarking infra you'd like to reuse?

**Comment by abhizer** [comment]
I meant this script: https://github.com/feldera/feldera/blob/main/benchmark/feldera-sql/run.py
Most of it should be reusable. 

Then we just need to add to: https://github.com/feldera/feldera/blob/main/scripts/bench.bash

After that we need to get the frontend to use the generated CSV file, I think. 
@aehmttw might be able to explain that part better.

**Comment by blp** [comment]
> I meant this script: https://github.com/feldera/feldera/blob/main/benchmark/feldera-sql/run.py Most of it should be reusable.

Oh! That makes sense. I support that. Thanks for clarifying.

**Comment by aehmttw** [comment]
An easy way to do this could be to extract the code in run.py that polls from stats and keeps track of it, and place the code into its own file which would have initialize, poll stats, and finish functions, which could be called from any test that is running a pipeline. If the tests are just different queries with different tables, the existing script could be modified to take in the queries/tables as inputs. Unless somebody else is on it, I plan to take a look at this for the coming sprint.

**Comment by aehmttw** [comment]
I made a pull request which modifies run.py to read SQL from a configurable file directory. Please let me know if that's adequate or if there's anything else you guys were looking for which I may be able to add.

https://github.com/feldera/feldera/pull/2013

@ryzhyk @abhizer

**Comment by abhizer** [comment]
@aehmttw Does this mean that adding a new folder (say, `custom`) and queries inside it (`custom/q0.sql`), the frontend will find this file and add it to the list of benchmarks?

**Comment by aehmttw** [comment]
It's not automatic currently. You'd have to run "run.py" with the argument --folder custom. Every run of "run.py" can be set to produce its own csv files. Would you like the detection to be automatic?

**Comment by abhizer** [comment]
I actually meant to ask if the generated csv file is picked up automatically by the frontend. But `run.py` auto-detecting new benchmarks also sounds great to me. Then hopefully, we don't need to mess with this or the CI for benchmarking again.

**Comment by aehmttw** [comment]
Currently not, a few things have to be added, such as saving the csv from earthly, and auto-detecting it from bench-publish. I might be able to add auto-detecting results csvs from bench-publish, if that would make things easier.
