### ISSUE TITLE
Support incremental AsOf joins in the compiler

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2009]
- [x] Implement ASOF joins in Calcite:
  - [x] Parser
  - [x] Validator
  - [x] SqlToRelConverter
  - [x] Convert to Enumerable
  - [x] Enumerable execution
  - [x] Submit Calcite PR: https://github.com/apache/calcite/pull/3883
  - [x] Get PR reviewed
  - [x] Get PR merged
  - [x] New Calcite release
- [ ] Implement ASOF support in our SQL compiler
  - [x] Generate code using ASOF DBSP operator
  - [ ] Design GC API for ASOF joins in DBSP 
  - [ ] Implement the static analysis for GC for ASOF joins

**Comment by mihaibudiu** [comment]
Submitted https://github.com/apache/calcite/pull/3883

**Comment by lalithsuresh** [comment]
@ryzhyk good to close?

**Comment by ryzhyk** [comment]
The unchecked boxes are still not done. I don't think they are urgent now, but we should track them.

**Comment by mihaibudiu** [comment]
I will close this issue since the remaining boxes are all covered by #2010
