### ISSUE TITLE
DECIMAL documentation and implementation disagree

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2012]
https://www.feldera.com/docs/sql/decimal/ says:
> The maximum precision supported is 128 binary digits (38 decimal digits). 

but we're using https://github.com/gz/rust-decimal, which says:
> The binary representation consists of a 96 bit integer number, a scaling factor used to specify the decimal fraction and a 1 bit sign.

so we should probably update the documentation to match.

Thanks to andrey36652 (Andrew) in Discord for reporting this issue.

**Comment by mihaibudiu** [comment]
Seems that the maximum precision is actually 28 with this library.
The crate's documentation also recommends https://crates.io/crates/bigdecimal, but it's hard to tell whether it has some showstopper problems. (It also recommends https://crates.io/crates/decimal-rs which I think we have tried, and which looks unmaintained.)

**Comment by Andrey36652** [comment]
https://crates.io/crates/bigdecimal should be slower (significantly?) as it deals with arbitrary precision decimals. It uses i64 to store scale and BigInt (from num-bigint crate) to store value. BigInt uses BigUint which is defined as
https://github.com/rust-num/num-bigint/blob/a25836ec6c341d1aa40c97335842f330b6a62911/src/biguint.rs#L35
So it's heap-allocated.

**Comment by mihaibudiu** [comment]
I tried to fix this bug, but it uncovers a Calcite bug. I have filed https://issues.apache.org/jira/browse/CALCITE-6464 with Calcite. If this is indeed a bug in Calcite, we'll need to solve that one first, and then make this change in our compiler. Otherwise the results of division operations using decimal values are too lossy.

**Comment by mihaibudiu** [comment]
Filed a PR to fix this in Calcite: https://github.com/apache/calcite/pull/3906, if accepted we can fix our side too.
