### ISSUE TITLE
[SQL] Internal type error, Vector when expected Tuple

### ISSUE THREAD

**Issue by cdouglas** [feldera/feldera#2017]
```
Vec<Tup1<s(16,false)?>> is not an instance of class org.dbsp.sqlCompiler.ir.type.DBSPTypeTuple
```

**To Reproduce**
`sql-to-dbsp tpcc.sql` (see attached)
[tpcc.sql.txt](https://github.com/user-attachments/files/16169272/tpcc.sql.txt)

From `main`, 74d37a5f77110a397dba014edfa21c76e6347506

The query is odd, but we also observed this error composing views using `LIMIT`.

**Comment by mihaibudiu** [comment]
I suspect it's related to #1957; if that's correct, this should be easy to fix

**Comment by mihaibudiu** [comment]
This is a funny query because it uses LIMIT without ORDER BY, so the result by the definition of SQL is rather non-deterministic.
