### ISSUE TITLE
SQL compilation shouldn't say "success" before rust compilation is done

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2031]
When programs pass SQL compilation, it says "Success" alongside "Saved", even when rust compilation isn't over and can potentially fail. This is confusing.

Reported by @xiasongh

**Comment by ryzhyk** [comment]
I think we still want to indicate that SQL compilation was successful, so maybe the label should say something like `SUCCESS [compiling Rust]`, and then simply `SUCCESS` when it's done.

**Comment by gz** [comment]
maybe replace SUCCESS with VALID (since there isn't success yet)

**Comment by lalithsuresh** [comment]
How about showing "[SQL] [RUST]". Both are gray in the beginning. 

SQL compilation makes it green and turns RUST yellow. Rust compilation succeeding makes both green. Either failing makes that one red.

**Comment by ryzhyk** [comment]
> How about showing "[SQL] [RUST]". Both are gray in the beginning (Pending state).
> 
> SQL compilation makes [SQL] green and turns [RUST] yellow. Rust compilation succeeding makes both green. Either failing makes that one red.

I like this option.

**Comment by ryzhyk** [comment]
@Karakatiza666 , shall we do this in the new UI?

**Comment by Karakatiza666** [comment]
In the old UI I will replace SUCCESS with VALID;
For the new UI I want to combine these two in the single status - where it's still clear that SQL is checked (compiled) but pipeline program is still being compiled. For UX purposes on UI side SQL compilation success is just an implementation detail of SQL syntax check so I don't want to dedicate any explicit marker to "SQL compilation success"

**Comment by lalithsuresh** [comment]
It's still one status, just displayed clearly as SQL vs Rust. Users so far know there are two stages to it (SQL vs Rust), primarily because they run into the rust side failing occasionally. Obscuring that detail, which is what we do now, seems to cause even more confusion.

**Comment by Karakatiza666** [comment]
Fixed by https://github.com/feldera/feldera/pull/2221
