### ISSUE TITLE
Support starting and pausing individual connectors

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2033]
We currently either start all connectors or pause all of them. The "pull" connectors like HTTP GET and S3 always start alongside the pipeline. It would be useful to specify whether a connector is in the started/paused state in the beginning and also change it individually at runtime. A desired state setting, basically.

Tagging @gz so you can consider it for the planned API changes.

Reported by @xiasongh

**Comment by mihaibudiu** [comment]
Maybe also expose the step of the circuit

**Comment by lalithsuresh** [comment]
@mihaibudiu you mean for monitoring purposes?

**Comment by mihaibudiu** [comment]
For complete control over what data is being processed in each step. By controlling the adapters and the circuit the user can have complete control over which data is being processed in each step.

**Comment by gz** [comment]
With the new API @snkas and @Karakatiza666 are working on this would come down to "starting/stopping a table".

I think the ergonomics of this will be slightly worse as it will lead to some amount of recompilation when adding/removing a table... Maybe we a table could take a list of connectors instead of tying it to just one connector per table this would avoid the recompilation.

**Comment by lalithsuresh** [comment]
@gz no, the goal is not to remove the table, but to start/pause the movement of data via the connector.

**Comment by gz** [comment]
I get that, but lets say you have two connectors  for a table. If you want to attach/detach one of them you can do this with the API. In the new form you need two tables for this (and you can make a 3rd table to union the two..). If you want to stop one, either you remove one from the union-set or remove the table, in both cases the program will change.

**Comment by ryzhyk** [comment]
This could be implemented as an ALTER TABLE statement maybe

**Comment by lalithsuresh** [comment]
I'm not sure I follow why we need recompilation or any tables are being removed. We might not be on the same page I think.

This isn't about attaching or detaching connectors, but pausing them. 

Think of what the `/v0/pipelines/foo/pause` API does today -- it pauses the connectors without reconfiguring the pipeline (it's still the same connectors + program in the pipeline). I'm envisioning something like `/v0/pipelines/foo/table/s3_xyz1/pause`. What it should do is tell the running pipeline's corresponding adapter to pause (i.e., invoke this: https://github.com/feldera/feldera/blob/bb922cc34be05cc99b879081201397c95e444a31/crates/adapters/src/transport/url.rs#L200)

This is going to be practically mandatory for operations.

**Comment by gz** [comment]
I see what you mean now, yes that should be possible.
