### ISSUE TITLE
Web console graphs and statistics disappeared

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2058]
When I run any pipeline, the graphs are blank and the statistics are all zero. The culprit seems to be commit 8a38423d ("WebConsole: Fix pipeline relation metrics not accumulated when there are multiple connectors per relation", 2024-07-12). When I revert that commit, the graphs and statistics appear correctly again.

My main test case is `benchmark/run-nexmark.sh -L sql --query 9 --partitions 1 --events 10M` but anything else worked for me too.

**Comment by blp** [comment]
@ryzhyk says it only happens for some pipelines for him.

I observed that the `/stats` endpoint still reported the correct numbers, so it's just a UI issue.

**Comment by lalithsuresh** [comment]
I reverted 8a38423.
