### ISSUE TITLE
Unify profile and metrics

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2073]
The Rust code has two different mechanisms to collect performance data: metrics and profile.
I think these two should be unified into a single mechanism, which has the union of capabilities.
The data should be retrievable through the retrieve_profile() API and also accessible through the web API.

**Comment by blp** [comment]
The profile is a graph annotated with statistics on some nodes, the metrics are mostly global counters. What does the unification look like?

**Comment by mihaibudiu** [comment]
Same APIs to access them.

**Comment by blp** [comment]
What data structure is the result of the unification of a graph and a collection of counters?

I am serious here. I don't know what this should look like. Since the profile is a .zip file that contains a bunch of .dot files, do you want metrics there as an extra .csv file or something?

**Comment by mihaibudiu** [comment]
No, I mean the circuit.retrieve_profile() Rust API. Not the dot file.

**Comment by mihaibudiu** [comment]
The dot file is just a serialization of the data structure

**Comment by blp** [comment]
OK, I'm beginning to understand.

I think this idea has a fundamental impedance mismatch, because these profiles are per-worker but metrics are per-process (not even per-circuit although we only currently care about one circuit per process). We don't currently have a plan to reimplement metrics to be per-worker.

**Comment by mihaibudiu** [comment]
Think of both as databases providing views of the circuit. You have workers and operators, but you can do rollups too, so you should be able to aggregate profiles per node from all workers, and per circuit from all nodes. There is no reason profile data should not be retrievable using the web api.

**Comment by ryzhyk** [comment]
The profile is really a juxtaposition of the static dataflow graph and per-thread, per-operator performance counters. The former can be returned by a separate endpoint. The latter look a lot like metrics (although as @blp  pointed out they don't live in the global namespace).

**Comment by mihaibudiu** [comment]
Superseded by #2283
