### ISSUE TITLE
RFC: Connector orchestration

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2096]
## Motivation

Today all input connectors are started, paused, and unpaused simultaneously along with the pipeline.  In some scenarios the user may need to enable individual connectors in a particular order. For example, a table can be connected to an S3 bucket for backfill and a Kafka topic for streaming. We would like to run the former until the entire snapshot is read, and then enable the latter.

## Design

A minimal implementation of this feature includes:

* Add a flag to connector configuration indicating whether the connector should start in enabled or disabled state. The default is `true`, so by default connectors are enabled, as they are today. 

* Add an API endpoint to enable/disable individual connectors at runtime.

Connector behavior is determined by its enabled/disabled state and the paused/running state set by the pipeline:

| Connector state set by the user | Connector state set by the pipeline  | Effective connector state|
|----------|----------|----------|
| Enabled   | Running   |  Running   |
| Disabled | Running    | Paused |
| Enabled | Paused | Paused |
| Disabled | Paused | Paused |

### Connector configuration

Assuming the new API:

```sql
CREATE TABLE example (
    id INT NOT NULL PRIMARY KEY
) WITH (
    'connectors' = '[{
        "name": "backfill",
        "enabled": true,
        "transport": {...},
        "format": {...}
    }, {
        "name": "stream",
        "enabled": false,
        "transport": {...},
        "format": {...}
    }]'
);
```

Note that we allow a list of connectors, with each connector having a name unique for the given table and the optional `enabled` flag, which controls initial status of the connector. If the name is not specified, a unique id will be generated instead.

### API endpoint

I could use some advice on the best REST API design practices. But how about a `PATCH` endpoint `/pipelines/my_pipeline/sources/my_table.my_connector?enabled=true`?

For tables with a single attached connector, connector name can be elided.

**Comment by lalithsuresh** [comment]
I'd keep the naming identical to whatever we use today for pipeline's state of being started/paused/shutdown. I don't think it's called "enabled".

We already have the `POST /v0/pipelines/my_pipeline/{action}` endpoint, which we use for pipeline start/stop/shutdown. So we need to make sure the URL routing doesn't conflict.

If it doesn't conflict, then `POST /v0/pipelines/my_pipeline/connectors/{table_name}.{connector_name}/{action}` where action can be start or pause would be the consistent way to go.

**Comment by gz** [comment]
imo we should just make the connector name globally unique within the pipeline and avoid the table.connector thing

**Comment by ryzhyk** [comment]
> I'd keep the naming and endpoint similar to whatever we use today for pipeline's state of being started/paused/shutdown. I don't think it's called "enabled".

I deliberately picked a different term, because this is a slightly different concept.  The pipeline will _pause_ the connector when its buffer is full or the whole pipeline is getting paused.  It can then unpause the connector, which will only start running it is _enabled_.

**Comment by ryzhyk** [comment]
> We already have the POST /v0/pipelines/my_pipeline/{action} endpoint, which we use for pipeline start/stop/shutdown. So we need to make sure the URL routing doesn't conflict.

> If it doesn't conflict, then POST /v0/pipelines/my_pipeline/connectors/{table_name}.{connector_name}/{action} where action can be start or pause would be the consistent way to go. It also allows us to interact with input and output connectors consistently.

`/action` makes sense. `connectors` instead of `sources` is also ok I guess.  There is no concept of enabling (or pausing) output connectors but I can see how that can be useful.

**Comment by ryzhyk** [comment]
> imo we should just make the connector name unique within the pipeline and avoid the table.connector thing

I'm going back and forth with this. Since connectors are no longer global, but are always associated with a table, it seems unnecessary to force unique names for them. OTOH, `table.connector` or even `table/connector` is indeed awkward. I'm ok with globally unique connector names, especially because we will only need them for connectors that we want to control via the API.

**Comment by lalithsuresh** [comment]
> The pipeline will pause the connector when its buffer is full

It sounds more like this backpressure scenario is the odd one. I'd rather rename this case from pause to "backpressure" or something else, given it's an internal detail and not a concept most users need to know.

So:
* pipeline pausing => all connectors are paused
* pause a connector => that connector is paused and stops pushing data
* buffer full => pipeline marks the connector as backpressure/bikeshed. The connector will only resume from the bikeshed state if the connector is not in paused state.

**Comment by ryzhyk** [comment]
Ok, we'll use "pause/start" everywhere. There is an awkward combination when the connector state is RUNNING but the pipeline is PAUSED, so the connector is not actually running.

**Comment by lalithsuresh** [comment]
> OTOH, table.connector or even table/connector is indeed awkward.

table.connector is not that unusual given SQL naming conventions. We can make it so that if the name is not ambiguous, "connector" works. If it is ambigious, it needs to be qualified as "table.connector".

**Comment by ryzhyk** [comment]
> > OTOH, table.connector or even table/connector is indeed awkward.
> 
> table.connector is not that unusual given SQL naming conventions. We can make it so that if the name is not ambiguous, "connector" works. If it is ambigious, it needs to be qualified as "table.connector". The easiest starting point is table.connector though.

I think, if connector names are scoped within their table, then "table" should be the default when there is only one connector.

**Comment by lalithsuresh** [comment]
> > > OTOH, table.connector or even table/connector is indeed awkward.
> > 
> > 
> > table.connector is not that unusual given SQL naming conventions. We can make it so that if the name is not ambiguous, "connector" works. If it is ambigious, it needs to be qualified as "table.connector". The easiest starting point is table.connector though.
> 
> I think, if connector names are scoped within their table, then "table" should be the default when there is only one connector.

Yes. I prefer they're scoped within their tables. So we'd have:

`POST /v0/pipelines/my_pipeline/connectors/{table_name}/{action}`  // when there is only one connector
`POST /v0/pipelines/my_pipeline/connectors/{table_name}.{connector_name}/{action}` // when there are multiple connectors

**Comment by ryzhyk** [comment]
Closing via #2113
