### ISSUE TITLE
Allocated bytes/used bytes ratio is too high.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2102]
After running the TikTok pipeline with storage disabled to completion, I get its profile using `/dump_profile`.  Here is the resulting profile for worker 0:

![0](https://github.com/user-attachments/assets/da1203fd-cc80-482e-a906-dc8730675a78)

I notice that most Z-1's have 2x-4x more `allocated bytes` than `used bytes`. If these measurements are accurate, they indicate that we waste a lot of memory.

I saw this with other pipelines too, so it's not just tiktok.

**Comment by mihaibudiu** [comment]
Can you elaborate on how this happens?

**Comment by gz** [comment]
>Can you elaborate on how this happens?

my guess is vectors that grow too big and are reused but not resized

**Comment by lalithsuresh** [comment]
> > Can you elaborate on how this happens?
> 
> my guess is vectors that grow too big and are reused but not resized

Yup. That, or dynamic vector growth.

**Comment by ryzhyk** [comment]
> Can you elaborate on how this happens?

I don't know yet.

**Comment by blp** [comment]
See https://github.com/feldera/feldera/pull/2127

**Comment by blp** [comment]
Fixed with #2127
