### ISSUE TITLE
The great conversion

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2121]
Make sure these links/files are converted to use the new API. Commit your changes directly on Simon's PR branch:
Note some of them might not need any changes, but it's better to check them all.

@lalith
- [x] https://github.com/feldera/feldera/blob/main/README.md (see https://github.com/feldera/feldera/pull/2150)
- [x] https://www.feldera.com/docs/tutorials/rest_api/ (https://github.com/feldera/feldera/pull/2153)
- [x] https://www.feldera.com/docs/api/rest/ (lalith: the API docs could use minor tidying up but no biggie)
- [x] https://www.feldera.com/api (everything under it make sure docs make sense)
- [x] https://github.com/feldera/feldera/blob/main/demo/README.md (https://github.com/feldera/feldera/pull/2154)
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo09-S3/run.py (https://github.com/feldera/feldera/pull/2154)

@blp
- [x] https://www.feldera.com/docs/concepts
- [ ] https://www.feldera.com/docs/tour/
- [ ] https://www.feldera.com/docs/contributors/ui-testing
- [ ] https://github.com/feldera/feldera/tree/main/demo/docs-demo
- [x] https://github.com/feldera/feldera/blob/main/benchmark/README.md
- [x] https://github.com/feldera/feldera/blob/main/benchmark/feldera-sql/README.md

@snkas 
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo05-DebeziumMySQL
- [x] https://www.feldera.com/docs/connectors/sources/http-get

@mihaibudiu
- [x] https://www.feldera.com/docs/connectors/sources/http
- [x] https://www.feldera.com/docs/connectors/sinks/http
- [x] https://www.feldera.com/docs/connectors/sources/delta
- [x] https://www.feldera.com/docs/connectors/sources/kafka
- [x] https://www.feldera.com/docs/connectors/sources/debezium-mysql
- [x] https://www.feldera.com/docs/connectors/sinks/delta
- [x] https://www.feldera.com/docs/connectors/sinks/kafka
- [x] https://www.feldera.com/docs/connectors/sinks/snowflake
- [x] https://www.feldera.com/docs/contributors/compiler

@ryzhyk
- [x] https://www.feldera.com/docs/tutorials/basics/part1 #2161
- [x] https://www.feldera.com/docs/tutorials/basics/part2 #2161
- [x] https://www.feldera.com/docs/tutorials/basics/part3 #2161
- [x] https://www.feldera.com/docs/tutorials/basics/part4 #2161 
- [x] https://www.feldera.com/docs/use_cases/fraud_detection/ #2151 
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo06-SupplyChainTutorial/run.py #2155 
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo10-FraudDetectionDeltaLake #2151
- [x] https://github.com/feldera/feldera/tree/main/demo/project_demo11-Hopsworks #2175 
- [x] https://github.com/feldera/feldera/blob/main/demo/demo_notebooks/fraud_detection.ipynb #2151
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo02-FraudDetection #2151 
- [x] All fraud detection blogs
- [x] https://github.com/feldera/feldera/tree/main/demo/project_demo08-DebeziumJDBC #2162 
- [x] https://github.com/feldera/feldera/tree/main/demo/project_demo13-DebeziumPostgres #2165 

@gz
- [x] https://www.feldera.com/docs/tutorials/monitoring/
- [x] https://www.feldera.com/docs/api/json
- [x] https://www.feldera.com/docs/api/parquet
- [x] https://www.feldera.com/docs/api/csv
- [x] https://github.com/feldera/feldera/tree/main/demo/demos/product-availability
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo00-SecOps/run.py
- [x] https://github.com/feldera/feldera/blob/main/demo/project_demo12-HopsworksTikTokRecSys/
- [x] https://github.com/feldera/feldera/tree/main/demo/demos/productitems-continuous

@abhizer
- [x] https://www.feldera.com/python/index.html
- [x] https://github.com/feldera/feldera/tree/main/python
- [x] https://www.feldera.com/blog/eventbridge-and-feldera/

## Ignored for now

Maybe we can delete some of them.

- [ ] https://github.com/feldera/feldera/blob/main/demo/hello-world/run.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/project_demo01-TimeSeriesEnrich/run.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/project_demo03-GreenTrip/run.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/project_demo04-SimpleSelect/run.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/simple-count/run.py
- [x] https://github.com/feldera/feldera/blob/main/demo/simple-join/run.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/steady/demo.py
- [ ] https://github.com/feldera/feldera/blob/main/scripts/compilation_speed_benchmark.py
- [ ] https://github.com/feldera/feldera/blob/main/demo/project_demo07-SnowflakeSink

**Comment by lalithsuresh** [comment]
Fraud detection delta lake should be on the main list.

**Comment by snkas** [comment]
New API spec:
- Checkout the PR: https://github.com/feldera/feldera/pull/2071
- Run the pipeline-manager (note that it will delete all existing pipeline-related tables)
- Go to: http://localhost:8080/swagger-ui/

**Comment by lalithsuresh** [comment]
I sneakily moved some benchmarking links to Ben. :)

**Comment by gz** [comment]
When working on the demo directories while we're at it: Let's remove the `project_XX-` prefix in all folders and (for those that don't exercise the python SDK) let's consistently name the file `program.sql` and make sure there is a `README.md` or similar top-level comment in the SQL file explaining what this thing does

**Comment by lalithsuresh** [comment]
@gz I think it's much better for the SQL file itself to embed via comments what the program does. This way, the in-product-demos will also have that documentation.

**Comment by gz** [comment]
if we can do that consistently, maybe not having a folder at all for these demos and just a descriptive filename is best.

**Comment by lalithsuresh** [comment]
> if we can do that consistently, maybe not having a folder at all for these demos and just a descriptive filename is best.

Yup, 100% agree.

**Comment by blp** [comment]
@gz I'm working on the secops demo because it's essential to the tour that I got assigned.

**Comment by blp** [comment]
> @gz I'm working on the secops demo because it's essential to the tour that I got assigned.

I finished with the secops demo but I'm new to this new API so some eyes on it would be cool.

**Comment by ryzhyk** [comment]
Moved snowflake sink to the ignored-for-now list

**Comment by mihaibudiu** [comment]
Can we close this?
