### ISSUE TITLE
Ability to do "Run in Sandbox" Buttons for Demos

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2133]
Ideally we should have buttons a user can click that sends them to the sandbox and populates the SQL code for a given demo.

e.g., other apps I've seen essentially use HTTP GET arguments for this and append `?sql=bla&name=bla` to the login url which then will prepopulate the SQL editor/pipeline after you've logged in...

**Comment by Karakatiza666** [comment]
Implemented by https://github.com/feldera/feldera/pull/2255
