### ISSUE TITLE
py: OutputHandler.to_dict() makes Null values NaN when it should be None

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#2142]
Original format of the result:
```
[{'id': 0, 'c1': 1, 'c2': 11, 'c3': 16, 'c4': 22, 'c5': 5, 'c6': 33, 'c7': 70, 'c8': 44, 'insert_delete': 1},
 {'id': 1, 'c1': 11, 'c2': 22, 'c3': Null, 'c4': 45, 'c5': 51, 'c6': 61, 'c7': 72, 'c8': 88, 'insert_delete': 1}]
```
 
After the result goes through OutputHandler.to_dict():
```
 [{'id': 0, 'c1': 1, 'c2': 11, 'c3': 16.0, 'c4': 22, 'c5': 5, 'c6': 33, 'c7': 70, 'c8': 44, 'insert_delete': 1},
 {'id': 1, 'c1': 11, 'c2': 22, 'c3': nan, 'c4': 45, 'c5': 51, 'c6': 61, 'c7': 72, 'c8': 88, 'insert_delete': 1}]
```

**Comment by mihaibudiu** [comment]
Does this only happen for floating point?

**Comment by abhizer** [comment]
I am unsure. When the python client gets data from feldera, it normally creates a dataframe and while doing that, I think this happens for `Null` and likely `NaN`. Fixing this requires a slight change in the current api to not convert it to a dataframe at all, and return the JSON as is. 

Currently, `pipeline.foreach_chunk()` takes a closure that accepts a dataframe. 

So it is a design question of if we should have: 
1. `pipeline.foreach_chunk_raw()` for raw data? 
2. `pipeline.foreach_chunk_df()` for dataframes, and the current one for raw data? 
3. Or something else.

**Comment by mihaibudiu** [comment]
That sounds to me like it's a bug waiting to bite us. We want the dataframe to reflect the correct values.
So even if you use a _raw() function, the problem will remain for dataframes.

**Comment by abhizer** [comment]
Yeah, this is problematic. 
Maybe telling the pandas dataframe about the type of the columns can help, but this might be complicated for complex types. 

The easiest thing to do would be to only return raw data (as a python dict) and ask people to manually convert to pandas if they need it. Then, they can likely supply the appropriate datatypes for problematic columns.

**Comment by abhizer** [comment]
The plan for solving this is to have a table mapping feldera supported types with pandas supported types and giving pandas this schema while creating the dataframe.
