### ISSUE TITLE
SQL: PRIMARY KEY requires NOT NULL

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2145]
The following SQL:
```
CREATE TABLE example (
    id INT PRIMARY KEY
);
```
... returns with SQL error:
```
PRIMARY KEY column 'id' has type INTEGER, which is nullable
```

Expected behavior is I think that it infers from PRIMARY KEY that it must be NOT NULL?

**Comment by snkas** [comment]
It also happens for `FOREIGN KEY`

**Comment by mihaibudiu** [comment]
Foreign keys can be null 
I don't know if I plan to fix this. It's useful for people to know that primary keys cannot be null

**Comment by snkas** [comment]
Ah sorry, true, I had PRIMARY KEY (id) later on in the table definition, hence it also raised the issue for id which was not related to it having a FOREIGN KEY reference.

**Comment by snkas** [comment]
Thanks, just thought I should bring it up :+1:

**Comment by mihaibudiu** [comment]
We should follow what other SQL dialects do.
If they allow non null primary keys we can turn this error into a warning.
The compiler should probably turn convert the type anyway.
This is important because the input adapter will reject tuples with nulls in key fields.

**Comment by lalithsuresh** [comment]
I think this is more an issue with the error. It should say if possible that primary key columns must be non null.

**Comment by mihaibudiu** [comment]
The error message says exactly that

**Comment by mihaibudiu** [comment]
Well, almost

**Comment by lalithsuresh** [comment]
It says: "PRIMARY KEY column 'id' has type INTEGER, which is nullable", which doesn't say why this is an error. If it's an easy fix, worth changing it into something like "PRIMARY KEY columns have to be NON NULL. But column 'id' has type INTEGER, which is nullable."

**Comment by mihaibudiu** [comment]
Actually, the full error message printed at stderr is the following:
`error: PRIMARY KEY cannot be nullable: PRIMARY KEY column 'C' has type INTEGER, which is nullable`
In the json data structure with the error returned from the compiler the structure is this:
```
{
  "startLineNumber" : 2,
  "startColumn" : 4,
  "endLineNumber" : 2,
  "endColumn" : 8,
  "warning" : false,
  "errorType" : "PRIMARY KEY cannot be nullable",
  "message" : "PRIMARY KEY column 'C' has type INTEGER, which is nullable",
  "snippet" : "    2|   c INT PRIMARY KEY\n         ^^^^^\n    3|);\n"
}
```

The full error message should contain both the errorType and the message. 
So I will mark this as an invalid issue.
However, I will make a change: if the compiler --lenient flag is passed, then I will only produce a warning for this case.
