### ISSUE TITLE
Product availability demo does not compile due to primary key error

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2174]
The default example that the new UI loads (product availability), has tables with primary key columns

```
-- Warehouse
CREATE TABLE warehouse (
    id INT PRIMARY KEY,
    name VARCHAR NOT NULL,
    address VARCHAR NOT NULL
);

```

which throw an error about PRIMARY KEY columns having to be non null. Did the demo change or was this a regression?

Let's either fix the demos or have 'primary key' imply non-null as is the case I believe with most databases.

**Comment by ryzhyk** [comment]
We no longer allow nullable primary keys. The demo needs to be updated.

**Comment by gz** [comment]
Hm I updated it and tried it in the UI but I mustve forgotten to recompile the sql compiler.

**Comment by lalithsuresh** [comment]
@ryzhyk the right behavior is for primary keys to automatically be non-null, rather than have to mark it explicitly (e.g., MySQL and Postgres both do this).

**Comment by mihaibudiu** [comment]
This is because you can actually dynamically alter the keys. Not in our case

**Comment by snkas** [comment]
Related issue: https://github.com/feldera/feldera/issues/2145

**Comment by mihaibudiu** [comment]
I have been working on a set of optimizations dedicated specially to streaming programs. These are not yet fully ready, but since they include a fix for this problem I will submit the PR and continue implementing the optimizations in a separate PR.

**Comment by mihaibudiu** [comment]
Seems like the version in main has NOT NULL primary keys, so it compiles fine.
