### ISSUE TITLE
[SQL] [adapter] Create an adapter to populate the NOW table

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2235]
The adapter has to insert a new TIMESTAMP value every step.
It should not delete the previous value.

**Comment by blp** [comment]
The documentation says that the previous value should be deleted:
> The user has to maintain the invariant that this table always contains a single value. Moreover, deleting a value and inserting a new one requires the newly inserted value to be larger than the original value.

If only insertions are expected then the documentation should be updated.

**Comment by mihaibudiu** [comment]
I have updated the documentation in the last PR I merged.

**Comment by mihaibudiu** [comment]
I am not sure when it gets pushed to the website
