### ISSUE TITLE
[SQL] Clarify method to declare materialization for views

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2253]
The following SQL view declarations have the following materialized field results:
```
CREATE VIEW example1 WITH ('materialized' = 'false') AS SELECT 1; -- Result: materialized = false
CREATE VIEW example2 WITH ('materialized' = 'true') AS SELECT 1; -- Result: materialized = false
CREATE MATERIALIZED VIEW example3 WITH ('materialized' = 'false') AS SELECT 1; -- Result: materialized = true
CREATE MATERIALIZED VIEW example4 WITH ('materialized' = 'true') AS SELECT 1; -- Result: materialized = true
```

It would be clearer if either tables and views use the same method to declare materialization or that an error is thrown if the materialized property is used for views.

**Comment by ryzhyk** [comment]
The `materialized` attribute is only defined for tables (since there is no `CREATE MATERIALIZED TABLE` syntax in SQL). I suppose we should raise an error if we encounter it in view declarations and advice the user to use `CREATE MATERIALIZED VIEW` instead.
