### ISSUE TITLE
SQL: Compilation error: Post-process result type i8 different from empty set type i8?

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#2261]
For a SQL program with the query: 

```
CREATE TABLE stddev_groupby(
                    id INT, c1 TINYINT, c2 TINYINT NOT NULL, c3 INT2, c4 INT2 NOT NULL, c5 INT, c6 INT NOT NULL,c7 BIGINT,c8 BIGINT NOT NULL);

CREATE VIEW stddev_view AS SELECT
                            id, STDDEV_SAMP(c1) AS c1, STDDEV_SAMP(c2) AS c2, STDDEV_SAMP(c3) AS c3, STDDEV_SAMP(c4) AS c4, STDDEV_SAMP(c5) AS c5, STDDEV_SAMP(c6) AS c6, STDDEV_SAMP(c7) AS c7, STDDEV_SAMP(c8) AS c8
                         FROM stddev_groupby
                         GROUP BY id;
```

The compilation fails with:
_**{'SqlError': [{'start_line_number': 0, 'start_column': 0, 'end_line_number': 0, 'end_column': 0, 'warning': False, 'error_type': 'Compiler error', 'message': 'Post-process result type i8 different from empty set type i8?', 'snippet': ''}]}**_

Interestingly, the same query without the group by clause compiles fine.

**Comment by mihaibudiu** [comment]
This is exactly why we need these tests.

**Comment by mihaibudiu** [comment]
BTW: there are no columns with type SHORTINT
