### ISSUE TITLE
Collect per-connector/per-circuit metrics in the `adapters` crate.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2287]
Here are the pipeline- and connector-level metrics we track today. With the exception of `steps`, these are exposed via the `/stats` endpoint. We will additionally expose them as Prometheus metrics. 

Note, this does not include detailed circuit metrics that will be exported by DBSP.

## Pipeline-level metrics

- `steps` - number of steps completed by the circuit

- `state`: state of the pipeline: running, paused, or terminating.

- `rss_bytes` - resident set size of the pipeline process, in bytes.

- `cpu_msecs` -  CPU time used by the pipeline process, in milliseconds.

-  `buffered_input_records` -  total number of records currently buffered by all endpoints.

- `total_input_records` - total number of records received from all endpoints.

- `total_processed_records` - Total number of input records processed by the DBSP engine. Note that some of the outputs produced for these input records may still be buffered at the output endpoint. Use `OutputEndpointMetrics::total_processed_input_records` for end-to-end progress tracking.

## Input endpoint metrics

- `total_bytes` - total bytes pushed to the endpoint since it was created.

- `total_records` - total records pushed to the endpoint since it was created.

- `buffered_bytes` - number of bytes currently buffered by the endpoint (not yet consumed by the circuit).

-  `buffered_records` number of records currently buffered by the endpoint (not yet consumed by the circuit).

- `num_transport_errors`  - number of transport errors

-  `num_parse_errors` - number of parser error

## Output endpoint metrics

- `transmitted_records` - number of records sent to the output transport

- `transmitted_bytes`  - number of bytes sent to the output transport

- `queued_records`  - number of queued records. These are the records sent by the main circuit thread to the endpoint thread. Upon dequeuing the record, it gets buffered or sent directly to the output transport.

- `queued_batches` - number of queued batches

- `buffered_records` - number of records pushed to the output buffer. Note that this may not be equal to the current size of the buffer, since the buffer consolidates records, e.g., inserts and deletes can cancel out over time.

- `buffered_batches` - number of records pushed to the output buffer.

- `num_encode_errors` - number of format encoder errors

- `num_transport_errors`  - number of transport errors

- `total_processed_input_records` - The number of input records processed by the circuit. This metric tracks the end-to-end progress of the pipeline: the output of this endpoint is equal to the output of the circuit after processing `total_processed_input_records` records.

# Additional metrics we may want to track

- CPU utilization per parser/encoder.

- Total disk usage collected from the OS: number of files, size, IOPS

**Comment by lalithsuresh** [comment]
We also need metrics for storage use.

**Comment by ryzhyk** [comment]
> We also need metrics for storage use.

That's going to come from DBSP; although maybe we could track total FS usage here.

**Comment by gz** [comment]
>although maybe we could track total FS usage here, similar to how we track RSS

this is a system metric, IMO it should be collected by something that's monitoring the host grafana/netdata etc already support this

**Comment by ryzhyk** [comment]
There is a prometheus plugin for node level metrics, but we need them per pipeline.

**Comment by gz** [comment]
> maybe we could track total FS usage here, similar to how we track RSS.

we already have these metrics in dbsp though ben disabled a few because it was too expensive

**Comment by lalithsuresh** [comment]
@ryzhyk is this good to close?

**Comment by ryzhyk** [comment]
Nope, we still need to expose per-circuit metrics to prometheus.
