### ISSUE TITLE
[WEBUI] Configure window does not have a "Cancel" button

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2294]

**Comment by mihaibudiu** [comment]
![image](https://github.com/user-attachments/assets/76c2a3b8-b8f7-439e-a427-e45ac72e8466)

**Comment by lalithsuresh** [comment]
Does ctrl+z / cmd+z do the undo you need?

**Comment by mihaibudiu** [comment]
that works, at least for a small number of edits.
