### ISSUE TITLE
SQL: Attempt to overflow a Data Type results in wrap around

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#2316]
For a SQL program such as:

```
CREATE TABLE sum(c1 TINYINT);
```

```
CREATE VIEW sum_view AS SELECT SUM(c1) AS c1 FROM sum
```

When attempting to aggregate the values such that the final result is too large to fit in the data type range, instead of overflowing, the result wraps around. 

Inserting values: 127 and 1 results in: -128

**Comment by mihaibudiu** [comment]
#2341

**Comment by rivudhk** [comment]
It panics for me too. And this is the error message that I get.

**Comment by mihaibudiu** [comment]
panic is the expected behavior.
Producing -128 is wrong.
So which one is happening?

**Comment by rivudhk** [comment]
Ah. I apologise. It seems I confused this issue's comment thread with the other issue. 

Here, it doesn't panic for me. I just get -128.

**Comment by mihaibudiu** [comment]
Can you supply a program that reproduces this bug?
I couldn't create one. In fact, I have written a test which passes (by panicking, as expected):https://github.com/feldera/feldera/pull/2341

**Comment by rivudhk** [comment]
With this, I get the result: -128

```
import unittest
from feldera import PipelineBuilder, Pipeline
from tests import TEST_CLIENT

class TestFailNull(unittest.TestCase):
    def test_overflow(self):
        table_name = "overflow"
        view_name = "overflow_view"
        
        sql = f"""   
        CREATE TABLE {table_name}(c1 TINYINT);
        
        CREATE VIEW {view_name} AS SELECT SUM(c1) AS c1 FROM {table_name};"""

        pipeline = PipelineBuilder(TEST_CLIENT, name="test_overflow", sql=sql).create_or_replace()

        data = [{"insert":{"c1": 127}},{"insert":{"c1": 1}}]       
        out = pipeline.listen(view_name)
        pipeline.start()
        pipeline.input_json(table_name, data, update_format="insert_delete")
        pipeline.wait_for_completion(True)

        out_data = out.to_dict()
        print(out_data)
```

**Comment by mihaibudiu** [comment]
Figured out why the test I wrote didn't find this bug: it runs in debug mode, and Rust in debug mode does checked arithmetic. Your test runs in release mode, and the arithmetic is not checked.

**Comment by mihaibudiu** [comment]
This will require a fix for https://github.com/feldera/feldera/issues/2351
