### ISSUE TITLE
[DBSP] the `partitioned_rolling_aggregate_linear` operator should be adapted

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2327]
with an API similar to the one from #2323

**Comment by mihaibudiu** [comment]
I am wondering whether the non-linear aggregate operators shouldn't also use a similar API

**Comment by ryzhyk** [comment]
That's definitely possible

**Comment by mihaibudiu** [comment]
Since there is no real benefit I will close this issue.
