### ISSUE TITLE
Allow limiting step size independent of input buffer size

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2330]
See discussion #2314. Here's a summary:

We already do buffer size for connectors and allow the user to control it. The default limit is 1,000,000 records, which is effectively unlimited when individual records are large or expensive to process (the records average about 13.5 kB for this demo).

This issue calls for limiting admissions from the buffers to the steps, so that even if we've buffered a given number of records we don't necessarily process all of them in the next step. This would give us another layer of control.

Either way, it would make sense to use some kind of dynamic feedback to control the processing rate. Suppose we add a target step duration. It could default to, for example, 1 second. Then, if a step takes longer than 1 second, we reduce the target buffer size (or admission size); if it takes less than one second, we increase it.

One issue with limiting the buffer size is going to be Kafka, which doesn't like to be paused. Maybe that's why having an admission control layer is a good idea: instead of pausing Kafka when we fill the buffer, we only need to pause it when we get `N1*A` records for some `N1` where `A` is the number we admit per step, and then resume it when the number drops to `N2*A` records for some `N2 < N1`. Then we can absorb the slowness of the resume.

**Comment by ryzhyk** [comment]
@blp , can we close this?
