### ISSUE TITLE
[WEBUI] Stuck in edit configuration

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2332]

**Comment by mihaibudiu** [comment]
After a pipeline failed I opened the "edit configuration" menu. I can't edit, since it's read-only.
I cannot close the menu since the "apply" button is disabled.
There's nothing I can do.

**Comment by mihaibudiu** [comment]
![image](https://github.com/user-attachments/assets/e4660ca0-c07a-4d4b-bbbd-73623c74d665)

**Comment by gz** [comment]
click anywhere outside of that dialog and it will disappear

**Comment by mihaibudiu** [comment]
Duplicate of #2294
