### ISSUE TITLE
[WEBUI] UI does not differentiate between warnings and errors

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2367]
They should not be displayed in the same way.

**Comment by Karakatiza666** [comment]
Are you talking about SQL compiler messages? If so, could you provide code snippet to reproduce?

**Comment by mihaibudiu** [comment]
for example add the following to your SQL:
`CREATE FUNCTION F(X INT) RETURNS INT;`
will trigger a warning

**Comment by Karakatiza666** [comment]
Would it make sense to rename "Errors" tab to "Issues", and have it diisplay both errors and warnings there?

**Comment by gz** [comment]
yes

**Comment by mihaibudiu** [comment]
I think it's fine to leave it "errors", but show something slightly different
