### ISSUE TITLE
why is the binary removed when the pipeline is stopped

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2390]
the binary that runs the program is removed from the path where it ran from when the pipeline is stopped... It looks like it gets copied there every time. Maybe it would be better to keep the binary there? The minor annoyance that led me to this is that if you want to use perf on a program, it won't find the symbols anymore once the pipeline is stopped.

```
feldera/benchmark/feldera-sql on  main [$?] via 🐍 v3.12.3 took 18s 
❯ stat /home/gz/.feldera/pipelines/pipeline0191b098-dfea-7b50-8dea-c51a8daf1e57/program_0191b098-dfea-7b50-8dea-c51a8daf1e57_v3
  File: /home/gz/.feldera/pipelines/pipeline0191b098-dfea-7b50-8dea-c51a8daf1e57/program_0191b098-dfea-7b50-8dea-c51a8daf1e57_v3
  Size: 173619224 	Blocks: 339112     IO Block: 4096   regular file
Device: 259,14	Inode: 59169233    Links: 2
Access: (0760/-rwxrw----)  Uid: ( 1000/      gz)   Gid: ( 1000/      gz)
Access: 2024-09-01 19:47:58.288596389 -0700
Modify: 2024-09-01 19:46:56.528841314 -0700
Change: 2024-09-01 19:47:58.279596279 -0700
 Birth: 2024-09-01 19:46:56.268838136 -0700

feldera/benchmark/feldera-sql on  main [$?] via 🐍 v3.12.3 
❯ stat /home/gz/.feldera/pipelines/pipeline0191b098-dfea-7b50-8dea-c51a8daf1e57/program_0191b098-dfea-7b50-8dea-c51a8daf1e57_v3
stat: cannot statx '/home/gz/.feldera/pipelines/pipeline0191b098-dfea-7b50-8dea-c51a8daf1e57/program_0191b098-dfea-7b50-8dea-c51a8daf1e57_v3': No such file or directory
```

**Comment by snkas** [comment]
A pipeline start for the local-runner corresponds to creating a directory where it will run, fetching the binary from the compiler server and copying it there, and then running the binary. Shutdown is [cleaning up that directory](https://github.com/feldera/feldera/blob/main/crates/pipeline-manager/src/local_runner.rs#L181). I think cleanup is a necessary part of the cycle?

**Comment by gz** [comment]
Maybe it could be removed only the next time the pipeline is started (and the binary has changed)? But I leave it up to you, feel free to close as wontfix.
