### ISSUE TITLE
Refactor Python SQL tests

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2437]
We currently generate and compile a separate program with 1table+1view for each test. This is not sustainable, due to compilation delays. We need to refactor the framework to combine multiple tests into a single SQL program. Each test can have its own table + view within this program, however they can also share either the same input table or even the view as well. For example, multiple aggregate tests can operate on the same input table and produce results as columns in a common output view.  

Step 1 is to refactor existing integer aggregation tests.

Additionally, we should compile these programs using the dev compilation profile to:
1. speed up compilation
2. catch overflow bugs more reliably (overflows will panic in dev mode)

**Comment by gz** [comment]
In many cases you should also be able to just run the same query as ad-hoc sql after feeding the data and verify that the result is the same (treat it as a set, display a diff on failure). This will simplify the testing.

**Comment by mihaibudiu** [comment]
she has already validated the results using postgres.
the trouble is with the ones that give different results due to rounding

**Comment by mihaibudiu** [comment]
Also, the python SDK does not provide tools to issue ad-hoc queries

**Comment by ryzhyk** [comment]
> Also, the python SDK does not provide tools to issue ad-hoc queries

Good point. @gz , shall we add an issue for that? It's probably a good idea to expose ad hoc queries from Python?

**Comment by gz** [comment]
> the trouble is with the ones that give different results due to rounding

this is a solved problem in numerics... eps says hi

>Also, the python SDK does not provide tools to issue ad-hoc queries

we should fix that cc @abhizer

**Comment by lalithsuresh** [comment]
May I suggest implementing these as table-driven tests? If they all have the same shape, we could have a set of text files, one per test case, each with some format that specify the table, the view, the inputs and expected outputs. 

The test framework can then create one big pipeline out of all test cases (tables and views) -- supply input data and check the output data (both from python and say, by comparing against postgres or via our own ad-hoc queries --- potentially even all three).
