### ISSUE TITLE
VARIANT doesn't support byte arrays and user-defined structs

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2479]
- [x] `VARIANT` doesn't currently support the `VARBYTE` type.
- [x] user-defined structs can be represented as `Variant::Map`, but this conversion is not implemented. The way to do this is probably to implement `Serializer`/`Deserializer` for `Variant` and rely on existing `Serialize`/`Deserialize` impls for user-defined structs.

**Comment by mihaibudiu** [comment]
Let's merge the existing code first rather than piling up more commits.

**Comment by mihaibudiu** [comment]
I am not sure what to do for serde for this type for inputs and outputs

**Comment by mihaibudiu** [comment]
I think I have this ready
