### ISSUE TITLE
Python API for ad hoc queries

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2493]
Python API to run ad hoc queries against a pipeline. It should support both response formats supported by the ad hoc query engine:
- Tabular: can be used to print results directly to console
- JSON: can be deserialized into a dataframe or some other format that the python program can manipulate programmatically

**Comment by abhizer** [comment]
Something like this? 

```py
def query(self, tabular=False): 
   pass # todo

pipeline.query(SQL) -> Dict # response format is JSON by default
pipeline.query(SQL, tabular=True) -> String # table as String
pipeline.query(SQL, tabular=False) -> Dict
```

**Comment by gz** [comment]
instead of tabular, I'd suggest we have `format` which can currently be one of 'text', 'json', 'parquet'

the json is streamed as new-line delimited records (ndjson)

'parquet' will send you a response that downloads a file instead so maybe it's not important to support in this context. if format is not specified python should use json and return it as a dict or (maybe better) dataframe.

**Comment by ryzhyk** [comment]
- I think that use cases for tabular vs JSON are sufficiently different that these should be two separate methods.
- Since the backend already supports response, streaming, we should support this in the API as well, so the methods should return a cursor that the user can start consuming while the response body is still streaming.
- I agree, there are several potentially useful formats for response data: JSON, Parquet, dictionary of dictionaries (the outer dictionary contains rows, and each row is a dictionary).
- @abhizer will explore similar existing APIs and write a more detailed RFC.

**Comment by abhizer** [comment]
### Spark 

Spark normally seems to have a dataframe type where you call `.show()` to see the result. 
`df` by itself can be used to further process this data. 

```py
df.show() # prints the table
df.show(1) # prints the first row of the table
df.show(1, vertical=True) # show the first row vertically, useful in cases where there are too many columns
```

https://spark.apache.org/docs/latest/api/python/getting_started/quickstart_df.html#Viewing-Data

***

### PyFlink

In PyFlink Python API, you call `.print()` to see the table.

```py
# prepare source tables 
source = table_env.from_elements([(1, "Hi", "Hello"), (2, "Hello", "Hello")], ["a", "b", "c"])

# Get TableResult
table_result = table_env.execute_sql("select a + 1, b, c from %s" % source)

# Print the table
table_result.print()
```
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/python/table/intro_to_table_api/#print-the-table

***

### Feldera

I feel like the best and simplest way for us to do things is: 

```py
pipeline.show(SQL) # prints the tabular result

pipeline.query(SQL) # returns JSON
pipeline.query(SQL, format=QueryResponseFormat.JSON) # returns a python dict
pipeline.query(SQL, format=QueryResponseFormat.Parquet, path="example.parquet") # saves to example.parquet?
# and so on for other formats
```

To me, it makes sense `show()` is a separate method, whereas for other formats, we can use `query()` itself. 

If we really wanted to align with Spark and Flink, we could make `query()` method lazy and call `pipeline.query(SQL).print()` to show the response, but this feels rather overkill and unnecessary. 




What do you think? @gz , @ryzhyk
