### ISSUE TITLE
Rounding error in Python tests.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2494]
I disabled dtype-based Python tests due to rounding errors.  Need to figure out where the decimal<->float conversion creeps into the chain of (de)serializations.

**Comment by mihaibudiu** [comment]
The float conversion was in Python, where you write 0.1. That's a float.

**Comment by mihaibudiu** [comment]
At least one of them.

**Comment by ryzhyk** [comment]
I tried with strings, same outcome
