### ISSUE TITLE
Implement UI for pipeline logs

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#2503]
As a tab in the bottom panel of WebConsole

**Comment by ryzhyk** [comment]
@Karakatiza666 , @snkas , what functionality do we need here? 
- We probably need to handle terminal color codes (or at least have a way not to show them to make the log readable)
- Log search

Are we doing this as a simple text window or is there a specialized library we will use (I imagine such a library might support stuff like log filtering and regular expression search, as well as be optimized for displaying large logs efficiently)

**Comment by snkas** [comment]
The simple text window at least for now, and then iterate and add functionality as we go in my opinion

**Comment by snkas** [comment]
So far no problems with terminal color codes interestingly
