### ISSUE TITLE
[datagen] Invalid timestamp string is quietly accepted, but no data is generated

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2524]
I forgot the `Z` in the end of the timestamp string.  The connector didn't complain, but no data was generated:

```sql
CREATE TABLE test (
    id BIGINT NOT NULL PRIMARY KEY,
    ts TIMESTAMP NOT NULL
) WITH (
  'materialized' = 'true',
  'connectors' = '[{
    "transport": {
      "name": "datagen",
      "config": {
        "plan": [{
            "limit": 10,
            "fields": {
              "id": { "range": [0, 10000000000] },
              "ts": {"range": ["2024-01-01T00:00:00", "2030-01-01T00:00:00"], "scale": 1000 }
            }
        }]
      }
    }
  }]'
);
```

**Comment by gz** [comment]
getting this as output: 

![image](https://github.com/user-attachments/assets/e389e619-870c-4b5e-8a63-78a678e1a00a)
![image](https://github.com/user-attachments/assets/c623911a-a8c0-47f7-afbb-3efb4abafd83)

I think with https://github.com/feldera/feldera/pull/2500 the console line will show up in the UI as well which will make things easier to find so I think it's fine for now
