### ISSUE TITLE
Pipeline manager integration tests delete all pipelines

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2556]
The pipeline manager integration test deletes all existing pipelines, which makes it dangerous to run against an existing Feldera delployment. Can we change it to only overwrite the pipelines that name-clash with the pipelines it creates, and maybe use pipeline names that minimize the chances of such a clash, e.g., manager-test-XXX

**Comment by snkas** [comment]
I could split off/distinguish the tests that are undesirable for running/unable-to-test against an instance (e.g., list of pipelines, API key management).

This is to some extent inherent to being tests though? Ideally, the integration tests spin up their own pipeline manager instance and run against it. The ability to provide an environment variable that runs against is more for convenience to enable quick devcycle for tests. The environment variable `TEST_DBSP_URL` should in general not be configured to a deployment, unless it is a test instance.

**Comment by ryzhyk** [comment]
Deployment might be too big of a word here. I am talking about my local instance, where I often have many useful programs I am testing. I agree, I shouldn't probably run tests against that.

**Comment by snkas** [comment]
Switching between different working directories could be made easier, maybe the CLI (or just a very limited script) could be useful there
