### ISSUE TITLE
[WebConsole] Reduce whitespace around the logo and the New Pipeline button.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2567]
There's way too much whitespace around the Feldera logo and the Create New Pipeline button.  I would move the logo to the top left corner and reduce the whitespace around.

**Comment by gz** [comment]
this is the guideline on how much whitespace should be there
![image](https://github.com/user-attachments/assets/a7c69c6a-67a7-4c04-8935-4e3b573fb302)

I also have a scrollbar for pipelines now:
![image](https://github.com/user-attachments/assets/5e2c3378-387e-4123-95be-a511e6c1e8ac)
