### ISSUE TITLE
[SQL] Run SLT tests continuously

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2578]
Since SLT tests take so long, I propose running then in rotation, so that each day of the week some tests are run.
There are about 628 test files, so we could do about 2/day to rotate all tests in a month.

**Comment by lalithsuresh** [comment]
How long does one of these files take to run?

**Comment by mihaibudiu** [comment]
at about 10 tests/second I think about 2 hours

**Comment by lalithsuresh** [comment]
We could run several of these in parallel as a nightly job.

**Comment by mihaibudiu** [comment]
Correction, we need 20 files per day, so 200K tests/daily, which would take about 20 hours.

**Comment by mihaibudiu** [comment]
@lalithsuresh any news about this?

**Comment by lalithsuresh** [comment]
It's ready when you are to run on k8s. I need you guys to prepare a container that runs SLT and receives an argument which is an index.

```
➜ cat job-spec.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 'sample-job'
spec:
  completions: 20
  parallelism: 20
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - 'bash'
        - '-c'
        - 'echo "My partition: ${JOB_COMPLETION_INDEX}"'
        image: 'docker.io/library/bash'
        name: 'sample-load'
➜  k apply -f job-spec.yaml
job.batch/sample-job configured

....
➜  k logs -l job-name=sample-job
My partition: 12
My partition: 3
My partition: 11
My partition: 15
My partition: 17
My partition: 19
My partition: 9
My partition: 2
My partition: 4
My partition: 5
My partition: 0
My partition: 1
My partition: 10
My partition: 13
My partition: 18
My partition: 14
My partition: 16
My partition: 6
My partition: 7
My partition: 8
```

**Comment by mihaibudiu** [comment]
No idea who "you guys" is. I don't know how to prepare a container.
And how do you get the errors out of it?

**Comment by mihaibudiu** [comment]
the container will need two numbers: it's identity, and the total number of containers.

**Comment by lalithsuresh** [comment]
@gz want to help Mihai prep a container for SLT?

**Comment by mihaibudiu** [comment]
If the java tests run in a container using earthly, then we probably already have one.

**Comment by lalithsuresh** [comment]
Yeah I think you're pretty close tbh. I'd scope it down to only have the minimal footprint to run SLT and not bring everything else.

**Comment by snkas** [comment]
Build container = write a Dockerfile that generates the image with appropriate entry point.
