### ISSUE TITLE
CTRL-LEFT, CTRL-RIGHT no longer work in the SQL editor

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2579]
CTRL-LEFT, CTRL-RIGHT no longer work in the WebConsole (they are supposed to jump over an entire word). Not sure if this affects any other shortcuts.

Edit: If I am not mistaken, the editor used to highlight matching brackets, that functionality is gone too
Edit: auto complete suggestions are gone too
Edit: error message no longer pops up when I hover over the underlined red code.
Edit: commenting shortcut CTRL - / doesn't works

**Comment by gz** [comment]
fwiw this works before 

* 7cf4576f8 - Reduce production bundle size, add loading indicators (11 hours ago)

**Comment by Karakatiza666** [comment]
I cut as much features as possible to minimize bundle size as I was not sure how useful some of those are;
Will re-enable listed features

**Comment by ryzhyk** [comment]
Let's bring everything back and only disable those features we know we won't need.
