### ISSUE TITLE
NOW() isn't always compiled into `window`.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2584]
This correctly compiles `now()` into the `window()` DBSP operator; however if I uncomment the `x = 5` line, then `now()` is compiled into a join, which is correct, but inefficient (in terms of both memory and performance, since in this case the join is evaluated on a single worker):

```sql
create table t (
    x int,
    ts timestamp
);

create view v as
select
    *
from t
where
    -- x = 5 and
    ts > now();
```

**Comment by mihaibudiu** [comment]
as a temporary workaround this can be written using two separate filters
