### ISSUE TITLE
[fda] Should `start` wait for successful deployment?

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2598]
Currently `start` and `restart` send the `start` command to the pipeline, but don't wait for the pipeline status to become `Running`. I think they should.  This is especially important when using `fda` in automation, where one otherwise needs to poll with a timeout to make sure initialization actually succeeded.

**Comment by blp** [comment]
For OVS, in a similar situation, we defaulted to making operations wait for completion but added a `--no-wait` option that did not.

**Comment by ryzhyk** [comment]
Interestingly, `shutdown` and `pause` already do `wait_for_status`, so I suspect this is just an omission.

**Comment by lalithsuresh** [comment]
Good idea to do this for fda-start. Simplifies automation/scripts.
