### ISSUE TITLE
[pipeline-manager] Log endpoint stream doesn't end if pipeline crashes

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2607]
First, this works as expected:

Step 0: `fda start test`
Step 1: `fda log test --watch`
Step 2: `fda stop test`

yields:
```
2024-09-29 01:21:24 INFO [pipeline-019229e6-8e28-7ef1-880e-cfab04c94d6c] Started HTTP server on port 44945
2024-09-29 01:21:24 INFO [pipeline-019229e6-8e28-7ef1-880e-cfab04c94d6c] Pipeline initialization complete
LOG STREAM END: pipeline is being shutdown
```
(stream is terminated)

However, this doesn't work as expected:

Step 0: `fda start test`
Step 1: `fda log test --watch`
Step 2: `kill pipeline_pid` or `kill -9 pipeline_pid`

yields:
```
2024-09-29 01:21:24 INFO [pipeline-019229e6-8e28-7ef1-880e-cfab04c94d6c] Started HTTP server on port 44945
2024-09-29 01:21:24 INFO [pipeline-019229e6-8e28-7ef1-880e-cfab04c94d6c] Pipeline initialization complete
```
(stream/connection stays open -- we don't learn anything about lost pipeline in log)

We should ideally also terminate the log stream, and send a message that we lost the pipeline pod/process in this case.

**Comment by snkas** [comment]
Yes, this does get picked up with stdout/stderr becoming not available but currently it just continues until the process is explicitly terminated. I think I will make it the behavior that if either is no longer available, the log will end as it is unexpected behavior. I will add documentation regarding this, and especially when the processes upon failure get auto-restarted this needs to be documented.

**Comment by gz** [comment]
>especially when the processes upon failure get auto-restarted this needs to be documented.

I think it's fine once we have restart functionality that the log stream does not end. But in case the pipeline is lost and the manager doesn't decide to restart it it seems a natural way to convey it back is to end the stream.
