### ISSUE TITLE
fda: Handle incorrect arguments without panics

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2612]
**Describe the bug**

Incorrect arguments shouldn't panic fda and should yield a friendlier error message.
```
➜  ~ fda query foo
thread 'main' panicked at /Users/lalith/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fda-0.26.0/src/main.rs:657:21:
stdin and sql are mutually exclusive options
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

See above.

**Expected behavior**

Let's have an error message like:

```
`query` command expects a SQL query or a pipe from stdin. For example, `fda query my-pipeline 'select * from foo'` or `echo "select * from foo" | fda query my-pipeline `
```

**Screenshots**

**Context (please complete the following information):**
 - Feldera Version: 
 - Environment: 
 - Browser: 
 - Pipeline Configuration/SQL code:

**Additional context**

**Comment by gz** [comment]
Hm looks like a bug in how clap is configured for this. I'll have a look
