### ISSUE TITLE
[WebConsole] program text obscured by navigation text

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2621]
There should be a way to turn off the navigation pane shown on the right, or it should not overlap the program text.

![image](https://github.com/user-attachments/assets/153437c3-2695-4bc0-9242-8e89b4ac5dc0)

**Comment by ryzhyk** [comment]
FWIW, this editor behaves in the same way in vscode.

**Comment by mihaibudiu** [comment]
I think in VScode you can turn that off if you really want to see the text.
If the program is too long it fills the whole window.
