### ISSUE TITLE
[WebConsole] Rust compilation status not shown after compilation

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2631]
After SQL compilation, there is a green checkmark with "SQL" next to it.
It would be preferred if there would also be a green checkmark with "Rust compilation" next to it once that stage of compilation is completed.
The checkmark would also be nice if would be a green circle with a checkmark in it rather than just loose, such that it matches the (x) that happens when it fails.

**Comment by Karakatiza666** [comment]
@lalithsuresh The Rust compilation success status is intentionally hidden as to not to draw attention to it. Let me know If you'd rather have it show a green checkmark alongside the SQL

**Comment by lalithsuresh** [comment]
Yeah I prefer the current behavior w.r.t Rust Compilation.

**Comment by ryzhyk** [comment]
I think the current behavior makes sense too.

**Comment by snkas** [comment]
I see -- my thinking is/was that the user would want to see feedback in the same location when compilation is completed upon opening the pipeline tab again. It's a preference, will close the issue in that case based on feedback :+1:
