### ISSUE TITLE
Rust errors should be wrapped in an actionable error message for users

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2643]
When Rust compilation fails, a stack trace is pretty bad UX. Let's wrap this in an actionable error message for the user.

E.g.: "Rust error: the specified SQL generated invalid Rust, which should not happen. Please file a bug report with example SQL that triggered it: https://github.com/feldera/feldera/issues".

**Comment by mihaibudiu** [comment]
I think we should keep the stack traces too, they can help us debug issues.

**Comment by ryzhyk** [comment]
Rust compilation errors don't produce a stack trace, but we should keep the original Rust compiler message.
Note also that when using UDFs, a Rust compiler error can be caused by an incorrect UDF implementation. We shouldn't report those as Feldera bugs.

**Comment by lalithsuresh** [comment]
> I think we should keep the stack traces too, they can help us debug issues.

Yup, I meant the friendly error message should precede the stack trace. Maybe we can add a blue screen. :)
