### ISSUE TITLE
[py] Use ad hoc queries in Python SQL tests

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2650]
The SQL tests in `python/tests` currently use the streaming API to read test outputs. In addition to being awkward, it introduces non-determinism, since the correctness check applies to the final state of the view, but the pipeline can output several deltas, and the streaming API doesn't consolidate these outputs.

With the new ad hoc query API, we can instead run `select * from <output_view>` in the end to get a full snapshot and compare it against the expected snapshot.

**Comment by abhizer** [comment]
Ad-hoc queries with output format JSON doesn't support Decimal type, which kinda blocks this.

**Comment by abhizer** [comment]
https://github.com/feldera/feldera/issues/2667
