### ISSUE TITLE
Add an int32 type alias for integer

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2651]
we already have int64, it would be nice to use `int32` for 4-byte integers

![image](https://github.com/user-attachments/assets/00b5d1c4-be74-4623-a261-dd777478cb5c)

**Comment by mihaibudiu** [comment]
I don't think we can do that, since INT8 will become very confusing.
Things are already pretty bad.
I'd rather remove INT64.

**Comment by mihaibudiu** [comment]
we can add a compiler flag to enable one of the two... but no one likes compiler flags

**Comment by gz** [comment]
I think it's more user friendly to have aliases which indicate bits like int8, int32, int64 ... I personally can't remember what is INTEGER or BIGINT, but I do know how many bits I want

**Comment by mihaibudiu** [comment]
we don't make this call, the people who designed SQL dialects do

**Comment by gz** [comment]
what dialect do we follow?

**Comment by gz** [comment]
I think this is out of scope of the issue.. the issue is about adding `int32` which I don't think has a conflict with `int8`

**Comment by mihaibudiu** [comment]
technically there is a compiler flag for the dialect, but I am not sure what exactly it does.
the aliases are currently valid for all dialects
