### ISSUE TITLE
[adhoc] json format doesn't support DECIMAL type

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#2667]
SQL: 

```sql
CREATE TABLE x(C DECIMAL(20, 2));

CREATE MATERIALIZED VIEW v AS SELECT * FROM x;
```

Insert data with fda:

```sh
fda query decimal 'insert into x values(11.11);'
```
Here, `decimal` is the name of the above pipeline.

Trying to get data in JSON format:

```sh
curl  'http://localhost:8080/v0/pipelines/decimal/query?sql=SELECT%20*%20FROM%20v;&format=json'
{"error":"Arrow error: Invalid argument error: JSON Writer does not support data type: Decimal128(20, 2)"}
```

-----

PS by @ryzhyk : There are several python aggregate tests disabled due to this issue. Don't forget to enable those tests as part of the fix.

**Comment by ryzhyk** [comment]
@gz , I reassigned this to you. I initially thought that the issue was in our (de)serialization framework, but it looks like it is purely an `arrow-json` issue. The error happens in the `arrow-json` crate, which genuinely doesn't seem to know how to serialize decimals. Can you take a look?

**Comment by gz** [comment]
ok will have a look on monday

**Comment by Karakatiza666** [comment]
I am adding a high-priority label because this got really intrusive since ad-hocs got support from WebConsole

**Comment by gz** [comment]
This has been fixed in https://github.com/apache/arrow-rs/releases/tag/53.2.0 we need to wait for it to be on crates.io then we can upgrade

**Comment by gz** [comment]
waiting for datafusion release, they upgraded main to 53.2

**Comment by gz** [comment]
datafusion has released v43 which includes the fix. but we also need to wait for delta-rs to upgrade it's datafusion dependency before we can upgrade https://github.com/delta-io/delta-rs/pull/2886

**Comment by ryzhyk** [comment]
@abhizer , would you be able to re-enable python tests blocked by this issue and check that they work now? Thanks1
