### ISSUE TITLE
[WebConsole] Support demos with UDFs.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2679]
Add support for demos that include UDFs and implement at least one such demo. Possible design:

If the demo directory includes a `<name>.rs` file and, optionally, `<name>.toml` file in addition to `<name>.sql`, these files will be supplied to the manager as `udf_rust` and `udf_toml` properties.

**Comment by Karakatiza666** [comment]
Fixed by https://github.com/feldera/feldera/pull/2691
