### ISSUE TITLE
Web Console unresponsive under large volume of logs.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2713]
* Create a large CSV file with millions of records (the exact schema doesn't matter, as it is supposed not to match the table schema)
* Create a SQL table whose schema doesn't match the CSV schema

```sql
CREATE TABLE t (
   -- Columns do not match the CSV file
   x INT,
   y VARCHAR,
   x TIMESTAMP.
   ...
);
```

* Run the pipeline and open the log tab. You should see many parse errors in the log. A few seconds later the Web Console becomes almost completely unresponsive. I can switch to another tab sometimes, but after that none of the UX elements work.

**Comment by mihaibudiu** [comment]
hey, it's just like github!
