### ISSUE TITLE
[SQL] Support PARSE_DATE, PARSE_DATETIME, PARSE_TIME

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2716]

**Comment by mihaibudiu** [comment]
These things are can be much trickier than they look because Calcite already has rules for format strings, and they may not match the format strings that Rust libraries use. We already have a similar issue for the reverse direction: #2275

**Comment by mihaibudiu** [comment]
You will also note that the Calcite documentation does not specify anywhere the format string rules, they have to be reverse engineered from the implementation. These functions are actually in the BigQuery dialect, so the right documentation to use the BigQuery documentation.

**Comment by ryzhyk** [comment]
Can we just use the strftime format?

**Comment by mihaibudiu** [comment]
Only if strftime works in the same way across Java, Rust, and Bigquery.

**Comment by mihaibudiu** [comment]
But that's exactly why we have #2275, the interpretation of the format string is different in different languages.

**Comment by mihaibudiu** [comment]
Another alternative is for us not to load the bigquery function library at all, and then we can use these names.

**Comment by mihaibudiu** [comment]
Then we get to define how these functions work.

**Comment by mihaibudiu** [comment]
That's what I will do, I will just use the Rust definition.
