### ISSUE TITLE
[SQL] implement SPLIT_PART function

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#2721]
as per ~~https://w3resource.com/PostgreSQL/split_part-function.php~~ https://www.postgresql.org/docs/current/functions-string.html, Table 9.10, **split_part** function

**Comment by prashant3286** [comment]
Need more information about which part should the `SPLIT_PART` function implement?
cc: @Karakatiza666

**Comment by Karakatiza666** [comment]
Hi @prashant3286! The linked page really lacks detail.
Here is a better definition based on PostgreSQL implementation which should fit nicely:
https://www.postgresql.org/docs/current/functions-string.html

```
split_part ( string text, delimiter text, n integer ) → text

Splits string at occurrences of delimiter and returns the n'th field (counting from one), or when n is negative, returns the |n|'th-from-last field.

split_part('abc~@~def~@~ghi', '~@~', 2) → def

split_part('abc,def,ghi,jkl', ',', -2) → ghi
```

Also, this issue contains helpful info on adding a new SQL function to the compiler:
[Recipe for implementing new SQL functions](https://github.com/feldera/feldera/issues/951)

**Comment by mihaibudiu** [comment]
The recipe won't be as useful, because it's for functions which are already supported by Calcite.
I should update it to describe how to add new functions, there is a way to do that.

**Comment by mihaibudiu** [comment]
That being said, this function can be implemented in pure SQL using our syntax for defining functions:
```sql
CREATE FUNCTION SPLIT_PART(text VARCHAR, delimiter VARCHAR, n INTEGER) RETURNS VARCHAR AS
SPLIT(text, delimiter)[n];
```

This assumes the result NULL is fine when the index is out of range.

**Comment by zhuqi-lucas** [comment]
Hi, i create a PR to support this in calcite first, after that merged, i will create a PR for feldera side change:
https://github.com/apache/calcite/pull/4027

**Comment by Karakatiza666** [comment]
@zhuqi-lucas since the Calcite PR is successfully merged we'd be happy to see your follow-up PR to Feldera :smiley:

**Comment by zhuqi-lucas** [comment]
Sure @Karakatiza666 , @mihaibudiu now the default branch for calcite is:

```
    CALCITE_REPO="https://github.com/mihaibudiu/calcite.git"
    CALCITE_BRANCH="variant"
    CALCITE_NEXT_COMMIT="9b88b5b8807eeee4b728def3983e4c2a505319a3"
```

It does not include the latest PR for calicte which including the merged PR, we need to update.

**Comment by mihaibudiu** [comment]
Indeed. I will try to rebase my branch tomorrow on Calcite main and see if anything breaks.

**Comment by zhuqi-lucas** [comment]
Sure, i will submit a PR after the rebase.

**Comment by mihaibudiu** [comment]
When https://github.com/feldera/feldera/pull/2967 is merged this should work.
Sorry for the delay, it actually takes quite some time to validate a new build of Calcite with our compiler.

**Comment by zhuqi-lucas** [comment]
Submitted the PR for review, thanks!
