### ISSUE TITLE
Actionable error messages in SQL compiler instead of "not yet implemented" errors

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2722]
We have certain functions that we don't support in specific contexts, like using row_number() in contexts with windowed aggregates. The rank/lead/lag functions come up with such errors too.

We currently return an opaque "Not yet implemented" error for these. We've had consistent user feedback that this is confusing, when they see these functions in our documentation.

I suggest we give the user a more actionable error instead. Something like: "`function` not yet implemented in this specific context. Please file an issue here: https://github.com/feldera/feldera/issues".

Being more specific about context would also be great, but I understand that's really difficult.

**Comment by mihaibudiu** [comment]
Can we close this issue?
