### ISSUE TITLE
Support for unnest in combination with left-joins

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2736]
We currently only support cross-join unnest, would be good to support unnest with left joins, e.g.,

```
create view latest_cells_with_mentions as
select
    s.id,
    s.raw_value,
    s.background,
    m.mentioned_id
from
    latest_cells s
left join unnest(s.mentioned_cell_ids) as m(mentioned_id) on true;
```

**Comment by mihaibudiu** [comment]
why does this need to be a left join if the predicate is "true"?
what rows are being left out by a regular join?

**Comment by gz** [comment]
the ones where mentioned_cell_ids is empty

**Comment by mihaibudiu** [comment]
Can you try this on another database? I don't think this is what a left join would do.
