### ISSUE TITLE
Code from a deleted pipeline shows up in a different pipeline

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2740]
* Delete pipeline 1
* Switch to pipeline 2
* Switch to pipeline 3 - pipeline 1 code shows up

https://github.com/user-attachments/assets/e696afe4-5c50-42c0-8393-8d46bcf32351

**Comment by Karakatiza666** [comment]
A temporary fix is in the merge queue, the proper fix is in progress
