### ISSUE TITLE
[SQL+DBSP] MAX and MIN for append-only only streams can be more efficient

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2751]
MAX and MIN aggregates generally require maintaining the integral of the collection (so they have `O(N)` space complexity, but `O(n)` time complexity, where `N` is the size of the collection, and `n` is the size of a delta). However, for append-only collections they can be implemented in constant space, by only storing the current min or max value. We need a DBSP operator for this (although it looks a lot like `waterline` and can probably just be implemented in terms of it) and SQL compiler support. The compiler already has the ability to declare input tables as `append_only` and propagate this info through the pipeline using static analysis.

**Comment by mihaibudiu** [comment]
The waterline only works for MIN and MAX without GROUP BY.

**Comment by ryzhyk** [comment]
Right, but that matches our notion of waterline, which is global for the entire table.

**Comment by mihaibudiu** [comment]
The question is whether we want to do something special for MAX for group-by aggregate for append-only tables as well.

**Comment by ryzhyk** [comment]
oh yeah, we can definitely build that operator too.

**Comment by ryzhyk** [comment]
DBSP support added in #2777
