### ISSUE TITLE
Checkpointing shouldn't be blocked by long-running merges

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2774]
The `Spine::commit` method currently calls `AsyncMerger::pause`, which blocks until any ongoing merges complete.  This can potentially take a long time, but as far as I can tell, isn't strictly necessary, since the commit only needs to include current batches that form the spine.

**Comment by mihaibudiu** [comment]
Did we merge a version of ft recently?
Then I suspect this is on the newer version of that branch.

**Comment by blp** [comment]
> Did we merge a version of ft recently? Then I suspect this is on the newer version of that branch.

Yes, I just pushed it. I am reporting progress.

**Comment by ryzhyk** [comment]
@blp , ok to close this?

**Comment by blp** [comment]
Fixed!
