### ISSUE TITLE
[RFC] `emit_final` attribute.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2775]
This RFC is based on the discussion in #2752.

In some applications users want to only observe final outputs of a query, i.e., outputs that are guaranteed to not get retracted as new inputs are received.  This is because the application (1) may not be able to act correctly on intermediate outputs, (2) may not be able to determine when the output becomes final,  or (3) may not be able to process retractions of intermediate results.

We would prefer to express this in pure SQL without introducing new extensions, but this cannot always be done (this behavior can in general only be expressed in terms of the _waterline_ of the query, which in turn cannot be expressed in SQL for non-append-only collections) and when it can it's fragile and error-prone (see discussion in #2752). We therefore decided to introduce new syntax for this.  We will implement it as an experimental feature and will collect user feedback before stabilizing it.

Proposed syntax:

```sql
CREATE VIEW v WITH ('emit_final' = 'true')
AS
SELECT ...
FROM ...
```

Unlike other attributes, `emit_final` changes the behavior of the view, and cannot be considered a no-op. The semantics of this query is:

```rust
v.index_by_ts().window(-infinity, waterline)
```

where

* `v` is the output of the view without the `emit_final` attribute
* `index_by_ts()` - indexes `v` by the timestamp column (see below)
* `waterline` - the current waterline of `v`, i.e., a timestamp value such that no updates with a timestamp `< waterline` can ever be observed to this view.
* the `window(-infinity, waterline)` operator delays outputs until they fall below the waterline.

This semantics is defined with respect to a timestamp column. This can be any column in the view that has bounded lateness and that can be used to compute the waterline. The compiler infers lateness from `LATENESS` annotations on tables and views using static analysis. If none of the columns have lateness, the compiler rejects the program. If multiple columns have LATENESS, the compiler must pick one of them.  Rather than have it make an arbitrary choice, we may require the user to specify the timestamp column, e.g.,:

```
WITH('emit_final_with_timestamp' = '<column_name>'`)
```

or

```
WITH(
    'emit_final' ='true'`,
    'timestamp' = '<column_name>'
)
```

where the `timestamp` attribute only needs to be specified if there are multiple candidates.

**Comment by mihaibudiu** [comment]
Features needed:
- [x] Front-end support (language extension)
- [x] Back-end support (compiler and runtime implementation)
- [x] Documentation
- [ ] Garbage collection

**Comment by mihaibudiu** [comment]
Reopening until GC is fixed
