### ISSUE TITLE
Ad-hoc results --format=json: JSON Writer does not support data type: Decimal128(28, 0)

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#2778]
1. Create pipeline with
```sql
create table PRICE (
    price decimal
) with ('materialized' = 'true');
```
2. Enter a row via ad-hoc query with
```sql
INSERT INTO PRICE (price) VALUES (1000)
```
3. Try to
```sql
SELECT * FROM PRICE;
```

![image](https://github.com/user-attachments/assets/24e10fa9-7f72-4bd8-830b-9e209be7d535)

Consequently, all the other data types need to be checked for compatibility with ad-hoc result serialization.
The serialization works in change stream.
For API compatibility, SQL values in results from ad-hoc query and change stream updates need to be serialized in the same JSON shape.

**Comment by ryzhyk** [comment]
Closing as duplicate of #2667
