### ISSUE TITLE
[WEBUI] udf.rs tab should change background on click

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2787]
I started a new pipeline manager, deleted all programs, and then started a new one.
Pasted the SQL, but the udf.rs tab is read-only. 
I cannot add udfs.

https://github.com/user-attachments/assets/18350dd8-a7a1-40d1-891a-8750399e5b8c

**Comment by mihaibudiu** [comment]
Same problem persists on try.feldera.com
So looks like our sandbox cannot be used with udfs

**Comment by mihaibudiu** [comment]
Sorry for the soundtrack, you can ignore

**Comment by mihaibudiu** [comment]
this is with Firefox

**Comment by mihaibudiu** [comment]
In fact, looks like the program is editable, but clicking on the window does not make that clear.
I was trying to select and replace the existing program displayed.
I think that on click the default program should disappear or just it should always be editable.

**Comment by ryzhyk** [comment]
Hiding the example text on click is probably the right behavior here.
