### ISSUE TITLE
[pipeline-manager] ASCII art is too large

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2809]
The ASCII art that prints "Feldera" is too large and interferes with seeing earlier log messages.

**Comment by snkas** [comment]
Using just figlet _standard_ font with FELDERA in caps looks alright, not sure how to generate a light version of it though.
```
$ figlet FELDERA
 _____ _____ _     ____  _____ ____      _    
|  ___| ____| |   |  _ \| ____|  _ \    / \   
| |_  |  _| | |   | | | |  _| | |_) |  / _ \  
|  _| | |___| |___| |_| | |___|  _ <  / ___ \ 
|_|   |_____|_____|____/|_____|_| \_\/_/   \_\
```

**Comment by gz** [comment]
this looks ugly 😀 what messages acan get lost (cant you scroll up to see them?)

**Comment by lalithsuresh** [comment]
I prefer the current version with the current logo as well.

**Comment by snkas** [comment]
Alright then
