### ISSUE TITLE
[sql] `window` interval for `emit_final` should be open.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2822]
`emit_open` compiles to the `window` operator with `[-infinity, waterline]` bounds. I believe that the interval should be open on the right: `[-infinity, waterline)`. The reason is that monotonicity only guarantees that outputs of the view don't change for timestamps < waterline, but can change for timestamps = waterline.  Consider the following SQL:

```sql
CREATE TABLE purchase (
   ts TIMESTAMP NOT NULL LATENESS INTERVAL 1 HOURS,
   amount BIGINT
) WITH (
    'materialized' = 'true'
);

CREATE MATERIALIZED VIEW daily_total
WITH (
    'emit_final' = 'd'
)
AS
SELECT
    TIMESTAMP_TRUNC(ts, DAY) as d,
    SUM(amount) AS total
FROM 
    purchase
GROUP BY 
    TIMESTAMP_TRUNC(ts, DAY);
```

```sql
-- Waterline is now 2020-01-01 
INSERT INTO purchase VALUES('2020-01-01 01:00:00', 20);

-- Waterline still at 2020-01-01 due to lateness
INSERT INTO purchase VALUES('2020-01-02 00:10:00', 15);

-- Waterline moves to 2020-01-02.
INSERT INTO purchase VALUES('2020-01-02 02:00:00', 65);
```

We expect output for 2020-01-01 to be produced after the last insert, but we in fact see the aggregate getting updated after each insert above due to the closed window interval.

**Comment by ryzhyk** [comment]
Would be nice to double check that window bounds are correctly derived for NOW() temporal filters, with non-strict inequalities (<=) getting compiled to closed intervals, and `<` getting compiled to closed intervals.

**Comment by mihaibudiu** [comment]
A code review says they are:
```
            boolean lowerInclusive = bounds.lower == null || bounds.lower.inclusive;
            boolean upperInclusive = bounds.upper == null || bounds.upper.inclusive;
            DBSPOperator window = new DBSPWindowOperator(
                    operator.getNode(), lowerInclusive, upperInclusive, diffIndex, windowBounds);
```
