### ISSUE TITLE
Arrow error: Invalid argument error: JSON Writer does not support data type: Decimal128(28, 0)

### ISSUE THREAD

**Issue by ytooyama** [feldera/feldera#2829]
**Describe the bug**

When you copy and paste an SQL query with Ad-hoc-query, an error appears that JSON Writer does not support data type: Decimal128(28, 0).

**To Reproduce**

1. Set up while looking at the document.
  - https://docs.feldera.com/tutorials/basics/part1
  - https://docs.feldera.com/tutorials/basics/part2
2. Use the terminal to run it.

```shell
curl -X 'POST' http://localhost:8080/v0/pipelines/supply_chain/ingress/PART?format=json -d '
{"insert": {"id": 1, "name": "Flux Capacitor"}}
{"insert": {"id": 2, "name": "Warp Core"}}
{"insert": {"id": 3, "name": "Kyber Crystal"}}'

curl -X 'POST' http://localhost:8080/v0/pipelines/supply_chain/ingress/VENDOR?format=json -d '
{"insert": {"id": 1, "name": "Gravitech Dynamics", "address": "222 Graviton Lane"}}
{"insert": {"id": 2, "name": "HyperDrive Innovations", "address": "456 Warp Way"}}
{"insert": {"id": 3, "name": "DarkMatter Devices", "address": "333 Singularity Street"}}'

curl -X 'POST' http://localhost:8080/v0/pipelines/supply_chain/ingress/PRICE?format=json -d '
{"insert": {"part": 1, "vendor": 2, "price": 10000}}
{"insert": {"part": 2, "vendor": 1, "price": 15000}}
{"insert": {"part": 3, "vendor": 3, "price": 9000}}'
```

3. Copy and paste SQL queries in the Ad-hoc-query of the web interface and run them.

```sql
SELECT * FROM PART	#OK
3 rows
id	name
2	Warp Core
3	Kyber Crystal
1	Flux Capacitor

SELECT * FROM VENDOR	#OK     
3 rows
id	name	address
2	HyperDrive Innovations	456 Warp Way
3	DarkMatter Devices	333 Singularity Street
1	Gravitech Dynamics	222 Graviton Lane

SELECT * FROM PRICE	#ERR
Arrow error: Invalid argument error: JSON Writer does not support data type: Decimal128(28, 0)
```

5. See error 

```
Arrow error: Invalid argument error: JSON Writer does not support data type: Decimal128(28, 0)
```

**Expected behavior**

The result of "SELECT * FROM PRICE" is displayed.

**Screenshots**

<img width="980" alt="err" src="https://github.com/user-attachments/assets/911629ac-265e-435d-bd6e-3b2f2c10658c">

**Context (please complete the following information):**
 - Feldera Version: ghcr.io/feldera/pipeline-manager:latest(image id:4862c140d8f0)
 - Environment: Docker
 - Browser: Firefox, Safari
 - Pipeline Configuration/SQL code:
   - https://docs.feldera.com/tutorials/basics/part1#step-1-create-a-pipeline

**Additional context**

**Comment by mihaibudiu** [comment]
This looks like a duplicate of #2667

**Comment by ryzhyk** [comment]
Thanks for reporting!  This is a duplicate of https://github.com/feldera/feldera/issues/2667. Good news is, there is already a fix in the upstream repository.

**Comment by ytooyama** [comment]
Thank you for your reply. If there is an update, I will try this again!

**Comment by gz** [comment]
FYI as a workaround you can just declare the price type in the `PRICE` table as `double` or `integer`

```
create table PRICE (
    part bigint not null,
    vendor bigint not null,
    price integer
) with ('materialized' = 'true');
```

**Comment by ytooyama** [comment]
Thank you for your reply.
