### ISSUE TITLE
The column name has not been evaluated

### ISSUE THREAD

**Issue by ytooyama** [feldera/feldera#2836]
**Describe the bug**

Incomplete data is registered in the table because the column name is not evaluated and no error is displayed.

**To Reproduce**

1. Contents of program.sql

```sql
CREATE TABLE sales (
 number INTEGER,
 customer   VARCHAR(128),
 sweets VARCHAR(128),
 price INTEGER
) with ('materialized' = 'true');
```

2. Input the Data...but Register data with a column name different from the table (sweets vs sweet).

```
curl -X 'POST' http://localhost:8080/v0/pipelines/testcase2/ingress/sales?format=json -d '
{"insert": {"number": 1, "customer": "Alice", "sweet": "candy" ,"price": 100}}
{"insert": {"number": 2, "customer": "Alice", "sweet": "candy" ,"price": 50}}
{"insert": {"number": 3, "customer": "Alice", "sweet": "cookie" ,"price": 150}}
{"insert": {"number": 4, "customer": "Bob", "sweet": "chocolate" ,"price": 200}}
{"insert": {"number": 5, "customer": "Bob", "sweet": "chocolate" ,"price": 300}}
{"insert": {"number": 6, "customer": "Jane", "sweet": "cookie" ,"price": 150}}
{"insert": {"number": 7, "customer": "Alice", "sweet": "chocolate" ,"price": 180}}
{"insert": {"number": 8, "customer": "Bob", "sweet": "chocolate" ,"price": 180}}
{"insert": {"number": 9, "customer": "Bob", "sweet": "chocolate" ,"price": 180}}
{"insert": {"number": 10, "customer": "Jane", "sweet": "cookie" ,"price": 220}}'
```

An error such as a different column name is not displayed and it will be registered.

3. Try the Adhoc query:

- SELECT * FROM sales;

4. Expected results

```sql
SELECT * FROM sales;
10 rows
number	customer	sweets	price
2	Alice			50
10	Jane			220
1	Alice			100
3	Alice			150
5	Bob			300
8	Bob			180
9	Bob			180
7	Alice			180
4	Bob			200
6	Jane			150
```

5. Actual results:
  - Incomplete data is registered

```sql
SELECT * FROM sales;
10 rows
number	customer	price
2	Alice		50
10	Jane		220
1	Alice		100
3	Alice		150
5	Bob		300
8	Bob		180
9	Bob		180
7	Alice		180
4	Bob		200
6	Jane		150
```

**Expected behavior**

It may be a good idea to display NULL or a blank space, or to display an error.

**Screenshots**

<img width="421" alt="spell_miss" src="https://github.com/user-attachments/assets/9970b9eb-9028-4fba-bf25-2e3224910713">

**Context (please complete the following information):**
 - Feldera Version: ghcr.io/feldera/pipeline-manager:latest (image id: 4862c140d8f0)
 - Environment: Docker
 - Browser: Firefox
 - Pipeline Configuration/SQL code:

**Additional context**
I hope there is an error like the number of columns is different.

**Comment by ryzhyk** [comment]
Thanks for reporting! I agree, this output looks odd. Just to clarify, there are three things going on here:
1. Feldera doesn't complain about the missing "sweets" column, because nullable columns are allowed to not be present in the JSON format.
2. Feldera doesn't complain about the unknown "sweet" column: it liberally accepts any input record as long as all non-nullable columns are present. 

Both of these could be made configurable. 

3. A column doesn't show up in ad hoc query outputs if all (some?) of its values are NULL.  I suspect this comes from datafusion, which we use our ad hoc query engine.  @gz may know more about this behavior and whether it is configurable.

**Comment by gz** [comment]
point 3 can be fixed, it's the same as https://github.com/feldera/feldera/issues/2839

**Comment by Karakatiza666** [comment]
Now that https://github.com/feldera/feldera/pull/2872 is merged, NULL values are correctly rendered in the result of an ad-hoc query

**Comment by ytooyama** [comment]
This problem has been fixed. Thanks!
