### ISSUE TITLE
[pipeline-manager] ASCII art light vs. dark version

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2837]
The ASCII art detector checks if it is a light or dark themed terminal. However, it gets it often wrong (e.g., especially when launched detached or not from terminal), in which in particular the light version is invisible and looks like unusual colored characters on white background.

Proposal: no theme detector for ASCII art, the terminal itself deals that there is contrast between text and background color.

**Comment by snkas** [comment]
What it looks like:
![ascii_art](https://github.com/user-attachments/assets/627ff157-402f-448a-a94a-0213f9b07bd4)

**Comment by gz** [comment]
>especially when launched detached or not from terminal

what is "launched detached" or "not from terminal" can you give me some steps to reproduce?
