### ISSUE TITLE
REST API ergonomics

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#284]
Collecting notes here as I encounter issues while writing integration tests. Will fix them separately:

* [x] (no longer needed) API object consistency: ID fields should be named "id" and not pipeline_id/connector_id/program_id.
* [x] API endpoint consistency: for program resources alone, we currently have `/v0/program`, `/v0/programs`, `/v0/program/{program_id}/code`, `/v0/programs/compile`, and `/v0/programs/{program_id}`. We might be able to simplify this to say, `/v0/programs` and `/v0/programs/{program_id}`. A POST request to `/v0/programs/` can be used to create objects. A POST to `/v0/programs/{program_id}` might be usable for compilation commands (`/v0/programs/{program_id}/compile` might be okay too). The standard approach of listing optional fields to fetch should be used to include the program code or not on a GET `/v0/programs`/`/v0/program/{program_id}`. There are similar cases of endpoint sprawl with `pipelines`.
* [x] NewProgramRequest overwrite_existing can be safely removed.
* [x] Remove cancel_program()
* [ ] Allow programs to be deployed without compilation

**Comment by gz** [comment]
>  API object consistency: ID fields should be named "id" and not pipeline_id/connector_id/program_id.

I have mixed feelings about it. I also found it a bit verbose in the beginning, but I've come to appreciate it more and more as it's always explicit which ID something is referring to in the code.

**Comment by lalithsuresh** [comment]
It's not about it being verbose as it is about consistency in the codebase and API. Other good APIs like AWS, Kubernetes etc also follow this pattern of providing common concepts across objects identical names (in Kubernetes, every object regardless of type has common metadata fields). 

In our codebase, it's "name" for pipeline, projects and connectors, but the ID fields have the type in the prefix, even though in the database schema it's "id". When working without code generated clients and just json, it's also convenient to have this type of consistency. For instance, I can write common code to fetch/delete lists of objects without caring about their type, or look at how many objects are owned by which user etc (which is where this use case came from).

**Comment by lalithsuresh** [comment]
With the JIT on the horizon, I think we don't need to worry about what I originally had in mind about deploying programs without compilation via the API. Closing the issue.
