### ISSUE TITLE
checkpointing needs to be able to serialize trait objects

### ISSUE THREAD

**Issue by blp** [feldera/feldera#2843]
Consider a SQL program like this ([full program with DDL](https://github.com/user-attachments/files/17513080/q23.txt)):

```
CREATE MATERIALIZED VIEW q23 AS SELECT COUNT(*) FROM bid;
```

This will generate a program whose pipeline looks, in part, like this:
![image](https://github.com/user-attachments/assets/f1f673c9-e6b5-4d2a-a031-3ebc9f3f5efd)

The corresponding Rust code ([full code](https://github.com/user-attachments/files/17513152/main.txt)) is:

```rust
        // rel#26:LogicalAggregate.(input=LogicalTableScan#1,group={},EXPR$0=COUNT())
        let stream469 = circuit.add_source(Generator::new(|| if Runtime::worker_index() == 0 {zset!(
            Tup1::new(0i64) => 1,
        )} else {zset!(
        )}));
        // rel#26:LogicalAggregate.(input=LogicalTableScan#1,group={},EXPR$0=COUNT())
        // DBSPDifferentiateOperator 538(469)
        let stream538: Stream<_, WSet<Tup1<i64>>> = stream469.differentiate();
```

The `Z^-1` operator here contains a Z-set, specifically a `FallbackWSet`. We don't implement checkpoint or rkyv serialization for these objects because previously they were only inside spines, which are never themselves serialized. I'm happy enough to implement serialization for them, but at the bottom of the tree of things I need to serialize for that are dynamic trait objects, defined in `crates/dbsp/src/dynamic/declare_trait_object.rs`, and I'm just a bit baffled by what should go there. @ryzhyk, I need help with that.

@mihaibudiu, if it would make sense to instead avoid having a `Z^-1` operator on a Z-set here, then that would also avoid the problem.

Without solving this one way or another, we can't checkpoint such a program.

**Comment by mihaibudiu** [comment]
You will have delay operators in one way or another. Avoiding them is not possible. They are used by the GC code, for example.
There is really no need for there operators to be different from other operators, though.

**Comment by blp** [comment]
> You will have delay operators in one way or another. Avoiding them is not possible. They are used by the GC code, for example. There is really no need for there operators to be different from other operators, though.

The issue is that we can't currently checkpoint a Z-set, unless it is inside a spine. Do the other uses of delay operators use this kind of "naked" Z-set? If they do, then we will have to implement checkpointing for Z-sets.

**Comment by mihaibudiu** [comment]
only @ryzhyk can answer these questions

**Comment by mihaibudiu** [comment]
but the reason you need to checkpoint a spine is because it logically has a delay inside.
The representation of the data may be different, though.

**Comment by blp** [comment]
I implemented checkpointing sort of the same way that storage works. It worked. Thanks @ryzhyk for the suggestion.
