### ISSUE TITLE
[adapters] Inline connector

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2849]
Addition of a very basic connector that supplements the datagen connector, in which it is possible to directly write its content inline. 
```
CREATE TABLE example (
    col1 INT NOT NULL,
    col2 INT NOT NULL
) WITH ('connectors' = '[{
    "name": "example",
    "transport": {
        "name": "inline_input",
        "config": {
            "content": "1,2\n3,4\n5,6"
        }
    },
    "format": {
        "name": "csv"
    }
}]');
```

**Comment by ryzhyk** [comment]
the datagen already lets you do this, but in a "columnar" format (by specifying the list of values in each field). This could be a datagen config option rather than a separate connector.
