### ISSUE TITLE
there is no feedback that SQL isn't editable anymore when pipeline is running

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2862]
instead it just doesn't let you type

![Screenshot from 2024-10-25 16-34-30](https://github.com/user-attachments/assets/067d905c-00de-4d58-87e9-535a83097335)

**Comment by Karakatiza666** [comment]
@gz  I change the editor background color from white to gray, it is not visible enough?

**Comment by Karakatiza666** [comment]
I will try to ensure tooltip with the "no edit" message pops up over cursor
