### ISSUE TITLE
[Python] Revise ingress/egress architecture

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#2874]
There is currently a set of views/tables maintained that are listened to. It is however possible for an HTTP connection to be interrupted for a multitude of network-related issues, which would sever the `listen()` even if the pipeline is continuously running and remains available.

With the advent of adhoc queries, it would probably be better to simplify the ingress/egress architecture to their core functionality of providing change streams rather than as a method to retrieve a snapshot (until they natively support such a functionality by providing modes like `snapshot`, `snapshot-and-follow` and `follow` rather than just only follow).

**Comment by snkas** [comment]
@abhizer @ryzhyk What are your thoughts on this?

**Comment by ryzhyk** [comment]
* We don't support using egress to create a snapshot at the moment. It only allows access to the change stream and doesn't provide a way to consolidate multiple updates.
* It's true that our HTTP-based protocol isn't yet fully reliable and can miss updates in case of a disconnection.
* We already support ad hoc queries in the Python API, including SELECT * to get a snapshot but of course this only works for materialized tables and views

I see a few improvements that are still needed based on this:

* We can make the HTTP transport more reliable by supporting replay for specified position on disconnect
* We should implement snapshot-and-follow for materialized views.

@snkas , do you have some other improvements in mind?

**Comment by snkas** [comment]
Currently with the pandas conversion, Python does offer some version of a snapshot based on the change stream.

The second improvement sounds good, the endpoint should offer the option to `snapshot`, `snapshot-and-follow` or only `follow` I think, or at least for snapshot-and-follow that there is a clear delineator between the snapshot and the follow phases. Making HTTP more reliable with replay for specific position is likely not a very needed feature if there is snapshot-and-follow available, and would likely be a lot of work?

**Comment by ryzhyk** [comment]
> Currently with the pandas conversion, Python does offer some version of a snapshot based on the change stream.

I don't think so. It simply converts changes into dataframes with an extra column for the insert/delete flag
