### ISSUE TITLE
querying an empty view should show that result is empty

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2882]
if we have an empty view table and do select * from empty, currently there is no feedback to the user aside from the query not showing anything. e.g. we should do what psql/others to they displays `(0 rows)` as a result. we should also make a new textbox after a query which yields 0 rows as it's a valid result and a useful pattern to do an insert in the next box and then go back re-evaluating the select query

**Comment by Karakatiza666** [comment]
This is the behavior on latest `main`

![image](https://github.com/user-attachments/assets/a1ff3c31-e960-4172-8506-3bab712e4ce4)

**Comment by Karakatiza666** [comment]
LMK if it's better to replace the message with "0 rows"
