### ISSUE TITLE
[sql] Anonymous tuples are not supported

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#2908]
This query fails:

```sql
CREATE TABLE t(
    group_id bigint,
    x bigint,
    y bigint,
    z bigint
);

CREATE VIEW v2 AS
    SELECT group_id,
        ARG_MAX(z, (x,y))
    FROM t
    group by group_id;
```

with

```
Function 'ROW' not yet implemented
This is tracked by issue https://github.com/feldera/feldera/issues/1265
:ROW(`z`, `$f2`)
```

which is fair enough, although `ROW` isn't one of the functions listed in that issue.

But if I rewrite this the way I think Calcite tries to re-write it, it compiles:

```sql
CREATE VIEW v AS
    WITH ranked AS (SELECT
        group_id,
        z,
        row_number() over (PARTITION BY group_id ORDER BY x DESC, y DESC) as rn
    FROM
        t)
    SELECT * FROM ranked
    WHERE
        rn = 1;
```

which makes me wonder whether with a bit more effort we could handle the query plan that the original query generates.

PS. the original query compiles if I do `ARG_MAX` over one column: `ARG_MAX(z, x)`.

**Comment by ryzhyk** [comment]
Based on discussion with @mihaibudiu , the problem here is that we don't support the anonymous tuple type (`ROW` is a constructor for this type). I renamed the issue accordingly. In the meantime, it would be nice to improve the error message to something like "anonymous tuples are not supported".

**Comment by ryzhyk** [comment]
If you run into this issue, one possible workaround is to use user-defined types (`CREATE TYPE`) instead.

**Comment by lalithsuresh** [comment]
@ryzhyk let's leave an example here of how to use `CREATE TYPE` in combination with ARG_MAX(). As for the error message, let's make it actionable:

```
Anonymous tuple types (ROW) is not supported. Consider using making a user-defined type (`CREATE TYPE`) instead. See: https://github.com/feldera/feldera/issues/2908
```
