### ISSUE TITLE
[SQL] join optimization 

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#2911]
Seems that some SLT tests from select5 are failing with out of memory.
This suggests that the join optimizations are not working properly.

**Comment by ryzhyk** [comment]
Multiway joins might be the best way to solve this.

**Comment by mihaibudiu** [comment]
not really, the problem is that conditions are not pushed to the joins early in the plan, so I suspect the plan is "join everything, then filter"

**Comment by mihaibudiu** [comment]
well, maybe multiway joins may help

**Comment by mihaibudiu** [comment]
but these queries do have good plans, and we used to find them

**Comment by ryzhyk** [comment]
If it's really compiled into a Cartesian product followed by a filter, then yes, multiway joins won't do anything to help. But if the planner simply finds a bad sequence of joins, then a multiway join can help a lot, it basically makes the performance much less sensitive to join ordering. It also avoids materializing intermediate results.

**Comment by mihaibudiu** [comment]
The truth is that multiway joins will help no matter what, since they can be asymptotically better than any particular join ordering.
Especially since the join ordering chosen by the compiler has no idea about the size of the particular relations.
