### ISSUE TITLE
Document the ad-hoc queries feature

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#2956]
It's unclear to users from the docs that this is built on DataFusion and uses a different SQL dialect.

**Comment by mihaibudiu** [comment]
I wanted to write something too. Maybe today

**Comment by mihaibudiu** [comment]
Can we close this issue after publishing https://www.feldera.com/blog/inspecting-feldera-pipelines?
This is not really documentation, but it does solve the problem raised in this issue.

**Comment by ryzhyk** [comment]
We need proper docs

**Comment by gz** [comment]
we have this. I think it covers the things you suggested, but it doesn't explicitly mention datafusion ... I can add some examples of differences I encountered in the past but other than that feel free to suggest what you want to see there https://docs.feldera.com/sql/ad-hoc

**Comment by gz** [comment]
I think we should probably move this page under "Feldera Interface"

**Comment by ryzhyk** [comment]
My bad, forgot about these docs. 

> Feldera does not guarantee consistency between SQL dialects of Feldera programs and ad-hoc queries as the former is used in an incremental view maintenance (IVM) context and the latter is not, so more complex ad-hoc queries may produce different results than an SQL program.

We should generally produce consistent results for the common subset of SQL, modulo rounding for floating point values. I suppose there are other corner cases, like different handling of decimal precision. But in general we don't want to make it sound like incremental evaluation is an excuse for incorrect results.

+1 on mentioning datafusion explicitly, so people know to check datafusion syntax.

I think it makes sense to have an AdHoc query page in the SQL reference, as I guess that's one place where people may look for it, but maybe we could also link to it from Feldera Interface. We no longer have a high-level diagram of Feldera anywhere (could be in the What is Feldera page). That'd be another place to show Ad Hoc queries.

**Comment by mihaibudiu** [comment]
There is a diagram for ad-hoc in my last blog post.
