### ISSUE TITLE
display column number in webconsole editor

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2976]
we see the line numbers but there is no way to get the column index in the web editor currently, this makes error like this harder to find:

```
Encountered "bigint" at line 100, column 136.
```

**Comment by gz** [comment]
nvm I guess we solve this with the squiggly lines, just that my line was way too long to see it

**Comment by mihaibudiu** [comment]
Is there soft wrap?

**Comment by Karakatiza666** [comment]
@mihaibudiu  I will add line wrap setting to the editor later. Currently if you click on the icon next to the error the error location scrolls into view, including column
