### ISSUE TITLE
recursive view definition mismatch better error message

### ISSUE THREAD

**Issue by gz** [feldera/feldera#2977]
maybe this error messages can be changed into something that can just be copy-pasted to replace the wrong declaration I just wrote

```
 Type mismatch:
Type inferred for view 'spreadsheet_view' is RecordType(BIGINT NOT NULL id, VARCHAR(64) NOT NULL raw_value, INTEGER NOT NULL background, BIGINT ARRAY mentions_ids, VARCHAR(64) ARRAY mentions_values, VARCHAR(64) computed_value) NOT NULL
  104|create materialized view spreadsheet_view as
  105|select
      ...
  113|    mentions_aggregated;
```

**Comment by mihaibudiu** [comment]
The problem is not the declaration but the definition. This is documented

**Comment by gz** [comment]
the issue is about the error message which could be improved.. ideally I could just copy and paste the line the compiler gives me and paste it in when I get it wrong

but right now it says `RecordType` and it prints the field name after the type

**Comment by mihaibudiu** [comment]
You cannot paste it because the problem is not the declaration

**Comment by gz** [comment]
don't understand, it was the declaration in my case

**Comment by mihaibudiu** [comment]
I would recommend against using varchar(n), it only leads to hard to debug errors

**Comment by gz** [comment]
it doesn't matter here.. do you understand the issue I'm trying to report or do I need clarify more?

**Comment by mihaibudiu** [comment]
You don't want to see rowtype keyword

**Comment by gz** [comment]
currently I'm getting

```
 Type mismatch:
Type inferred for view 'spreadsheet_view' is RecordType(BIGINT NOT NULL id, VARCHAR(64) NOT NULL raw_value, INTEGER NOT NULL background, BIGINT ARRAY mentions_ids, VARCHAR(64) ARRAY mentions_values, VARCHAR(64) computed_value) NOT NULL
  111|create materialized view spreadsheet_view as
  112|select
      ...
  120|    mentions_aggregated;
Type mismatch:
does not match the declared type RecordType(BIGINT NOT NULL id, VARCHAR(64) NOT NULL raw_value, INTEGER NOT NULL background, BIGINT ARRAY mentions_ids, VARCHAR(64) ARRAY mentions_values, INTEGER computed_value) NOT NULL:
```

ideally it could be

```
 Type mismatch:
Type inferred for view 'spreadsheet_view' is `(
    id bigint not null,
    raw_value varchar(64) not null,
    background integer not null,
    mentions_ids bigint array,
    mentions_values varchar(64) array,
    computed_value integer
)````

**Comment by mihaibudiu** [comment]
Technically yours is a signature, not a type. This will need a fair amount of work. This is all on the Calcite side
