### ISSUE TITLE
Builtin function name `user` clashes with table name 

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#3006]
This SQL

```sql
CREATE TABLE user (
    id BIGINT
);

CREATE TABLE t (
    user_id BIGINT
);

CREATE MATERIALIZED VIEW v AS
SELECT
    t.user_id
FROM
    user,
    t
WHERE
    user.id = t.user_id;
```

throws this error:

```
Incompatible types
   16|    user.id = t.user_id;
          ^^^^
```

Renaming the `user` table to any other identified fixes it.

We've run into this before. It would be better to reject table names that clash with function names.

**Comment by lalithsuresh** [comment]
We have a builtin function called 'user' ? This definitely deserves a better error message.

**Comment by mihaibudiu** [comment]
Calcite does
