### ISSUE TITLE
[fda] error message is unhelpful

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#3010]
I was wondering if I could create a pipeline given the SQL file only (was hoping it would extract pipeline name from file name). This failed, which is fine, but the error message doesn't seem to contain any useful information other than the 400 error code:

```
fda --host localhost:8080  create liveness-naive.sql

[WARN ] The provided API key is not added to the request because http://localhost:8080 does not use `https`.
Failed to create pipeline: 
[ERROR] Unexpected response from http://localhost:8080: Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/v0/pipelines", query: None, fragment: None }, status: 400, headers: {"content-length": "232", "access-control-allow-credentials": "true", "content-type": "application/json", "vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers", "date": "Sat, 23 Nov 2024 16:41:37 GMT"} }
[ERROR] Try upgrading to the latest CLI version to resolve this issue or report it on github.com/feldera/feldera if you're already on the latest version.
```

Concrete questions:
- Is it possible to print the errors in a nicer way (without losing useful information)? This detailed output can be confusing, e.g., there's no point in showing the `cannot_be_a_base` flag unless the error is indeed the wrong url base.
- Are we losing the actual error message here? I don't see any useful info other than the 400 code.

**Comment by blp** [comment]
I've noticed the same thing in other error cases with fda.

**Comment by gz** [comment]
does it change anything if you use http://localhost:8080 as hostname?

**Comment by blp** [comment]
In the cases I've examined, it happened because the particular error
response was not enumerated in openapi.json. When I added it (to the Rust
that generated openapi.json), that fixed the problem for that particular
case.

**Comment by gz** [comment]
yes thats usually the fix. 

my question is because in @ryzhyk  example he omits the https. I think if you have an API key set but dont specify localhost with http it will try to authenticate using https.
