### ISSUE TITLE
New UI: use a single configuration button

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#3017]
We currently have two different configuration buttons, one for the program and the other for the pipeline. There is no context for the user about the program configuration (it's not documented, so users won't know why it's there).

Keep one icon (the gear). And specify just the pipeline configuration for now. If you want to add the program config, add it as another json entry within the same form.

**Comment by snkas** [comment]
The program configuration will have a "cache" option added to specify whether to force recompilation or not (already in the compiler rework PR), which is relevant to the compiler rework. Additionally, in future there might be compiler flags passed (https://github.com/feldera/feldera/issues/2898). It's useful for development to be able to edit it in the UI.
