### ISSUE TITLE
Leaving a page during save leaves pipeline (and potentially other entities) in a bad state

### ISSUE THREAD

**Issue by gz** [feldera/feldera#302]
- click X icon on a connector
- saving...
- navigate to other page through menu on left while saving
- go back to pipeline builder
- expect: connector that X got clicked is gone
- observed: all connectors are gone

fix is likely to move the save logic a layer above so saving doesn't stop while navigating away, another way to leave the page is for the user to just close the tab then we should display a dialog (like google docs does it)

**Comment by Karakatiza666** [comment]
An appropriate way to tackle this seems just to add a warning when leaving the page while save is in progress
