### ISSUE TITLE
HTTP input adapter error message on failure

### ISSUE THREAD

**Issue by gz** [feldera/feldera#3023]
when the input adapter fails to load an URL we report this error message

```
 FATAL error on input endpoint 'table.30122650df': received unexpected HTTP status code (403 Forbidden)
```

it would be good to include also the URL that it failed to load (from the input adapter configuration) then the user can make a better mental link between what failed and where the configuration for this is that is responsible for the failure

**Comment by blp** [comment]
I guess that this is going to be the case for many of the endpoint types. Maybe we should give more details at a high level for messages from each endpoint, e.g.:

```
FATAL error on input endpoint 'table.30122650df' (URL ...): received unexpected HTTP status code (403 Forbidden)
```

Probably wouldn't be too hard, I'll see if I can do that.

**Comment by blp** [comment]
I'm not sure where the `.30122650df` comes from, either, or whether it is meaningful.

**Comment by lalithsuresh** [comment]
It's not meaningful either. IIRC, the pipeline manager generates these endpoint names. @snkas

**Comment by gz** [comment]
It might be useful to also print the http response body on error (in some log level) if not already done so

**Comment by lalithsuresh** [comment]
While we're tacking on improvements to this connector, here are two more gaps:

* Adding custom headers (e.g. for authentication)
* And the option to periodically poll the URL

... are both gaps.

**Comment by blp** [comment]
> While we're tacking on improvements to this connector, here are two more gaps:
> 
>     * Adding custom headers (e.g. for authentication)
> 
>     * And the option to periodically poll the URL

Those are quite independent so I filed #3024 for them.
