### ISSUE TITLE
If a pipeline becomes unavailable we should try to get it back

### ISSUE THREAD

**Issue by gz** [feldera/feldera#3121]
Correct me if wrong but I think once a pipeline is unavailable it stays in this state (e.g., if it's too busy to respond within 10sec it's considered lost forever). We should probably continue trying to contact it in case it comes back for a while (few mins).

**Comment by ryzhyk** [comment]
I think this was recently fixed by @snkas . The manager keeps polling the pipeline and it eventually goes back to the RUNNING state if it becomes available again.  At least this is the behavior I've observed.

**Comment by snkas** [comment]
It should indeed come back up, it regularly tries to again reach out to the pipeline. If any of the `/stats` requests succeed, it will become the status (e.g., `Running`/`Paused`) that it reports.

**Comment by snkas** [comment]
It is an important part of the design: pipelines becoming unavailable for some time is expected (e.g., when being moved to a new node).

**Comment by gz** [comment]
Sounds good I'll try to figure what's special about mine that it doesn't come back

**Comment by mihaibudiu** [comment]
I will close this issue then.
