### ISSUE TITLE
[SQL] Incorrest result when subtracting Interval from Interval 

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#3132]
For a SQL program such as:

```
CREATE TABLE timestamp_tbl(
id INT,
c1 TIMESTAMP NOT NULL,
c2 TIMESTAMP);

CREATE LOCAL VIEW atbl_long_interval AS SELECT
id,
(c1 - c2)YEAR as years,
(c2 - c1)YEAR as years_rev
FROM timestamp_tbl;

CREATE LOCAL VIEW linterval_plus_linterval AS SELECT
id,
years + INTERVAL '12' YEAR  AS f_c1,
years_rev + (- INTERVAL '12' YEAR ) AS f_c2
FROM atbl_long_interval;

CREATE MATERIALIZED VIEW linterval_plus_linterval_res AS SELECT
id,
CAST((f_c1) AS BIGINT) AS f_c1_res,
CAST((f_c2) AS BIGINT) AS f_c2_res
FROM linterval_plus_linterval;
```

Where input for timestamp_tbl as: 
`{"id": 1, "c1": "2020-06-21 14:00:00", "c2": "2023-02-26 18:00:00"}`

View **linterval_plus_linterval_res** returns: 
`{'id': 1, 'f_c1_res': 9, 'f_c2_res': -9}`

When it should return: 
`{'id': 1, 'f_c1_res': 10, 'f_c2_res': -10}`

**Note:** 
View  **atbl_long_interval**  returns: 
`{'id': 1, 'years_res': -2, 'years_rev_res': 2}`

**Comment by mihaibudiu** [comment]
I actually don't really understand the semantics of the difference between two time objects, I think I will remove this function from the list of operations supported. We have a function called `TIMESTAMPDIFF` which is well-defined which can be used for this purpose.

**Comment by mihaibudiu** [comment]
Calcite really seems to ignore the interval specifier, except to derive whether an interval is long or short, and then it computes the difference in months (for long interval) or seconds (for short intervals).
In these circumstances, the result may be correct.

**Comment by mihaibudiu** [comment]
I think I have a compromise solution: we will not support arbitrary time units for subtracting values. We will only support MONTHS for long interval results, and SECONDS for short interval results. These guarantee that the resulting interval precisely represents the difference between the two objects (without any truncation). To support the other variants of subtraction would require significant changes to our type system. I will write some tests and amend #3137. This will also make the example in this issue invalid.
