### ISSUE TITLE
[SQL] Compilation fails for MAX on ARRAY type for a query returning empty result

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#3145]
The following query:

```
CREATE MATERIALIZED VIEW max_emp AS SELECT
MAX(c1) AS max
FROM array_tbl
WHERE FALSE;
```

Fails to compile when **array_tbl** is defined as:
```
CREATE TABLE array_tbl(
id INT,
c1 INT ARRAY NOT NULL,
c2 INT ARRAY,
c3 MAP<VARCHAR, INT> ARRAY);
```

With the following error:
**SQL compiler process returned with non-zero exit status code (1) and stderr which cannot be deserialized due to expected value at line 1 column 1:
Exception in thread "main" org.dbsp.sqlCompiler.compiler.errors.UnimplementedException: Cast from Vec<i32?> to Vec<i32?>? not implemented:**

However, it passes when array_tbl is defined as:
 ```
CREATE TABLE array_tbl(
c1 INT ARRAY NOT NULL);
```

**Comment by mihaibudiu** [comment]
I cannot reproduce this bug with the latest main branch.
