### ISSUE TITLE
WebConsole shows 500 error when Feldera instance becomes unreachable

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#3163]
The fix: provide an error page that is displayed after all unexpected JavaScript crashes

**Comment by snkas** [comment]
**Extra context from back-end implementation perspective:**

When the Web Console errors significantly (e.g., for local form factor, terminate the pipeline-manager process and refresh the Web Console, causing it to be unable to reach the back-end), it shows a blank page with the following error:

```
500
Internal Error
```

This gives the impression that the back-end returned a 500 error, whereas it actually did not. Ideally, this should be replaced with a clearer error message which provides more information (e.g., "Back-end could not be reached." or "Back-end took too long to respond.", or "Unable to reach back-end.").

**Comment by Karakatiza666** [comment]
I went for the following presentation:
![image](https://github.com/user-attachments/assets/60311b29-f921-409e-a9ee-6e1b60213741)

**Comment by snkas** [comment]
Looks great! Thanks a lot. The error message is some string supplied by the Web Console when the error occurred?

**Comment by Karakatiza666** [comment]
Yes, it is a message generated by WebConsole's JavaScript; generally the message can use some server-provided string, but this situation is not really in our use-case

**Comment by lalithsuresh** [comment]
"Unable to reach the Feldera service. Please check your internet connection, make sure the Feldera service is running and reload the page."

**Comment by Karakatiza666** [comment]
It is

**Comment by Karakatiza666** [comment]
![image](https://github.com/user-attachments/assets/e2eb447a-2372-4a48-a46a-bc63a80cf9d8)
