### ISSUE TITLE
[SQL] Comparison operations on ROW type with different element types gives an error

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#3180]
The following SQL program:

```
CREATE TABLE row_tbl(
id INT,
c1 INT NOT NULL,
c2 VARCHAR,
c3 VARCHAR);


CREATE MATERIALIZED VIEW v AS SELECT
ROW(c3, c1) !=  ROW(c1, c3) AS c1
FROM row_tbl;
```

Produces the following error:
**This is a bug in the compiler (please report it to the developers):
Tup2<i32, s?> is not an instance of interface org.dbsp.sqlCompiler.ir.type.IsNumericType**

**Comment by mihaibudiu** [comment]
This may happen for ARRAY and MAP too, it is triggered by the != operation.
Can you write some tests that exercise these as well?

**Comment by rivudhk** [comment]
This error occurs for all comparison operations when the leading element of the ROW types being compared are different:

>  EVERY/SOME(ROW(**INT**, VARCHAR) operator ROW(**VARCHAR**, INT))    //vice-versa

**Comment by mihaibudiu** [comment]
This is the underlying cause: https://issues.apache.org/jira/browse/CALCITE-6735, which I plan to fix.

**Comment by mihaibudiu** [comment]
This has nothing to do with SOME, EVERY, it's about comparing ROW values with different types.
