### ISSUE TITLE
[WebConsole] UI issues on a wide screen

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#3181]
This is what the UI looks like on a wide screen:

![image](https://github.com/user-attachments/assets/04218ccf-b50b-4d68-ad65-b29758504641)

I see two issues here:
* The white space on the right is not usable (we can't expand the window into it)
* The grey area under the memory graph is not used either.

Both of these don't look very nice.

**Comment by Karakatiza666** [comment]
UI was supposed to be centered and limited in width on ultra-wide screens. **sigh** It looks like I need to test everything the second time on Firefox.

As for the gray area, I will move View statistics table on wider screens there, if any are available

**Comment by ryzhyk** [comment]
> UI was supposed to be centered and limited in width on ultra-wide screens. sigh It looks like I need to test everything the second time on Firefox.

Why not use the whole screen?
