### ISSUE TITLE
pipeline status in wrong place

### ISSUE THREAD

**Issue by gz** [feldera/feldera#3184]
![image](https://github.com/user-attachments/assets/682ae3ca-bd8d-4c8b-a791-8a42d78ddbbe)
status shouldnt be up there if there is enough space. probably status should never be up there it looks ugly

**Comment by Karakatiza666** [comment]
I will make the pipeline status chip content-aware, so that it is displayed inline for shorter pipeline names even if it would be pushed above for longer pipeline names
