### ISSUE TITLE
[SQL] COUNT(DISTINCT col) applied to Row type produces incorrect results

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#3196]
The following SQL:

```
CREATE TABLE row_tbl(
id INT,
c1 INT NOT NULL,
c2 VARCHAR,
c3 VARCHAR);

CREATE MATERIALIZED VIEW row_count_col_gby AS SELECT
id, COUNT(DISTINCT ROW(c1, c2, c3)) AS c1
FROM row_tbl
GROUP BY id;
```

Given the following input:

```
{"id": 0, "c1": 4, "c2": None, "c3": "adios"},
{"id": 0, "c1": 3, "c2": "ola", "c3": "ciao"},
{"id": 1, "c1": 7, "c2": "hi", "c3": "hiya"},
{"id": 1, "c1": 2, "c2": "elo", "c3": "ciao"},
{"id": 1, "c1": 2, "c2": "elo", "c3": "ciao"}
```

Produces the following result:
**[{"id": 0, "c1": 1}, {"id": 1, "c1": 2}]**

When it should produce:
**[{"id": 0, "c1": 2}, {"id": 1, "c1": 2}]**

Without group-by, it produces: **{'c1': 3}** 
When it should produce: **{'c1': 4}**

**Note:** This happens when there is NULL value present in the column

**Comment by mihaibudiu** [comment]
I don't understand this bug. The result produced is actually (0,2), (1,3), which is correct, but is neither of the two results you show. There are 3 records with id:1

**Comment by mihaibudiu** [comment]
I tagged this as "invalid", please reopen with additional information if needed.

**Comment by rivudhk** [comment]
@mihaibudiu I've updated the SQL. It was supposed to be: **COUNT(DISTINCT col)**. Can you please try again?
