### ISSUE TITLE
[SQL] DATE -/+ INTERVAL MONTHS produces incorrect results on certain input values

### ISSUE THREAD

**Issue by rivudhk** [feldera/feldera#3222]
The following SQL:

```
SELECT
'2023-02-26':: DATE + INTERVAL '-32' MONTHS AS mth1,
'1948-12-02':: DATE + INTERVAL '246' MONTHS AS mth2
```

Produces the following result:
**{'mth_1': '2020-06-26', 'mth_2': '1969-06-02'}**
                      
When it should produce:
**{'mth_1': '2020-06-21', 'mth_2':'1969-06-21'}**

**Note:**
This only happens for the following cases:

**1. If the interval is a negative value
2. For date values before the year 1970**

**Comment by mihaibudiu** [comment]
Why should the day be different when adding a whole number of months?
