### ISSUE TITLE
An `Aggregator` that combines multiple `Fold`s

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#36]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Tue Aug 23 16:13:54 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/158_

----

None

**Comment by mihaibudiu** [comment]
I don't know if this is necessary, the SQL compiler already knows how to combine multiple Folds into one.

**Comment by mihaibudiu** [comment]
I will close this issue since the compiler does this.
