### ISSUE TITLE
UI sidebar order is awkward for documentation

### ISSUE THREAD

**Issue by blp** [feldera/feldera#361]
In documenting the UI, it makes sense to talk about programs and connectors first, and then pipelines, since pipelines use both of the others. You want to visit them in that order if you're adding something new. But the UI puts them in a different order: programs, connectors, pipelines. I think that programs, connectors, pipeline is a better order.

**Comment by gz** [comment]
I think that's fair, we can change the order... one argument for putting pipeline before connector was that you can run a pipeline without any connectors added to it and then use our API (and UI soon) to push data to tables and read data from tables/connectors so technically connectors are not needed for having something "useful"
