### ISSUE TITLE
Sometimes hard to spot the compiler errors in the UI

### ISSUE THREAD

**Issue by blp** [feldera/feldera#364]
Sometimes when I see a compiler error in the UI, I have to scroll around and eyeball the code carefully to find the squiggle that I can hover to find out about the error. Often, the location of the squiggle has nothing to do with the location of the error. For example, the following SQL yields an error that the `LAG` function is unimplemented by putting a squiggle under `CREATE` on the first line even though `LAG` is only used near the end of the file.

```sql
CREATE TABLE demographics (
    cc_num FLOAT64 NOT NULL,
    first STRING,
    gender STRING,
    street STRING,
    city STRING,
    state STRING,
    zip INTEGER,
    lat FLOAT64,
    long FLOAT64,
    city_pop INTEGER,
    job STRING,
    dob STRING
    --dob DATE
);

CREATE TABLE transactions (
    trans_date_trans_time TIMESTAMP NOT NULL,
    cc_num FLOAT64 NOT NULL,
    merchant STRING,
    category STRING,
    amt FLOAT64,
    trans_num STRING,
    unix_time INTEGER NOT NULL,
    merch_lat FLOAT64,
    merch_long FLOAT64,
    is_fraud INTEGER
);

CREATE VIEW features as
    SELECT
        DAYOFWEEK(trans_date_trans_time) AS d,
        TIMESTAMPDIFF(YEAR, trans_date_trans_time, CAST(dob as TIMESTAMP)) AS age,
        ST_DISTANCE(ST_POINT(long,lat), ST_POINT(merch_long,merch_lat)) AS distance,
        TIMESTAMPDIFF(MINUTE, trans_date_trans_time, last_txn_date) AS trans_diff,
        AVG(amt) OVER(
            PARTITION BY   CAST(cc_num AS NUMERIC)
            ORDER BY unix_time
            -- 1 week is 604800  seconds
            RANGE BETWEEN 604800  PRECEDING AND 1 PRECEDING) AS
        avg_spend_pw,
        AVG(amt) OVER(
            PARTITION BY  CAST(cc_num AS NUMERIC)
            ORDER BY unix_time
            -- 1 month(30 days) is 2592000 seconds
            RANGE BETWEEN 2592000 PRECEDING AND 1 PRECEDING) AS
        avg_spend_pm,
        COUNT(*) OVER(
            PARTITION BY  CAST(cc_num AS NUMERIC)
            ORDER BY unix_time
            -- 1 day is 86400  seconds
            RANGE BETWEEN 86400  PRECEDING AND 1 PRECEDING ) AS
        trans_freq_24,
        category,
        amt,
        state,
        job,
        unix_time,
        city_pop,
        merchant,
        is_fraud
    FROM (
        SELECT t1.*, t2.*
               , LAG(trans_date_trans_time, 1) OVER (PARTITION BY t1.cc_num  ORDER BY trans_date_trans_time ASC) AS last_txn_date
        FROM  transactions AS t1
        LEFT JOIN  demographics AS t2
        ON t1.cc_num = t2.cc_num);
```

**Comment by gz** [comment]
> yields an error that the LAG function is unimplemented by putting a squiggle under CREATE on the first line even though LAG is only used near the end of the file.

AFAICT this would be something that needs to be fixed in the compiler (by passing different/longer line/column information which then the editor uses to display the squiggly lines)
@mihaibudiu

**Comment by blp** [comment]
> AFAICT this would be something that needs to be fixed in the compiler (by generating different/longer line/column information which then the editor uses to display the squiggly lines) @mihaibudiu

That is one way this could be improved, but it would also be helpful to have an easier way to spot the location of an error. For example, there could be a mark in the left margin, or a way to jump to the next/previous error, or a pane that lists the errors. This is not a major problem now, since the programs I am working with are short, but it could become more of a problem later.

**Comment by mihaibudiu** [comment]
Yes, the line location of the squiggle should be displayed more prominently if the editor supports that.

**Comment by gz** [comment]
I think there are two issues here:

- Just squiggly lines being hard to spot sometimes
but also
- The reported error being on CREATE when it should maybe highlight the LAG function?

The latter needs some change in the compiler

**Comment by mihaibudiu** [comment]
Please note that the editor we are using is off-the-shelf based on CodeMirror, so if it can't support this it may not be easy.

**Comment by mihaibudiu** [comment]
What happens in this case is that the LAG expression in Calcite does *not* have source position information, so the squiggle probably shows on the first line. I will see whether there's anything that could be done to improve on this.

**Comment by gz** [comment]
Here is another example where the column/row information should be on the data type vs. rather than the `create`:

![image](https://github.com/feldera/dbsp/assets/127654/d9df9cf5-2ab4-43f5-a1b7-32f50927c3b6)

**Comment by lalithsuresh** [comment]
Fixed with latest UI
