### ISSUE TITLE
Implement URL input adapter and use it in the demo.

### ISSUE THREAD

**Issue by blp** [feldera/feldera#426]
- [x] Implement an input adapter to fetch data from a URL.
- [x] Put our demo input data into S3. For some demos, we want to have small and large versions of the file.
- [ ] Make the demos use one version of the data. Provide input connectors for the other versions. Add demo instructions for how to connect the other versions.

**Comment by ryzhyk** [comment]
@blp ,  @lalithsuresh can help with access to our AWS account so you can setup the S3 buckets.

**Comment by blp** [comment]
Should the URL input adapter be an optional feature of the adapters crate? Or always included?

**Comment by ryzhyk** [comment]
I would keep things simple and not make it optional.  In an upcoming PR, I also removed the `server` feature, since it was becoming a pain to maintain.  (The Kafka adapter is still feature-gated, since it depends on a native library.)

**Comment by blp** [comment]
> I would keep things simple and not make it optional. In an upcoming PR, I also removed the `server` feature, since it was becoming a pain to maintain. (The Kafka adapter is still feature-gated, since it depends on a native library.)

Thanks, I was hoping to hear that.

**Comment by blp** [comment]
[PR for input adapter](https://github.com/feldera/dbsp/pull/431#pullrequestreview-1565893639)

**Comment by blp** [comment]
This has been finished for a long time. Closing.
