### ISSUE TITLE
CSV ingress applies left trim but not right trim

### ISSUE THREAD

**Issue by gz** [feldera/feldera#443]
e.g., for a timestamp 

'  1997-02-28 12:12:00' is a valid timestamp value but  '1997-02-28 12:12:00  ' is not a valid timestamp value 

should both types be accepted?

**Comment by ryzhyk** [comment]
Thanks for investigating, @blp . 

> The question then seems to be, what do SQL engines accept in timestamps?

It seems that being liberal in what we accept makes sense in this case.  And I think your fix is spot on.

**Comment by blp** [comment]
I wrote some code that mostly fixes this: https://github.com/feldera/dbsp/commit/0fa31b7ebcdc005755202151db77b48610dc8a43. However, after playing with it, I concluded that Calcite doesn't allow leading or trailing spaces when it parses timestamps, because the JIT compiler version of the timestamp tests ends up with literal nulls in the `.rs` file wherever I insert trailing spaces in the JitPostgresDateTest. That is, the timestamps get evaluated when the Java program compiles the test. We don't have Java code to evaluate timestamps so that must be Calcite doing it. And my quick look through the Calcite implementation seems to confirm that: it checks the parser position after it calls it and makes sure that it's at the end of the string (see https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java#L3137C1-L3147). I don't think we can fix this except by submitting a PR for Calcite.

Since we can't easily have the behavior that makes the most sense, I think that the next best thing would be to document it. I created a [branch for that](https://github.com/feldera/dbsp/tree/issue443-2).

**Comment by blp** [comment]
I think this is fixed as best it can. I left the [branch `issue443`](https://github.com/feldera/dbsp/tree/issue443) in place for now with my attempt at making the SQL code accept trailing white spaces, in case anyone wants to take a look and see whether there's something I missed.

**Comment by gz** [comment]
Thanks for digging into this. Who would've thought it's so much effort. 

Maybe I'm missing something but it seems odd that we have to change parsing code in more than one place (JIT+SQL) for something like this. 
Ideally we would validate and make all input well-formed at the ingress point before it gets passed on to SQL/JIT so they only see well formed (in this case trimmed things). I guess SQL literals still need some form of parsing so we can't get entirely rid of this but at least there we can probably be more strict in what is expected as the compiler can check it at compile-time and give reasonable errors?

**Comment by ryzhyk** [comment]
@blp , I ran into this again as I am writing docs for our JSON format. Is my understanding correct that what happens with the JIT test is that @mihaibudiu relies on some Calcite infrastructure to parse date/time literals in his test harness and it doesn't trim white space.  If that's the case, this is something that only affects the test harness, and there's no reason we shouldn't merge your fix, which improves the behavior of our actual deserialization code.

**Comment by blp** [comment]
> @blp , I ran into this again as I am writing docs for our JSON format. Is my understanding correct that what happens with the JIT test is that @mihaibudiu relies on some Calcite infrastructure to parse date/time literals in his test harness and it doesn't trim white space. If that's the case, this is something that only affects the test harness, and there's no reason we shouldn't merge your fix, which improves the behavior of our actual deserialization code.

I don't think it's about the test harness. I think it's about the constant expression evaluator in Calcite, which is something that we can't control without changing Calcite itself.

That is, I think this is what's going on: Calcite has a constant expression evaluator that it uses when it parses SQL code. This constant expression evaluator doesn't use our code at all. It does its thing without paying attention to us. On the other hand, we're responsible for evaluating expressions at runtime, and we can control that.

So, if we merged my changes, we'd have to document the SQL engine as having two different behaviors, something like this:
> If you specify a constant expression for a date or time literal, or an expression that Calcite can optimize to a constant expression, then DBSP will reject it if you have trailing white space in your literal. For other expressions on dates or times, DBSP will accept trailing white space.

That would be a really weird thing to put in documentation.

@mihaibudiu , do I have this right?

**Comment by ryzhyk** [comment]
The Calcite expression evaluator only kicks in when a date/time literal is used in a query.  I don't think it's a big deal if the user is forced to remove whitespaces in that context.  The Rust runtime parser on the other hand applies to all the data that streams into the pipeline in JSON, CSV, and other formats.  I think it's a good idea to be liberal in what we accept there even if it's not precisely identical to the date/time literals we allow in queries.

**Comment by ryzhyk** [comment]
I suspect that Mihai also uses the Calcite evaluator when parsing `insert`/`delete` commands that occur in tests.  These should only affect the test harness.

**Comment by mihaibudiu** [comment]
Input data != literals. You can have completely different rules.

**Comment by blp** [comment]
> Input data != literals. You can have completely different rules.

@mihaibudiu Can you help with the attempted fix in the `issue443` branch? `JitPostgresDateTest` fails and I don't know how to fix it.

**Comment by mihaibudiu** [comment]
I see your dilemma. A date literal is SQL is in fact a string literal with a cast (or some other similar construct).
So we have to differentiate between constant strings and non-constant strings.
Let me rewrite the fix in the branch.

**Comment by mihaibudiu** [comment]
In fact, perhaps it's simpler.
trim() should only be applied to strings that are read by the SQL program as input.
Then you only need to keep your changes to TuRustJitLiteral (which generates test inputs) and to the `intrinsics.rs` file.
We can argue separately about INSERT statements, whether the values there are literals or not. I think they are, and thus should not be trimmed.

**Comment by mihaibudiu** [comment]
So you can essentially just revert your changes except for 2 files.
Can you see whether such a PR works?
There's still the problem of the Rust serde, which is not tested by the compiler tests in any way.

**Comment by blp** [comment]
> So you can essentially just revert your changes except for 2 files. Can you see whether such a PR works? There's still the problem of the Rust serde, which is not tested by the compiler tests in any way.

OK, done.

There's a preliminary commit that removes a stray `println` from `casts.rs`.
