### ISSUE TITLE
Avoid redundant `distinct` applications

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#45]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Fri Feb  3 08:05:08 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/287_

----

`distinct` is a no-op when it is connected to the output of `aggregate`, `rolling_aggregate` or any other operator that outputs collections with unit weights only. Implement a simple optimization that skips inserting `distinct` in such cases, similar to how we don't shard already sharded data.

**Comment by mihaibudiu** [comment]
I think this should be up to the compiler.

**Comment by ryzhyk** [comment]
There's a lot we can do in the runtime, similar to how we deal with sharding.  I'll keep this one open.
