### ISSUE TITLE
Support upsert semantics for tables.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#455]
Currently, all SQL tables are backed by Z-set handles. This has two unpleasant implications:

- nothing prevents the user from deleting a non-existing row, which will create a record with a negative weight in DBSP. This shouldn't break anything but may cause surprising behaviors.
- records cannot be deleted by key

I don't have a complete RFC yet, but one approach would be:
- Use upsert handles for all or most tables (or, if we end up distinguishing "regular" and "streaming" tables, the latter continue using regular handles, but operate in insert-only mode).
- For tables with primary keys, use map handles (these are upsert handles where deletion is by key and an insert overwrites any existing record with the same key)
- When our GC mechanism is in place, make sure to GC old records from indexes maintained by `upsert` operators to bound their memory usage.
- Currently duplicate insertions and deletions are quietly suppressed.  Alternatively, we can introduce additional error streams (similar to how we plan to report parse errors) and report them there.

**Comment by ryzhyk** [comment]
I am about to submit a PR that enables upsert semantics for input tables.  Some leftover todos after that PR:

- [ ] Use `MapHandle`'s for input tables with primary keys (we currently use `SetHandle`s for everything).  These also have upsert semantics but support deletion by key and allow changing the value associated with a key with a single event.
- [ ] Insert-only collections (event streams) don't require upserts.
- [ ] We currently drop noop commands (double insertions and deletions) silently.  We may want to provide an option to log such events somehow (e.g., by writing them to a separate stream).

**Comment by mihaibudiu** [comment]
I think that the SQL compiler side for this is done, so I will remove this label.

**Comment by ryzhyk** [comment]
Let's keep the label, so it remains even when  the issue is closed.
