### ISSUE TITLE
Docs cleanup

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#464]
- [x] Remove the using DBSP page
- [ ] Move the "Writing Feldera ... SQL" page to README in the SQL compiler folder (we can also reuse parts of it to write the SQL tutorial)
- [x] Move Dev workflow under "Contributing"
- [x] Remove the Python API section - we'll introduce it in the next release
- [x] Move Rust API page .... somewhere (it's not exactly "Contributing"). Add links to DBSP crate docs (rustdocs, tutorial) inside this section.

**Comment by blp** [comment]
I think that this issue is done.

@ryzhyk Except I don't know what this is (maybe it was already done?):
> Move the "Writing Feldera ... SQL" page to README in the SQL compiler folder (we can also reuse parts of it to write the SQL tutorial)

**Comment by lalithsuresh** [comment]
@ryzhyk I think we can close this issue?
