### ISSUE TITLE
default args for pipeline manager lead to not being able to start twice

### ISSUE THREAD

**Issue by gz** [feldera/feldera#475]
Ideally if we just do cargo run without args it should do something sane.

Right now the defaults are not ideal

```
      --compiler-working-directory <COMPILER_WORKING_DIRECTORY>
          Directory where the manager stores its filesystem state: generated Rust crates, pipeline logs, etc

          [default: .]

      --debug
          Compile pipelines in debug mode.

          The default is `false`.

      --sql-compiler-home <SQL_COMPILER_HOME>
          Location of the SQL-to-DBSP compiler

          [default: ../sql-to-dbsp-compiler]
```

e.g., this `sql-compiler-home` implies we should run it inside of `crates/` but `--compiler-working-directory` would imply it stores db/binaries etc. also under crates.
If this happens, we can only run the manager once, the next time it complains about invalid directories there:

```
error: failed to load manifest for workspace member `/Users/gerdzellweger/workspace/dbsp/crates/data`

Caused by:
  failed to read `/Users/gerdzellweger/workspace/dbsp/crates/data/Cargo.toml
```

e.g. maybe we can set default directory for `compiler-working-directory` back to ~/.dbsp or something else

**Comment by ryzhyk** [comment]
The `sql-compiler-home` default is a regression from moving crates around.  The `compiler-working-directory` one is from before we standardized on `~/.dbsp`.  Definitely a good idea to fix it up so that `cargo run` works out of the box (well, mostly, there's still `pg-embed` feature that must be enabled manually).

**Comment by lalithsuresh** [comment]
Fixed by https://github.com/feldera/feldera/pull/994
