### ISSUE TITLE
Data inspection/data entry UX.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#489]
We should figure out a more ergonomic way to update and browse data in the UI. A typical flow will consist of the user submitting some changes to a table and observing changes to output tables. This requires:

- [ ] a UI to show the stream of changes to a table (in addition to the contents browser UI we have today)
- [ ] the ability to look at several selected input/output tables simultaneously, so you can click "submit" in the data entry UI and instantly see the output changes without navigating to a different view in the browser.

**Comment by gz** [comment]
> the ability to look at several selected input/output tables simultaneously
this seems crowded potentially confusing, why wouldn't you just keep two tabs open in this case?

**Comment by ryzhyk** [comment]
I was hoping for a user experience where you push data and immediately see the output without having to click around and trying to figure out what's changed in the view you just came back to since you last looked at it. Probably not a top priority, but the ability to look at the stream of changes (the first checkbox in this issue) is, and it may require some backend support, so that the user can inspect latest changes even if the monitoring window wasn't open all the time.
