### ISSUE TITLE
SQL compiler error: `CalciteObject:DATEDIFF(FLAG(DAY), $3, $5)`

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#516]
This SQL throws an error: `CalciteObject:DATEDIFF(FLAG(DAY), $3, $5)`.

```sql
create table PART_ORDER (
    id bigint,
    part bigint,
    customer bigint,
    target_date date
);

create table FULFILLMENT (
    part_order bigint,
    fulfillment_date date
);

create view FLAGGED_ORDER as
select
    part_order.customer,
    AVG(DATEDIFF(day, part_order.target_date, fulfillment.fulfillment_date))
    OVER (PARTITION BY part_order.customer
          ORDER BY fulfillment.fulfillment_date
          RANGE BETWEEN INTERVAL 90 days PRECEDING and CURRENT ROW) as avg_delay
from
    part_order
    join
    fulfillment
    on part_order.id = fulfillment.part_order;
```

If this is an unsupported feature, it'd be nice to generate a better error report.

**Comment by mihaibudiu** [comment]
If is impossible to generate a nice error messages because Calcite does not keep source code position for the RelNode IR, which is what the DBSP compiler receives. This is a fundamental problem. I have to figure out whether there is some way to get such information.

**Comment by ryzhyk** [comment]
But what's wrong with this query?

**Comment by mihaibudiu** [comment]
datediff is not implemented

**Comment by mihaibudiu** [comment]
Now datediff is implemented, but this program still does not compile. The error is:
```
error: Not yet implemented: OVER currently does not support sorting on nullable column  CalciteObject:rel#74:LogicalWindow.(input=LogicalProject#72,window#0=window(partition {0} order by [1] range between $3 PRECEDING and CURRENT ROW aggs [COUNT($2), $SUM0($2)]))
```

**Comment by mihaibudiu** [comment]
Error message has been improved in #732

**Comment by mihaibudiu** [comment]
I will close this issue, I think the core problem is fixed. The remaining problem is covered by #517
