### ISSUE TITLE
Additional information in pipeline manager version 

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#544]
Follow up from #529 

We currently print the version associated with the crate package. It would be good to print additional information like the commit ID too.

**Comment by lalithsuresh** [comment]
@gz I merged a PR that displays the version under the Feldera banner. Do we still want to also display things like the git version used, rustc version and other info as well?

I looked at a few options like the `built` crate and `vergen`. These crates bring in pretty heavy dependencies (like a git library) and from the sound of it, will interfere with build caching. The way they work is you add a line to your build.rs script which outputs a rust file into the target folder. You can then `include!()` this file in your program and reference some variables to get things like the git SHA etc.

I'm tempted to not mess with build caching and leave it at just the simple version info for now.

**Comment by gz** [comment]
makes sense. if we want avoid build caching probably makes sense to just enable/include the version info during release builds. not sure we need an extra crate I think setting/reading some env variables during build will most likely do. but lets leave it at version for now and improve in the future

**Comment by mihaibudiu** [comment]
that's usually under "help/about"
