### ISSUE TITLE
Getting stuck in the pipeline view after clicking on an inactive pipeline.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#547]
If I click on an _inactive_ pipeline URL on the home page, it expands the pipeline, but none of the links on the left (SQL Programs, Pipelines, etc.) works.

**Comment by gz** [comment]
The fix should involve to never be able/have an expanded pipeline view for an inactive/shutdown pipeline

**Comment by Karakatiza666** [comment]
Fixed by https://github.com/feldera/feldera/commit/d5d95d09c03aa65d71766a3c81357e72f4eb240d
