### ISSUE TITLE
Cannot collapse inactive pipelines

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#565]
Using the latest `main`, there is still no way to collapse an inactive pipeline (there us no chevron icon to click to collapse it).

**Comment by gz** [comment]
the old behaviour was that it would never expand a pipeline thats shutdown in the first place. I felt at the time that this was the least confusing: it gets shutdown through a click it collapses. and if that status from the API is in shutdown it never gets expanded on load.

**Comment by Karakatiza666** [comment]
Fixed by https://github.com/feldera/feldera/pull/572
