### ISSUE TITLE
Reduce logging when running demo via docker-compose

### ISSUE THREAD

**Issue by abewley-homegrid** [feldera/feldera#575]
The port in the demo lists localhost:8080, but you need to browse to localhost:8085.

<img width="1266" alt="Containers_-_Docker_Desktop" src="https://github.com/feldera/feldera/assets/131919322/47f2a931-9793-4fa0-8e0a-2397ef5ee261">

Also, at startup there are a bazillion messages like, you miss out other important messages:

feldera-pipeline-manager-1  | 2023-08-26 00:52:47 INFO [manager] 172.21.0.5 "GET /v0/programs/018a2f4f-6e36-7d07-a564-e39163a283f1 HTTP/1.1" 200 7646 "-" "python-httpx/0.24.1" 0.001421

**Comment by lalithsuresh** [comment]
@abewley-homegrid the port issue should already be fixed by 7a334fb0f37530db4306b3c2095387e9058c69fe

We do need to revisit the default log levels. These ones are produced by actix and are indeed noisy.

**Comment by ryzhyk** [comment]
Hey @abewley-homegrid! Thanks for the feedback. Yep, we definitely need to slow down are logging :)

**Comment by lalithsuresh** [comment]
Fixed by #581
