### ISSUE TITLE
Topic names gets lost in the Kafka input connector configuration dialogue

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#594]
If the user doesn't press Enter after typing the topic name (which most users won't, because this is not at all obvious), it gets lost and the generated connector has an empty list of topics.

Additionally, the dialogue should enforce non-empty list of topics, otherwise the connector config is invalid.

**Comment by ryzhyk** [comment]
Let's keep it open. This is still a ux issue, maybe one day we find a way to solve it.

**Comment by gz** [comment]
The 'right' fix for this probably involves to get a list of topics from the backend/kafka host then make this a drop-down list where the user can select them.

**Comment by ryzhyk** [comment]
> The 'right' fix for this probably involves to get a list of topics from the backend/kafka host then make this a drop-down list where the user can select them.

This would be nice, but we can't always assume that the topic exists at connector creation time, so being able to enter it manually is still useful.
