### ISSUE TITLE
Documentation links in WebConsole home should point to feldera.com/docs

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#596]
Updated in https://github.com/feldera/feldera/commit/6dea846e9b97267a24afcedaee57d60cd66ff2f6.

![Screenshot 2023-08-28 at 5 09 33 PM](https://github.com/feldera/feldera/assets/28739668/7cf0c907-653f-4a12-9a46-1ba7359a566d)

**Comment by gz** [comment]
I think https://github.com/feldera/feldera/commit/6dea846e9b97267a24afcedaee57d60cd66ff2f6 updated the links .. we just need to release a new docker version @lalithsuresh is working on it
