### ISSUE TITLE
RUSTSEC-2020-0168: mach is unmaintained

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#60]
<a href="https://github.com/apps/github-actions"><img src="https://avatars.githubusercontent.com/in/15368?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [github-actions[bot]](https://github.com/apps/github-actions)**
_Mon Apr  3 00:19:47 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/351_

----

> mach is unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `mach`                      |
| Version             | `0.3.2`                   |
| URL                 | [https://github.com/fitzgen/mach/issues/63](https://github.com/fitzgen/mach/issues/63) |
| Date                | 2020-07-14                         |

Last release was almost 4 years ago.

Maintainer(s) seem to be completely unreachable. 

## Possible Alternative(s)

These may or may not be suitable alternatives and have not been vetted in any way;
- [mach2](https://crates.io/crates/mach2) - direct fork

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0168.html) for additional details.

**Comment by mihaibudiu** [comment]
I don't see a dependabot warning for this one, so I will close it
