### ISSUE TITLE
Differing ordering between model and database causes CI test failures

### ISSUE THREAD

**Issue by blp** [feldera/feldera#613]
The pipeline manager tests sometimes fail in CI. Here is one example: https://github.com/feldera/feldera/actions/runs/6031359653/job/16364916648#step:7:5931. I can't reproduce the failure locally by running `cargo test -p pipeline-manager --features=pg-embed db::test::db_impl_behaves_like_model`, which seemingly always passes for me.

I downloaded the logs from the example cited above and extracted the first failure as [ci.txt](https://github.com/feldera/feldera/files/12489348/ci.txt). Then I extracted the [ci-left.txt](https://github.com/feldera/feldera/files/12489347/ci-left.txt) and [ci-right.txt](https://github.com/feldera/feldera/files/12489346/ci-right.txt) versions of it separately, and then I reordered the right version of it so that the `attached_connectors` were in the same order (by name) as in the left version. This got rid of all the differences (thus, `ci-left.txt` and `ci-right.txt` are identical above).

Is the order of `attached_connectors` significant? If not, then we should compare them order-insensitively.

**Comment by gz** [comment]
> Is the order of attached_connectors significant?

It is significant in the sense that we rely on it being well-ordered for displaying a diff when there is a change in the config between the version that is currently deployed config and the one that we modified. So ideally we can keep the ordering. It's a bit unfortunate that postgres strings are apparently ordered different than rust strings. But maybe as a fix I'll just order everything in rust for now.

**Comment by blp** [comment]
> It's a bit unfortunate that postgres strings are apparently ordered different than rust strings.

Rust `std` orders strings by Unicode code points. Postgres supports [collation](https://www.postgresql.org/docs/current/collation.html), which is complicated because different languages sort the same Unicode code points differently (see the [Unicode Collation Algorithm](https://unicode.org/reports/tr10/)).

I don't know what collation we're configuring Postgres to use. I think that if we specify `C` (or `POSIX`) as the collation, then it will use the same ordering as Rust. That might be just a matter of adding `export LC_ALL=C` to whatever sets up and launches Postgres, or... I don't really know Postgres very well.

I don't know why this would fail sometimes and not others. It is surprising that the collation order would be nondeterministic.

(Apologies if this is all stuff you already know!)

**Comment by gz** [comment]
Yep I also suspected locales.. will do some experimentation.
