### ISSUE TITLE
Create table with duplicate column name with different types results in generic editor highlighting

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#624]
- Create table in SQL program
- `create table abc (mycol1 number, mycol2 date, mycol2 timestamp);`

The compiler error notification raises a generic error in tooltip of `Compilation had 1 error, check highlighted lines in the editor for more details.` The editor shows the whole table as errored instead of the duplicated rows. The tooltip in the editor however shows the correct message. With a table with lots of columns or unsorted columns, it's hard to identify the offending duplicates. Maybe we should also have a search text dialog for the editor.

**Comment by gz** [comment]
Changing label and assigning @mihaibudiu since he already fixed and it's fixed by providing more detailed error information form the compiler
