### ISSUE TITLE
The `GEOMETRY` type breaks the data generator.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#634]
I declare a pipeline with a single table and no connector:

```sql
create table json_test (
    b BOOLEAN,
    i INTEGER,
    d DOUBLE,
    v VARCHAR(32),
    cc CHAR(16),
    t TIME,
    ts TIMESTAMP,
    dt DATE,
    gg GEOMETRY
);
```

When I run the pipeline, none of the data generation buttons work in the UI.  Removing the `GEOMETRY` column fixes the problem.

**Comment by gz** [comment]
it's not supported yet, probably breaks things because there is an assert that we throw when geometry is used.

To implement it, we need some input from @mihaibudiu on what `GEOMETRY` values look like

**Comment by ryzhyk** [comment]
Or just throw an "unsupported type" error

**Comment by mihaibudiu** [comment]
That's scheduled for 2025

**Comment by ryzhyk** [comment]
If we don't currently support any useful operations with this type, we should probably just remove it from the compiler and the docs.
