### ISSUE TITLE
Incorrect column name case sensitivity check in the compiler.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#636]
This [code](https://github.com/feldera/feldera/blob/5ff4b9c655105e33f3b6bbab7ce9053c7bf133f9/sql-to-dbsp-compiler/SQL-compiler/src/main/java/org/dbsp/sqlCompiler/compiler/backend/rust/ToRustHandleVisitor.java#L147) doesn't do what it is intended to. The `.append(field.sanitizedName.equals(field.name) ? "false" : "true")` line is supposed to determine whether column name is case-sensitive (i.e., declared with double quotes) but when I declare a column like this:
`create table foo("col" boolean);` it returns false.

**Comment by mihaibudiu** [comment]
This code does not detect whether the column name is case sensitive, it detects whether the column name is a legal Rust identifier.

**Comment by ryzhyk** [comment]
yes, and that's a bug

**Comment by mihaibudiu** [comment]
so it should be 'true' if either
- the column is case sensitive
- the original column name was not a legal Rust identifier, and thus has been renamed

**Comment by mihaibudiu** [comment]
In fact, "case-sensitive" is probably not a precise description.
Given our settings I will assume the first condition should be "name does contain characters that are not uppercase".

**Comment by mihaibudiu** [comment]
```
create table t1(c1 integer, "col" boolean, "SPACES INSIDE" CHAR)
```
output should be:
```
        deserialize_table_record!(TABLE["T1", 3] {
            (C1, "C1", false, Option<i32>, Some(None)),
            (col, "col", true, Option<bool>, Some(None)),
            (field, "SPACES INSIDE", true, Option<String>, Some(None))
        });
```

**Comment by ryzhyk** [comment]
This check is unrelated to whether column name is a valid Rust identifier. It only checks whether it's case sensitive, which I think is equivalent to whether it was specified with double quotes in SQL.

**Comment by ryzhyk** [comment]
> ```
> create table t1(c1 integer, "col" boolean, "SPACES INSIDE" CHAR)
> ```
> 
> output should be:
> 
> ```
>         deserialize_table_record!(TABLE["T1", 3] {
>             (C1, "C1", false, Option<i32>, Some(None)),
>             (col, "col", true, Option<bool>, Some(None)),
>             (field, "SPACES INSIDE", true, Option<String>, Some(None))
>         });
> ```

yep, this is correct.

**Comment by mihaibudiu** [comment]
If it's "COL" in SQL should it be 'true' or 'false'?

**Comment by ryzhyk** [comment]
But also 

```sql
create table t1(c1 integer, "COL" boolean, "SPACES INSIDE" CHAR)
```

output should be:

```rust
        deserialize_table_record!(TABLE["T1", 3] {
            (C1, "C1", false, Option<i32>, Some(None)),
            (col, "COL", true, Option<bool>, Some(None)),
            (field, "SPACES INSIDE", true, Option<String>, Some(None))
        });
```

**Comment by mihaibudiu** [comment]
Right now you'll get a 'false' for that combination, although it IS case sensitive.

**Comment by ryzhyk** [comment]
right, and that's not correct.

**Comment by mihaibudiu** [comment]
But you won't get that, you will get `(COL, "COL", false, ...)`

**Comment by mihaibudiu** [comment]
`create table t1(c1 integer, "col" boolean, "SPACES INSIDE" CHAR, "CC" CHAR)`
generates
```
        struct TABLE {
            C1: Option<i32>,
            col: Option<bool>,
            #[serde(rename="SPACES INSIDE")]
            field: Option<String>,
            CC: Option<String>,
        }
```
and
```
        deserialize_table_record!(TABLE["T1", 4] {
            (C1, "C1", false, Option<i32>, Some(None)),
            (col, "col", true, Option<bool>, Some(None)),
            (field, "SPACES INSIDE", true, Option<String>, Some(None)),
            (CC, "CC", false, Option<String>, Some(None))
        });
```

**Comment by mihaibudiu** [comment]
I generate legal Rust identifiers, not legal Clippy identifiers.
Is this solution adequate?

**Comment by ryzhyk** [comment]
This has nothing to do with Rust or clippy identifiers. This flag tells the deserializer whether it should expect the field name in JSON to match the column name in a case-sensitive or case-insensitive manner. There's a typo in my previous message. I want:

```
(COL, "COL", true, ...)
```

**Comment by mihaibudiu** [comment]
I guess we need to test whether we handle properly tables with column names like "col" and "COL".

**Comment by ryzhyk** [comment]
where
- `COL` is the name of the field in the Rust struct
- `"COL"` - column name, which must match the key in JSON.
- `true` - tell the deserializer to match the JSON key in a case-sensitive way, i.e., it must be exactly `"COL"` and not `"col"`

**Comment by mihaibudiu** [comment]
Postgres rejects this:
`CREATE TABLE T(COL CHAR, "col" CHAR)`

**Comment by mihaibudiu** [comment]
if we take this route then you can always do a case-insensitive comparison.

**Comment by ryzhyk** [comment]
Is the problem that it is difficult to extract from the compiler whether the column name is case sensitive?
The way I implement case-insensitive check is by converting JSON keys to upper case. I also assume that the case insensitive column name is given in upper case in the macro declaration.  Problem is that uppercase conversion may not be well defined for some unicode characters.

**Comment by mihaibudiu** [comment]
The problem of case-sensitivity is complicated.
You can configure calcite to process column names in various ways.
Our current configuration is for Calcite to normalize (uppercase) all non-quoted column names and leave the other ones unchanged. I think that's true for both declarations and uses. But we may change this behavior, I think different SQL dialects have different behaviors.
After this normalization, done in the front-end, the compiler doesn't worry about case anymore. Internally columns are referred just by their numeric indexes in the tuple.

**Comment by mihaibudiu** [comment]
Yes, uppercase depends really on the locale, which is not defined.
So you just want to know whether the column name was quoted?
If we don't know the locale then I don't see how you can even do case-insensitive comparisons.

**Comment by ryzhyk** [comment]
> So you just want to know whether the column name was quoted?
yes

**Comment by mihaibudiu** [comment]
I have submitted a different implementation. Here is the matching result:
```
create table t1(
                c1 integer,
                "col" boolean,
                "SPACES INSIDE CHAR,
                "CC" CHAR,
                "quoted "" with quote" CHAR,
                U&"d\\0061t\\0061" CHAR)
```

```
        deserialize_table_record!(TABLE["T1", 6] {
            (C1, "C1", false, Option<i32>, Some(None)),
            (col, "col", true, Option<bool>, Some(None)),
            (field, "SPACES INSIDE", true, Option<String>, Some(None)),
            (CC, "CC", true, Option<String>, Some(None)),
            (field_0, "quoted \" with quote", true, Option<String>, Some(None)),
            (data, "data", true, Option<String>, Some(None))
        });
```

**Comment by ryzhyk** [comment]
Yep, looks perfect.
