### ISSUE TITLE
Update copyright notices in the compiler. 

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#637]
Personally I would drop copyright headers in each file in favor of a single repository-wide LICENSE file (can they all be removed with some IDE magic?)  But if we keep them, they should reflect Feldera copyright.

**Comment by mihaibudiu** [comment]
We cannot remove the vmware copyright. All new files don't have one.

**Comment by ryzhyk** [comment]
We wouldn't be removing it, just keeping it in one place.

**Comment by mihaibudiu** [comment]
But then how do you know which files it applies to?

**Comment by ryzhyk** [comment]
All files in the repo

**Comment by mihaibudiu** [comment]
I don't know what to do about this, I think we should just close this issue

**Comment by ryzhyk** [comment]
I think we should implement my original suggestion: single LICENSE file, add Feldera copyright.

**Comment by mihaibudiu** [comment]
I don't think we are allowed to remove the copyright from the files we imported because of the original license.

**Comment by gz** [comment]
We should remove the copyright notice and just add them to a NOTICE file in the top-level project dir.

Also LICENSE is supposed to be just the MIT license text (no other copyright notices). This would also have the benefit of github correctly parsing our license and displaying it e.g., like here
![Screenshot from 2023-10-04 17-21-22](https://github.com/feldera/feldera/assets/127654/5fe55a40-812c-4ef2-ae7f-0122c5e844b6)

as opposed to what it does now for our repo

![Screenshot from 2023-10-04 17-22-19](https://github.com/feldera/feldera/assets/127654/95039432-5d88-4628-b481-9e02605f0d2e)

**Comment by lalithsuresh** [comment]
@ryzhyk @mihaibudiu I believe this issue was fixed right?

**Comment by mihaibudiu** [comment]
I didn't modify the copyright in the files that we got from the vmware repository
