### ISSUE TITLE
Compilation status doesn't get updated automatically

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#642]
If I open the `Pipelines` view while the program is compiling, the `COMPILING` status won't change until I refresh the page or switch to a different tab or different window.

I think this is also the case for the `Programs` tab.

Also, the `BUILDING PIPELINE` label in the `Programs` tabs should probably be renamed to `COMPILING`.

**Comment by Karakatiza666** [comment]
Fixed with https://github.com/feldera/feldera/pull/990
