### ISSUE TITLE
Deduplicated output for fault tolerance

### ISSUE THREAD

**Issue by blp** [feldera/feldera#655]
When a crash occurs with fault tolerance enabled, some or all workers might have produced some output for circuit steps that will be replayed on restart. Because we require circuits to be deterministic and [input to be reproducible](https://github.com/feldera/feldera/issues/652), this means that some of the same output will be produced again. We need the output implementation to discard this duplicate output.

The [output design](https://github.com/feldera/dist-design#output) is an abstract approach to this problem.

The concrete approach to this using the `dbsp_adapters` API might be to add the following method to `OutputEndpoint`:

```rust
type Step = u64;

trait OutputEndpoint {
    /// Notifies the output endpoint that data subsequently written by `push_buffer`
    /// belong to the given `step`.  If data for the given step has been written
    /// before, the endpoint should discard it up to the previously written length.
    /// Optionally, the endpoint may compare the previous version to the new version
    /// and log a warning if it differs.  Beyond the previously written length,
    /// the endpoint should append to it if `step` is the last step in the output,
    /// or log a warning if the output already contains steps beyond `step`.
    fn start_step(step: Step) -> AnyResult<()>;

    /// Notifies the output endpoint that it no longer needs to track the positions
    /// of steps before `step`.  It may optionally discard that tracking metadata.
    fn expire_step(step: Step);
}
```

**Comment by ryzhyk** [comment]
This makes sense. This should probably be a new trait that inherits `OutputEndpoint`, e.g.,:

```rust
trait ReliableOutputEndpoint: OutputEndpoint {
}
```

**Comment by blp** [comment]
This is complete, although there is no PR for it yet. I'm going to build in support in the pipeline manager next. I expect to submit durable input, output, and pipeline manager support in an upcoming PR.
