### ISSUE TITLE
Durable state for single-host fault tolerance

### ISSUE THREAD

**Issue by blp** [feldera/feldera#657]
For fault tolerance, we must maintain a durable copy of the state in each stateful operator, in the context of the [overall distributed design](https://github.com/feldera/dist-design#output). If we implement this copy as an online database, then it also allows DBSP to handle data larger than memory. The `persistence` (or "storage") feature already implements a prototype of such a database using `rocksdb` as the backend.

With a single host, fault tolerance adds only a few additional requirements beyond those for storage, a subset of those listed in the [database design](https://github.com/feldera/dist-design#database):

* Storage must persist from one run to another. This means that it needs to be on a durable device. It also probably requires some additional configuration or command-line parameters.
* Changes to storage must be transactional and only commit a transaction between steps (but it is not necessary to commit between every pair of steps, only as often as a desirable frequency for checkpointing).
* The database must offer some extra storage for key-value pairs related to the circuit rather than to some particular operator. The most obvious use is that the circuit needs to keep track of the current step number so that it can know where to start reading input on restart or recovery (the `get_step()`/`set_step()` operations). I bet that there will be others, too.

**Comment by gz** [comment]
>Storage must persist from one run to another. This means that it needs to be on a durable device. It also probably requires some additional configuration or command-line parameters.
- We probably need some way to name the indexes that we store (e.g., dbsp api can require names for traces, compiler might be able to generate these names so trace data can be re-used/found across pipeline restarts)

**Comment by blp** [comment]
I think we've got this done. There is plenty of refinement yet to do, some of which I'm going to file as new issues soon.
