### ISSUE TITLE
Run all SQL compiler tests in JIT mode

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#660]
The JIT compiler now has a standalone executable that takes the IR + JSON input data files and outputs query results as JSON.

- [x] Use this tool to run SQL compiler tests in JIT mode
  - [x] SLT tests
  - [x] Java-based tests
- [ ] Increase SQL compiler test coverage in CI by running all (or at least many more than now) tests in JIT mode.

**Comment by mihaibudiu** [comment]
Can you point me to the documentation that explains how to use it?

**Comment by ryzhyk** [comment]
In only have this link from @Kixiron 
https://github.com/feldera/feldera/blob/35527082ac5175500f70e6f9aa2ea6c6655cc1d7/crates/dataflow-jit/src/main.rs

@Kixiron , can you add `Usage` to the tool to document its inputs?

**Comment by mihaibudiu** [comment]
I am not sure what to do about the CI. Some Java tests are run in CI using the JIT.
SLT still takes too long.
