### ISSUE TITLE
[JIT] Support for the NULL type

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#67]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Fri Apr 14 22:58:04 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/373_

----

SQL supports the NULL type, which is the type of the NULL literal.
There is no way to represent this in the JIT compiler.
This is useful for example to cast NULL to various other types, as in the following program:
`SELECT T.COL4 || NULL FROM T`
Perhaps the compiler can eliminate this, but right now it doesn't.

**Comment by mihaibudiu** [comment]
So far the compiler has managed to eliminate all NULL types from realistic queries.
However, there are queries like SELECT NULL where the type of the result is the NULL type.
