### ISSUE TITLE
Unable to switch from view to table in breadcrumb navigation

### ISSUE THREAD

**Issue by gz** [feldera/feldera#672]
Going from view to view works, but not view to table in nav, see screencast:

[Screencast from 09-10-2023 07:35:01 PM.webm](https://github.com/feldera/feldera/assets/127654/469a4604-b8e7-4c9b-93e6-1c597c3214a8)

**Comment by ryzhyk** [comment]
I run into this with 0.1.7.

Steps to reproduce:
-  Follow part 1 of the Feldera Basics tutorial to create a "supply chain analytics" program and a pipeline without connectors for it.
- Start adding entries to `PART`, `PRICE`, `VENDOR` views manually.

I am often unable to switch between different tables or between tables and views in the breadcrumbs navigation.  Sometimes it takes several clicks, sometimes doesn't seem to work at all until I navigate to some other table or view and then try again.

In addition, switching from the `INSERT NEW ROWS` to the `BROWSE` view doesn't always work (it works eventually, but I need to click around a bit first).
