### ISSUE TITLE
Design for initial time series analytics support.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#677]
Come up with a detailed design, including:
- [ ] SQL Syntax to express lateness (and watermarks?), streaming joins, time windows. Assign semantics for these constructs, hopefully as lifted queries, no weird hybrid operators.
- [ ] Detailed implementation plan: data flow analysis, GC, new DBSP operators, etc.

**Comment by mohsinbeg** [comment]
> * SQL Syntax to express lateness (and watermarks?), streaming joins, time windows. Assign semantics for these constructs, hopefully as lifted queries, no weird hybrid operators.

Please also add a demo docs for these examples. For example, I see `lateness` https://www.feldera.com/docs/sql/grammar as per @mihaibudiu we don't support it beyond query parsing.

**Comment by ryzhyk** [comment]
This issue was too broad and vague.  We've started design work and will break it up into smaller, well-defined issue over time.
