### ISSUE TITLE
Experimental MySQL+Debezium setup

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#681]
Create a MySQL -> Debezium -> Redpanda -> Feldera pipeline using, e.g., this [tutorial](https://redpanda.com/blog/redpanda-debezium) and run it in CI.  Feldera will initially be dropping all data on the floor. This will be a starting point for the Debezium connector work as well as for adding Debezium support to Feldera cloud.

**Comment by mohsinbeg** [comment]
MySQL -> Fivetran [setup doc](https://fivetran.com/docs/databases/mysql/aurora-setup-guide).

**Comment by ryzhyk** [comment]
Closed via #771
