### ISSUE TITLE
relation dropdown only partly works

### ISSUE THREAD

**Issue by blp** [feldera/feldera#685]
In the web console, the "relation" dropdown only works for me when I click on some of the relations. For example, following along with the demo instructions [here](https://github.com/feldera/website/pull/254#pullrequestreview-1623198366), I see the following dropdown list:

![image](https://github.com/feldera/feldera/assets/613451/bc736c70-ad0e-4d75-ae30-0fac905c4a4c)

and selecting some of them make the view refresh properly (LPREFERRED_VENDOR) and selecting others does nothing (PART, PRICE, LOW_PRICE). Then, when LOW_PRICE is displayed, none of them do anything, except that if I select VENDOR twice, it refreshes. Sometimes selecting things twice makes a difference when another one is in the view too. I don't see an obvious pattern.

I'm using Firefox 117.

**Comment by gz** [comment]
duplicate of https://github.com/feldera/feldera/issues/672
