### ISSUE TITLE
Support case-(in)sensitive columns in JIT.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#691]
Most SQL column names are case-insensitive.  The exception are columns declared with double quotes.  We already support case-insensitive parsing in Rust.  We need to do the same in JIT:

We probaly want to add a per-column flag in `JsonDeserConfig` to indicate whether the column should be parsed in the case-sensitive or case-insensitive mode.

**Comment by Kixiron** [comment]
True case-insensitivity is fairly complicated and really inefficient, do we really need "true" case insensitivity for real applications or do we just need to accept a known subset of permutations?

**Comment by ryzhyk** [comment]
Fixed permutations won't cut it. But I think that comparing strings by converting them to uppercase is good enough.

**Comment by ryzhyk** [comment]
Reopening, because now all columns are case-insensitive. The intention was to have a per-column case sensitivity flag.

**Comment by ryzhyk** [comment]
Actually, this is good enough for now. Will create a new issue for a better JSON parser as discussed with @Kixiron .
