### ISSUE TITLE
[RFC] persistent user settings

### ISSUE THREAD

**Issue by gz** [feldera/feldera#698]
# Add User settings

## Problem

The WebConsole would benefit from a way to store user-settings in the backend.
Some examples where this is useful right now are:

- the user modifies the data table settings in the browser (hides a column
  from display, resizes a column, reorders a column etc.)
- user selects random generator settings for fields of a program
- user switches between dark/light mode

Right now these changes are either not persisted at all (e.g., a table goes back
in default settings on a reload), or persisted only in the browser local storage
(so if the users logs in from another browser he will have to configure
everything again).

I expect there will be more configurable settings in the future. And because the
frontend is all client side right now, we don't have a good way to store
per-tenant settings in durable form.

## Proposed implementation

We add a key--value store API in the pipeline-manager:

- a new table in SQL will be needed

```sql
create table user_settings (
    tenant_id uuid,
    key string,
    value string,
)
with primary key (tenant_id, key)
```

Plus the following REST API:

- get(tenant, key) -> value
- patch(tenant, key, value)
- del(tenant, key) (probably not needed, backend could just GC stale entries)

WebConsole would most likely store JSON objects as values and strings as keys.
The client using the API should treat it as best effort, and should not rely on
a key being stored there forever or at all (e.g., client is expected to
implement fallback mechanism).

## Alternatives approaches

- We currently solve this (for some use-cases) with the local-storage API in the
  browser: The downside of the current approach is that it is per-browser, so if
  I login from my laptop and desktop I don't have the same settings on both
  machines.
- We can also not do anything but this hurts user-experience. (e.g., the
  configured random settings for a given program will reset every time a new
  browser session starts)
- The WebConsole is no longer a static client-side only website but runs with
  it's own backend/DB (not a great option in my opinion).

## Open questions

-  I don't think we necessarily need to expose this in the public REST API
   surface of the manager, we could leave it as an (undocumented endpoint for
   now), but IMO it's also ok if we document/expose it.

**Comment by mohsinbeg** [comment]
This is part of /admin setting for user management. I suggest we store all admin settings as first class elements in a normalized data model in our postgresql db.

**Comment by gz** [comment]
please elaborate what is `part of /admin setting for user management`

**Comment by mohsinbeg** [comment]
There should All the system wide setting persisted across user sessions or for platform runtime; UI data table settings, kafka tuning, monitoring sinks, postgresql. etc. An ops users will need to view and make changes to all of them.

**Comment by gz** [comment]
> There should All the system wide setting persisted across user sessions

Don't disagree, but let's keep scope, this RFC the scope is on *user-specific settings/preferences* (things like the width of a row on a table that's displayed, or which theme light vs. dark is active etc.). So something where ops and dev user are happy to have different opinions but they won't have an impact on the pipeline.

How to share connector/Kafka settings/monitoring settings etc. for a pipeline among multiple tenants is important but needs another RFC.

**Comment by lalithsuresh** [comment]
> There should All the system wide setting persisted across user sessions or for platform runtime; UI data table settings, kafka tuning, monitoring sinks, postgresql. etc. An ops users will need to view and make changes to all of them.

I suggest we keep this out of scope for the next 3-6 months. Until we have precise requirements from some users, we can't start working on this.

**Comment by mihaibudiu** [comment]
Have to be careful, the user hides a column, then it's always hidden, they may forget that they did it.
This was a big problem in Hillview too, which we never solved. It is very important for usability.

**Comment by lalithsuresh** [comment]
Closing this as it's not the UI direction we're going.
