### ISSUE TITLE
[RFC] Binary releases

### ISSUE THREAD

**Issue by gz** [feldera/feldera#699]
We currently just have docker as a distribution/packing model. This RFC discusses adding binary releases that can run natively on the machine and don't require docker.

## Problem (with docker)

- Docker is blocked on some corporate networks (e.g., Docker Desktop is free for small businesses (fewer than 250 employees AND less than $10 million in annual revenue), personal use, education, and non-commercial open source projects. Otherwise, it requires a paid subscription for professional use.) which leads to problems for users wanting to try it out
- The downloads for our containers are very large, which isn't great for trying it out over wifi/slower networks 

## Proposed solution

We don't have that many components that we need to ship as a package in binary form:

- Pipeline manager: compiles to standalone binaries
  - Has only a few system dependencies like SSL stuff
  - We ship the webconsole as part of the rust binary
- The SQL compiler can be a standalone JAR
  - Will require JVM installation on the host (unfortunate, *might* be able to compile to native code too (e.g., with gcc for java backend))
  - Currently also needs rustc installed
- JIT is another standalone rust binary we need to package
  - But it will remove the rustc dependency we need on the host

We already generate these artifacts as binaries during CI. So for now, the idea would be to just package these (e.g., zip) and have it in downloadable form on github for the major architectures (e.g., linux/win/macos)

## Open questions

- Is it a good idea? Do we need it?
- After unpack a user won't have redpanda/postgresql by default, so needs some explanation in docs for adding these manually & experience won't quite be the same out of the box
- Some OSs may require signing the binaries (windows, macos) for a good experience, (but a developer will know how to work around this)

**Comment by mohsinbeg** [comment]
I suggest a docker sandbox in AWS Docker. A "launch sandbox" button that prompts for email id, opens a terminal window (make it look like bash, etc) and show the user the docker output. After 3 days the sandbox terminates.

**Comment by gz** [comment]
>I suggest a docker sandbox in AWS Docker. A "launch sandbox" button that prompts for email id, opens a terminal window (make it look like bash, etc) and show the user the docker output. After 3 days the sandbox terminates.

we should definitely have a sandbox, but seems like these would be separate RFCs

**Comment by lalithsuresh** [comment]
@gz at this stage, given the number of services involved, I'm not a fan of distributing binary releases. We'll need to test and make it work for:
* a matrix of dependency versions (libc, sasl, JVM, cargo etc -- because ultimately the pipelines need to build rust programs too)
* OSes (Linux distros, Mac OSX and Windows of varying versions). 

The archive will need a compiled binary + a Java application (the sql compiler) + the source files and rust crates needed by the SQL compiler. Sounds like too much effort for little return right now but we could revisit later.

**Comment by sorenbs** [comment]
You might look into building a native image for the SQL compiler using [Graal](https://www.graalvm.org/22.0/reference-manual/native-image/).

**Comment by lalithsuresh** [comment]
@sorenbs generating native images with Graal would certainly be useful.

**Comment by lalithsuresh** [comment]
Closing for now given this might not change soon and we have a sandbox.
