### ISSUE TITLE
Add case sensitivity flag to the JSON schema file output by the compiler.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#709]
Suggested format:

```json
      "name" : "UPDATE_DATE",
      "case_sensitive": true,
      "columntype" : {
        "type" : "TIMESTAMP",
        "nullable" : true,
        "precision" : 0
      }
```

If the flag is missing, the default is `false`.

**Comment by mihaibudiu** [comment]
I am not sure "cast_sensitive" is the right label.
How about "quoted"?

**Comment by ryzhyk** [comment]
Heh, let's call it `case_sensitive`.

I don't think `quoted` is better.  `case_sensitive` precisely captures the semantics.

**Comment by gz** [comment]
should we just make the sql not case sensitive by default?

prev discussion https://github.com/feldera/feldera/issues/154

**Comment by mihaibudiu** [comment]
It may not be possible in all dialects, and it may break user programs.
For example, column names with spaces may require quotes which cause them to be case-sensitive automatically.
(Calcite can override that, though.)
