### ISSUE TITLE
Support `add_input_set` and `add_input_map` operators.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#730]
DBSP now supports four types of input streams:
- input Z-sets (created with `circuit.add_input_zset()`)
- input indexed Z-sets (created with `circuit.add_input_indexed_zset`)
- input sets, which are different from Z-sets in that duplicate insertions and deletions are suppressed, so all elements have unit weights (created with `circuit.add_input_set`)
- input maps - key/value maps with upsert update semantics (created with `circuit.add_input_map`).

The IR currently supports the first two. We need to support the other two as well.  In fact, statically compiled circuits only use `add_input_set` today, but we plan to start using  `add_input_map` for collections with primary keys soon.

- [ ] Add two new node types and corresponding operators to the IR (@Kixiron )
- [ ] The SQL compiler should emit source nodes that correspond to sets (@mihaibudiu )

**Comment by mihaibudiu** [comment]
Can you be more explicit about what the code that needs to be generated by the compiler?

**Comment by ryzhyk** [comment]
More detailed implementation plan:

- [ ] New JIT compiler input nodes
  - [ ] Rename existing input node types: `Source` -> `SourceZSet`, `SourceMap` -> `SourceIndexedZSet` or some other choice of names that will distinguish these existing operators from the new operators (see below)
  - [ ] add `SourceSet` node type backed by `Circuit::add_input_set`
  - [ ] add `SourceMap` node type backed by `Circuit::add_input_map`
- [ ] JIT deserialization demands: deserialization demands for `SourceIndexedZSet` and `SourceMap` need to define schemas for both keys and values.
- [ ] JIT input handles: we currently only have `JsonZSetHandle`.  We need to add `JsonSetHandle`, `JsonIndexedZSetHandle` and `JsonMapHandle`. Corresponding APIs TBD.
- [ ] Catalog API: add `register_input_map` method to the static Rust API
- [ ] SQL compiler
  - [ ] Rust mode: call `Catalog::register_input_map` instead of `register_input_set` for tables with a primary key. 
  - [ ] JIT mode: For tables with primary keys, generate the `SourceMap` node instead of `SourceZSet` (which means the compiler will also need to create a layout for the key type).

**Comment by ryzhyk** [comment]
This is a subset of #772. Closing this one and moving the details to #772.
