### ISSUE TITLE
Consolidated pipeline view

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#731]
- [ ] Show pipeline designer and runtime state in the same page.  For now the pipeline designer is in the read-only mode when the pipeline is running. Later we will add a toggle between design and runtime modes.
- [ ] Also show SQL code in the same view. Did we decide we wanted it to be editable?
- [ ] Remove the "expand pipeline" chevron in the pipelines list.

@Karakatiza666 , please fill in any missing details.

**Comment by mohsinbeg** [comment]
@Karakatiza666 what milestone version is this scheduled for?

**Comment by ryzhyk** [comment]
None yet. I think it will be 0.1.5 or 0.1.6, but we haven't planned those out yet.

**Comment by lalithsuresh** [comment]
Addressed by new UI
