### ISSUE TITLE
Shutdown all connectors before terminating the pipeline.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#753]
We currently shutdown the pipeline server without waiting for all connectors to cleanly shutdown (we send a termination notification to them, but there is not mechanism to wait for a connector to be done).  This seems to cause problems with Kafka where unclean consumer shutdown seems to cause timeouts in Kafka's membership protocol.

The problem is getting worse with the introduction of JIT-compiled circuits, which add a new safety requirement that no handles to JIT'd code should exist after the circuit terminates.

The solution to both problems is to add a mechanism to synchronously wait for connectors to shutdown before terminating the circuit.

**Comment by mihaibudiu** [comment]
I thought we are doing ROC, where there is no clean shutdown.
Expecting there to have one is a recipe for failure in uncommon cases.

**Comment by ryzhyk** [comment]
ROC or not, I want to avoid undefined behaviors in my code.
