### ISSUE TITLE
[JIT] Program with SELECT DISTINCT produces duplicated records

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#763]

**Comment by mihaibudiu** [comment]
I am attaching the files reproducing the bug.

**Comment by mihaibudiu** [comment]
[test.zip](https://github.com/feldera/feldera/files/12704978/test.zip)

**Comment by mihaibudiu** [comment]
The program is SELECT DISTINCT `COL0` + - `COL0` + 82 FROM `TAB2. The last operator before Sink is StreamDistinct. But the output produced looks like this:
```
{"data":{"EXPR$0":82},"weight":1}
{"data":{"EXPR$0":82},"weight":1}
```

**Comment by mihaibudiu** [comment]
After rebasing I can't reproduce this issue anymore.

**Comment by mihaibudiu** [comment]
I am reopening this issue because I have another test case with the same symptoms.

**Comment by mihaibudiu** [comment]
This is the output from a program that ends in a SELECT DISTINCT:
```
{"data":{"COL1":null,"COL2":-70},"weight":1}
{"data":{"COL1":null,"COL2":-70},"weight":1}
{"data":{"COL1":null,"COL2":-70},"weight":1}
```

**Comment by mihaibudiu** [comment]
[test.zip](https://github.com/feldera/feldera/files/12720937/test.zip)

**Comment by mihaibudiu** [comment]
I am still seeing this bug. Am I doing something wrong?
There isn't a test for this case in #799

**Comment by mihaibudiu** [comment]
I am reopening this issue, I have another test case that fails.
It's clearly a JIT bug, since the last stage before output is a StreamDistinct, and the output looks like this:
```
{"data":{"COL2":-77},"weight":1}
{"data":{"COL2":-748},"weight":1}
{"data":{"COL2":-924},"weight":1}
{"data":{"COL2":-77},"weight":1}
{"data":{"COL2":-748},"weight":1}
{"data":{"COL2":-924},"weight":1}
{"data":{"COL2":-77},"weight":1}
{"data":{"COL2":-748},"weight":1}
{"data":{"COL2":-924},"weight":1}
```
I will attach a zip with the reproduction.

**Comment by mihaibudiu** [comment]
[bug.zip](https://github.com/feldera/feldera/files/12824845/bug.zip)

**Comment by ryzhyk** [comment]
Moving to the next milestone. @mihaibudiu need to test the fix.

**Comment by ryzhyk** [comment]
@mihaibudiu , can we close this?
