### ISSUE TITLE
Add confirmation dialog to all delete icons

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#766]
Currently I can delete a pipeline without a prompt and all my work and mapping is gone. Same for SQL Program. I was giving a demo and clicked delete by mistake and the pipeline was gone. Containers had to be restarted. 

In fact, a better option would be put a deleted entity in a trash folder to allow restore if needed.

**Comment by ryzhyk** [comment]
Same for connectors.  A trash folder is a good idea, but I suggest we start with the minimal thing -- a confirm deletion dialog.
