### ISSUE TITLE
Report number of parsing errors per connector.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#776]
The `/stats` endpoint already reports the number of parse errors per connector. We need to show this number in the UI:
- [ ] In the expanded pipeline view where we show the list of connectors with per-connector stats (# of records, # of bytes, etc)
- [ ] In the active pipeline list on the homepage

Once we have an integrated pipeline view, we may want to show per-connector stats in the pipeline builder on each connector block.

Note: this issue doesn't include a mechanism to view detailed parsing errors.  The user still needs to look at the log for that.

**Comment by Karakatiza666** [comment]
![image](https://github.com/feldera/feldera/assets/8537259/ed205688-7e0a-49e9-b5a4-240ef73c6365)
(Comma separates thousands)
