### ISSUE TITLE
RocksDB Wide Column prototype

### ISSUE THREAD

**Issue by gz** [feldera/feldera#778]
- Build a rocksdb storage prototype that stores values using wide columns 
- Evaluate it by running a subset of (slow) nexmark queries

**Comment by ryzhyk** [comment]
@gz , can you briefly explain how this will work?

**Comment by gz** [comment]
Won't explore this, based on findings in https://github.com/feldera/feldera/issues/777 and what I posted on slack I highly doubt this will move the needle for us
