### ISSUE TITLE
Custom storage prototype (with proper alignment)

### ISSUE THREAD

**Issue by gz** [feldera/feldera#779]
- Build  storage prototype that repurposes the LSM /DRAM spine implementation and stores columnar data in a custom rkyv friendly format which allows for 0-copy deserialization
- Evaluate it by running a subset of (slow) nexmark queries

This will establish a better upper bound on what we could get from something (not rocksdb) that doesn't have the issue with alignment and isn't bogged down by column families

**Comment by blp** [comment]
A big part of the storage prototype is ready for review: https://github.com/feldera/feldera/pull/1250

**Comment by blp** [comment]
PR #1250 was merged.
