### ISSUE TITLE
custom webconsole 404 page not displaying

### ISSUE THREAD

**Issue by gz** [feldera/feldera#785]
e.g., this may be a regression from the routing PR?

![Screenshot from 2023-09-25 16-15-39](https://github.com/feldera/feldera/assets/127654/96c0b54e-4e2a-4c98-a0b9-d9589aac00ed)

**Comment by Karakatiza666** [comment]
This is one symptom of an issue I notice when web-console is served with pipeline manager. Will need to dig into this
