### ISSUE TITLE
Storage control plane and configuration

### ISSUE THREAD

**Issue by blp** [feldera/feldera#814]
For fault tolerance (single- or multi-host) we need persistent storage (see issues #527 and #658).

Storage needs to be separate per worker thread. A single database (etc.) could hold the storage for multiple worker threads, as long as it kept their data separated.

# Control Plane

Each trace must have an interface that gives it access to storage. The [circuit cache](https://docs.rs/dbsp/latest/dbsp/circuit/circuit_builder/trait.Circuit.html#tymethod.cache_get_or_insert_with) could keep a storage handle for access by traces. Traces would use this interface to create, read, and write storage.

The control plane would provide an interface for use by code outside the circuit, e.g. for:
- Verifying that the running program is compatible with the one that produced the storage
- Tracking the "step number" that the storage corresponds to
- Committing a transaction
- For multi-host fault tolerance, tracking the database version (issue #658)

The first two items above could be satisfied by having the storage control plane provide a key-value pair read/write interface.

# Configuration

Persistent storage needs configuration:
- The location for where the storage is to live (a directory path, URL, or some other locator)
- Maybe some tuning knobs.

Maybe configuration becomes part of the command-line interface for the circuit server program.

**Comment by lalithsuresh** [comment]
It'll be one configuration for the entire pipeline I assume?

**Comment by blp** [comment]
> It'll be one configuration for the entire pipeline I assume?

Yes. In a multi-host setup, though, if the hosts are heterogeneous, maybe they'd have different paths to storage, etc. Since we're using containers, I guess our hosts will be homogeneous.

**Comment by blp** [comment]
I think that @gz has implemented this, at least in a branch waiting for the dbsp crate to unfreeze.

**Comment by blp** [comment]
I believe that this is complete for now, although it's pretty basic at the moment.
