### ISSUE TITLE
Refactor away @iconify/react

### ISSUE THREAD

**Issue by Karakatiza666** [feldera/feldera#817]
As per discussion https://github.com/iconify/iconify/issues/255, @iconify/react is not a suitable solution in this project. It needs to be replaced either with multiple components for respective icon sets, or with a more suitable solution like https://github.com/unplugin/unplugin-icons

**Comment by gz** [comment]
It would be good if the new plugin would serve the icons from our own bundle/build and not issue network requests to a remote entity so the website works also in environments without internet connectivity

**Comment by Karakatiza666** [comment]
Part of https://github.com/feldera/feldera/issues/865
