### ISSUE TITLE
Metrics/basic profiling

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#83]
- [ ] API to expose operator graph and sample resource usage of each operator (CPU, size, memory). We already have low-level support for this, but no high-level API.  We may want to use smth like `metrics-rs` to get a rich set of statistics.
- [ ] UI to visualize all this.
- [ ] SQL compiler integration to correlate DBSP operators with SQL statements.

**Comment by lalithsuresh** [comment]
@gz @ryzhyk I'd say we can close this given recent work on tracing and profiling?

**Comment by gz** [comment]
think
so
