### ISSUE TITLE
[SQL] Implement value numbering in the JIT compiler

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#833]
Value numbering is a simple algorithm for common-subexpression elimination.
Turns out that Calcite cannot do that since it does not have temporaries that can store intermediate results.
So the code generated has lots of redundancies, even within the same basic block.

**Comment by Kixiron** [comment]
This is done to a smaller extent within the JIT compiler already, I just haven't implemented a more comprehensive version yet. I've got some pretty aggressive optimizations planned so I'm happy taking this

**Comment by mihaibudiu** [comment]
This has already been implemented in the Java SQL compiler, per basic block only.
