### ISSUE TITLE
UI should require group ID to be specified for Kafka connectors

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#840]
* UI allows creating Kafka connectors without specifying a group-id, which should not be allowed. Because creating a pipeline like this fails during deployment time ("Subscription error Local: unknown group").

* There is no way to copy error messages from failed pipelines, as it is only displayed during mouse hover. This makes it hard to report bugs.

**Comment by gz** [comment]
Hm from https://issues.apache.org/jira/browse/KAFKA-6774 it reads like an empty string is a valid group id? 
So that would be a valid configuration for some kafka deployments
