### ISSUE TITLE
Bugs in SSL form for Kafka connector

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#841]
The input forms when configuring SSL for a Kafka connector interfere with the actual content being passed.

Certificates are sensitive to new lines. Currently, the `ca.pem` field for example is a single-line form for a multi-line input. Same with the others.

Passing a certificate as is with newlines causes the newlines to be parsed as spaces as per the object I see in the DB.

Explicitly representing the certificate in a single line using "\n" doesn't work either, because the UI seems to convert "\n" into "\\n", also leading to malformed certificates.

**Comment by ryzhyk** [comment]
I think the solution is to convert all `.pem` settings to multi-line text fields in the form.

**Comment by gz** [comment]
The .pem form should probably just be a file upload form where the pem file can be added by the user (it can be read to a string on the client during form submit in JS and then sent as part of JSON)

**Comment by lalithsuresh** [comment]
The correct way to handle this is to support secrets, which can be made available to the pipeline at a known mount point. Right now, we store all of this as-is in the DB which is unsafe.

**Comment by ryzhyk** [comment]
I'm not sure why secrets are relevant in this particular case. Certificates are usually not secrets.

**Comment by ryzhyk** [comment]
File upload makes sense but I think a pem file can contain an entire certificate chain, but Kafka wants just one certificate or public key in these fields. In this case being able to paste just one certificate seems like the right thing to do.

**Comment by gz** [comment]
>but I think a pem file can contain an entire certificate chain, but Kafka wants just one certificate or public key in these fields

we should be able to parse&extract the right set of bits from the file

**Comment by ryzhyk** [comment]
Sure, or we can keep it simple and just have the use paste the right cert :)

**Comment by lalithsuresh** [comment]
The advantage to using secrets here is that it becomes much easier to rotate the keys/certificates via standard cluster manager mechanisms. All our control plane will maintain will be references to the secrets, which will stay the same.

**Comment by ryzhyk** [comment]
Fair enough, but I think that's complimentary. We need both secret management and a correctly working form for pasting certificates manually.
