### ISSUE TITLE
Kafka output connector busy-waits in connect()

### ISSUE THREAD

**Issue by blp** [feldera/feldera#842]
It looks to me like [the `loop` in `connect` for KafkaOutputEndpoint](https://github.com/feldera/feldera/blob/f57d71f283d4105691384a78069c9becce8e4f1a/crates/adapters/src/transport/kafka/output.rs#L331-L352) is a busy-wait loop. I didn't test it, I just noticed this while reading code.

**Comment by ryzhyk** [comment]
Yep, looks like I forgot to add a `sleep()` in that loop. Will fix it.
