### ISSUE TITLE
WebConsole should use bigint for types with >=64 bits

### ISSUE THREAD

**Issue by gz** [feldera/feldera#851]
In the data-viewer and for inserts we serialize/deserialize integers with the regular browser included json parser code. This causes issues as it uses the javascript number type for integers which is a 64-bit float. We should be able to fully represent 64-bit integers from feldera cap as BigInts in javascript. We don't want to loose precision when displaying/sending data to/from the backend.

e.g., JSON serialize/deserialize may be able to use this: https://www.npmjs.com/package/json-with-bigint

**Comment by Karakatiza666** [comment]
@gz what do you think about using [BSON](https://en.wikipedia.org/wiki/BSON) as a data transfer format? Apart from bigint, it has native support for more types, encodes length of data elements and has other properties (e.g. ability to lazily traverse the object structure without parsing it first) that might come useful elsewhere in the project.

**Comment by gz** [comment]
Few thoughts:

- JSON as a format is fine (it doesn't constrain the precision of the numbers) so the issue is purely a javascript language problem
- BSON is a new format, it will need backend+connector+JIT integration (plus future maintenance and support for it, if we decide to introduce it), so essentially a lot of extra work for fixing this particular (javascript language) problem
- While I do like binary formats, I'm not sure it's the best options for the Web UI: e.g., the UI isn't performance critical for data-shipping, but BSON makes future debugging harder: you will always see binary data for all outgoing network requests, harder to understand what's going on etc.
- The problem of getting BSON data and then converting it not into a `number` but a `bigint` type still needs support from whatever JS library you're using to parse BSON so this isn't different from using a different JSON parser library

**Comment by Karakatiza666** [comment]
You are right, loss of 64-bit integer precision by JS is not a JSON format limitation, and good points otherwise.
In that case I lean towards a library that doesn't add nor require an `n` suffix to convert bigints, let's see if we encounter consistency issues in usage (e.g. having 123n::bigint converted to `123` in JSON and back to 123::number)
