### ISSUE TITLE
WebConsole should allow attaching output connectors to input tables.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#872]
The API allows attaching output connectors to input tables. The way this works is that, for debugging purposes, we already attach output handles to all input stream, so there is an output stream with the same name for each input stream. This allows us to implement pass-through tables without writing silly views like:

```sql
create view output_view as select * from input_table;
```

The WebConsole currently doesn't support this and will throw an error when it encounters an output connector attached to an input table.  I'm not sure what the UI for attaching connector arrows to input tables should look like. Happy to brainstorm.

**Comment by gz** [comment]
I'd do smth like this, but we can discuss more

![increment(1)](https://github.com/feldera/feldera/assets/127654/af591cca-2a8b-4a2c-b82e-31753017720b)

**Comment by lalithsuresh** [comment]
No longer applies with the new web console
