### ISSUE TITLE
Consistent naming of collection data types

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#885]
We have a menagerie of types of sets: ZSets, IndexedZSets, Maps, Sets, which mean different things in different contexts.
For example, in the JIT you can describe inputs as:
```
layout=Set, kind=ZSet  - normal ZSet
layout=Set, kind=Upsert  - Set
layout=Map, kind=ZSet  - indexed ZSet
layout=Map, kind=Upsert  - Map
```
We should unify the naming and document it.
I favor using Z for collection names, since the other words are already highly overloaded.

**Comment by ryzhyk** [comment]
Do you have a preferred naming for these four things?

**Comment by mihaibudiu** [comment]
Moreover, all compilers and runtimes should use the same names.
