### ISSUE TITLE
[JIT] The JIT facade does not support the newly defined Map input operators

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#890]
I am attaching a zip file for a program that I would like to run using `cargo run -p dataflow-jit`.

**Comment by mihaibudiu** [comment]
[bug.zip](https://github.com/feldera/feldera/files/12922895/bug.zip)

**Comment by ryzhyk** [comment]
@mihaibudiu , can we close this?

**Comment by mihaibudiu** [comment]
I haven't tested this yet.

**Comment by mihaibudiu** [comment]
Will have to try #891
