### ISSUE TITLE
[JIT] unsupported operations on decimal values

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/feldera#896]
Here is a partial list of operations that the JIT does not support on decimal values.
Arguably, some of them should not be supported at all for decimals, since they are inexact, and perhaps the argument should be cast to a double instead. But some make perfect sense: abs, round, log, ln, power, log10, sqrt.
All of these functions are already implemented in the Rust runtime library. It would be nice to avoid duplicating this effort.

**Comment by thaodt** [comment]
hi @mihaibudiu @Kixiron can I take this issue if you haven't implemented it yet?

**Comment by Kixiron** [comment]
I've already mostly implemented it, don't worry about it

**Comment by mihaibudiu** [comment]
We very much appreciate the offer.

The truth is that we still have lots of functions to implement in the JIT. 
Currently we have two back-ends: a pure rust one, and the JIT. We have lots of SQL functions to implement in both of them.

The Rust backend is a bit ahead. The functions are based on the SQL functions described here https://calcite.apache.org/docs/reference.html, and currently their definitions are in https://github.com/feldera/feldera/tree/main/sql-to-dbsp-compiler/lib, but we still need to implement many more.

The JIT so far has been reimplementing these functions, but we need to devise a scheme to reuse the existing implementations. Unfortunately I think the JIT does not always use the same representations for the datatypes as the Rust backend does, so it's not clear how to do this. But if you want to contribute there should be plenty of stuff to do.

**Comment by mihaibudiu** [comment]
There's also #913 for example

**Comment by thaodt** [comment]
> We very much appreciate the offer.
> 
> The truth is that we still have lots of functions to implement in the JIT. Currently we have two back-ends: a pure rust one, and the JIT. We have lots of SQL functions to implement in both of them.
> 
> The Rust backend is a bit ahead. The functions are based on the SQL functions described here https://calcite.apache.org/docs/reference.html, and currently their definitions are in https://github.com/feldera/feldera/tree/main/sql-to-dbsp-compiler/lib, but we still need to implement many more.
> 
> The JIT so far has been reimplementing these functions, but we need to devise a scheme to reuse the existing implementations. Unfortunately I think the JIT does not always use the same representations for the datatypes as the Rust backend does, so it's not clear how to do this. But if you want to contribute there should be plenty of stuff to do.

Got your points. Let me check your reference and our codebase before I come back here to discuss more.
