### ISSUE TITLE
Do another pass on pipeline compilation dependencies

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#905]
I just noticed we pull in the JIT on every pipeline build, which slows down the compiler-server and/or bloats the container image size (depending on whether we precompile during image creation time, or compile on-site). 

It's worth doing another pass to minimize the dependencies used to build pipelines by the compiler server.

**Comment by ryzhyk** [comment]
- [ ] feature-gate JIT (it's only needed to build the standalone binary)

**Comment by ryzhyk** [comment]
Should be solved in #945.  I still see 12 duplicate dependencies in `cargo tree` (two versions of the same crate), but I don't see a good solution, since these dependencies are pulled in by other dependencies, mostly `actix`.
