### ISSUE TITLE
Compiling programs are shown with "building pipeline" status in the UI

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#906]
When compiling a program that isn't yet attached to a pipeline, we still see the status shown as "building pipeline" in the programs view.

**Comment by gz** [comment]
What would be a text/label that you feel is better? e.g., "Building Binary", "Compiling Binary" are some options I can think of

**Comment by lalithsuresh** [comment]
The confusing part is pipeline, because the message appears even when there are no pipelines associated with the program.

"Building binary" sounds good to me.

**Comment by Karakatiza666** [comment]
Fixed with https://github.com/feldera/feldera/commit/61f941c6e897948e125657663a8aa2c60088ef1e
