### ISSUE TITLE
Aggregates without explicit names show up with compiler-internal generated names in the UI

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#908]
With a view like

```
CREATE VIEW product_counts AS
SELECT count(*) FROM products;
```

The UI shows a generated name that looks like this when clicking the eye for this view:

![image](https://github.com/feldera/feldera/assets/434651/458e63fd-c54c-41cd-b408-5efa6f2b4195)

Also related, the panel suggests the view is not outputting any records, when that's not the case. I assume this has to do with the generated name as well.

![image](https://github.com/feldera/feldera/assets/434651/f98db8ac-ddeb-45cc-a1ce-08e6ed26052e)

**Comment by mihaibudiu** [comment]
EXPR$0 is the internal name used by Calcite to name this column.

**Comment by gz** [comment]
>the panel suggests the view is not outputting any records

This is because it doesn't have an output attached (then we don't count this in the backend -- I believe)

**Comment by gz** [comment]
re sql I think the workaround is smth like this:

```
CREATE VIEW product_counts AS
SELECT count(*) as counts FROM products;
```

**Comment by gz** [comment]
I don't think these two are webconsole issues fwiw (e.g., the sql names needs better names form the compiler if that's possible at all, the other needs backend/API change)

**Comment by lalithsuresh** [comment]
> re sql I think the workaround is smth like this:
> 
> ```
> CREATE VIEW product_counts AS
> SELECT count(*) as counts FROM products;
> ```

I'm familiar with the workaround. In typical SQL databases, you'd get a more human-friendly name like "count(*)" instead of expr$0.

**Comment by ryzhyk** [comment]
This is what Calcite generates. I don't know if we have any control over it.

**Comment by ryzhyk** [comment]
The second issue is completely separate. As @gz  said, it's a known issue.  But we do need to fix it at some point.  It requires backend support.

**Comment by mihaibudiu** [comment]
I will close this one as well, since it's a Calcite problem that we cannot solve.
