### ISSUE TITLE
Show the stream of changes in data browser.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#921]
Add the third tab to the data browser to visualize the raw stream of changes to the table or view.

The output should look like an append-only log of inserts and deletes. The browser should keep a bounded-length suffix of the log and allow the user to scroll through this suffix.

A fast-changing view can produce updates faster than the browser can visualize them, in which case the browser will miss some updates.  The browser can detect that some data has been lost by tracking sequence numbers in the JSON chunks and show an indication in the log, e.g., `[skipped 3 data chunks]`.

**Comment by mihaibudiu** [comment]
There should be a "pause view" button

**Comment by ryzhyk** [comment]
I wanted to suggest that, but then thought that but then thought that scrolling the view should have that affect.  I think @mihaibudiu  is correct, an explicit pause button is useful

**Comment by lalithsuresh** [comment]
New web console has a change stream menu.
