### ISSUE TITLE
Restarting Docker causes changes and failures in pipeline(s)

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#924]
1. Start docker desktop
2. Go to `Pipelines`
3. Click `Start Pipeline` button for `SecOps Pipeline`
4. Shutdown docker desktop without clicking `Shutdown Pipeline`
5. Retart docker desktop
6. Go to `Pipelines`
7. `SecOps Pipeline` shows CHANGES:`Modified (44)` and with STATUS:`Failure`

It's not obvious why there are changes or failures since no config or sql program edits were done.

<kbd>![image](https://github.com/feldera/feldera/assets/28739668/1a1f84fd-17e7-40fc-924f-56dc000394de)</kbd>
<kbd>![image](https://github.com/feldera/feldera/assets/28739668/7cd48093-a7a0-4709-89f5-b2ea994d2073)</kbd>

**Comment by lalithsuresh** [comment]
@mohsinbeg the status is failure because the pipeline indeed failed (as a result of the docker container being killed).

Regarding changes showing up: my guess is that the connector inputs show up in a different order on the left than on the right, and the diff-ing is order sensitive (@gz).

**Comment by mohsinbeg** [comment]
> @mohsinbeg the status is failure because the pipeline indeed failed (as a result of the docker container being killed).

Docker stop should be sending a SIGTERM to the main process pid (1). I assume we can trap that and do a pipeline shutdown. I went to pipeline again after a few mins and now see STATUS:`INACTIVE` and STATUS:`FAILURE` is no longer there. See screenshot below.

<kbd>![image](https://github.com/feldera/feldera/assets/28739668/0cedcbbe-27a4-43ff-9970-b09342226b67)>/kbd>

**Comment by gz** [comment]
the config returned from the api should have a well defined order to avoid this scenario. maybe its a regression or another way this could happen is if connectors get recreated on docker startup m with a random name (then it would have a diff)

**Comment by ryzhyk** [comment]
One of the containers being restarted is the demo container, which recreates the demos. It probably generates new uuid's and ends up with a different config.

**Comment by lalithsuresh** [comment]
This has been fixed.
