### ISSUE TITLE
Table editor error

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#934]
- Create a pipeline without connectors
- Start the pipeline
- Open the INSERT ROWS view on any input table
- Add some rows, _DON'T_ press "Insert rows"
- Try to navigate to a different table in bread crumbs.  The following error shows up

![image](https://github.com/feldera/feldera/assets/8323135/415f923d-4d98-4b1d-aa54-dd781d9d3ae2)

**Comment by mihaibudiu** [comment]
Is this resolved?

**Comment by ryzhyk** [comment]
No longer applicable in the new WebConsole
