### ISSUE TITLE
Docker demo containers do not always stop

### ISSUE THREAD

**Issue by snkas** [feldera/feldera#937]
Sometimes after ending the docker-compose demo with Ctrl-C, the containers themselves continue to run in the background where as they should have stopped.

**Comment by lalithsuresh** [comment]
Which containers do you see running? All of them or only a subset? Is the same subset usually?

**Comment by snkas** [comment]
All four:
- ghcr.io/feldera/demo-container:0.2.0
- ghcr.io/feldera/pipeline-manager:0.2.0
- postgres
- docker.redpanda.com/vectorized/redpanda:v23.2.3

**Comment by lalithsuresh** [comment]
When I ctrl-c, Docker starts to stop the containers which can take up to 10 seconds (the shutdown grace period). If you ctrl-c again it interrupts that process which could leave containers running.

Could you confirm if that's the behavior you see?

**Comment by snkas** [comment]
It is not always the case that Ctrl-C just exists the process without cleanup. Now I also consistently get:

```
Gracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 4/4
 ✔ Container downloads-demo-1              Stopped                                                                                                                                               0.0s 
 ✔ Container downloads-pipeline-manager-1  Stopped                                                                                                                                               0.0s 
 ✔ Container downloads-redpanda-1          Stopped                                                                                                                                               0.9s 
 ✔ Container downloads-db-1                Stopped                                                                                                                                               0.3s 
canceled
```

Unsure what is the determining factor whether the Ctrl-C is caught or not.

**Comment by snkas** [comment]
They also don't stop when I close the terminal by clicking the X in the top right.
Command to end all running docker containers: `docker kill $(docker ps -q)`

**Comment by lalithsuresh** [comment]
This hasn't been seen in a while. Closing for now.
