### ISSUE TITLE
WebConsole: allow pipeline configuration and monitoring

### ISSUE THREAD

**Issue by lalithsuresh** [feldera/feldera#939]
We currently do not expose a way to configure some key properties of a pipeline, and produce a PipelineConfig entry with defaults.

We'll need the ability to set and monitor some values of a PipelineConfig object from the UI:
* `workers`
* `resource limits/reservations`: https://github.com/feldera/feldera/pull/940

**Comment by gz** [comment]
@Karakatiza666 I made this part of next milestone in discussion with @lalithsuresh earlier because he's dependent on it

**Comment by Karakatiza666** [comment]
@lalithsuresh is there an API endpoint for applying these settings? I have generated bindings for API ver 0.3.2, but don't see an endpoint to set `workers` number and `ResourceConfig`

**Comment by lalithsuresh** [comment]
Blocked by https://github.com/feldera/feldera/issues/1106 and https://github.com/feldera/feldera/issues/1104
