### ISSUE TITLE
Design for UDFs.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#944]
We need a mechanism to implement both built-in SQL functions and user-defined functions as Rust/C/Wasm libraries.  Step 1 is to write a design document for that.  The design should address the following questions:

- [ ] Syntax to specify function signatures
- [ ] Tooling to generate C/Rust prototypes from these signatures.
- [ ] Calling convention (including mappings between SQL/Rust/C types)
- [ ] Linking model (how are the UDFs loaded into the pipeline process)
- [ ] One additional requirement is that there should be a way to implement the UDF once and use them in both statically compiled and JIT-compiled code.
- [ ] Implementation plan: what will it take to extend JIT and the Rust toolchain to implement this model?
- [ ] Performance considerations
- [ ] Think through fault isolation, especially for functions that are not part of the SQL language (i.e., proper UDFs). See comment by @gz below

What did I miss?

**Comment by mihaibudiu** [comment]
I have thought about this. I think that all udfs should return Result. This will enable us to report runtime errors properly. This will require changing the rust backend too.

**Comment by gz** [comment]
maybe some of this is helpful:

https://www.usenix.org/conference/osdi18/presentation/kulkarni
https://www.usenix.org/conference/osdi22/presentation/zhong
https://dl.acm.org/doi/abs/10.1145/3477113.3487272
https://www.usenix.org/conference/osdi20/presentation/narayanan-vikram

**Comment by ryzhyk** [comment]
@gz, are you saying we should add isolation to the list of requirements, to make sure a UDF cannot corrupt the state of the pipeline? That makes sense.

**Comment by gz** [comment]
Ah yea I didn't realize it wasn't part of the requirements before
