### ISSUE TITLE
Optimize Kafka adapter to handle small (and large) messages efficiently

### ISSUE THREAD

**Issue by ryzhyk** [feldera/feldera#964]
I found that the current Kafka input connector is inefficient in processing small messages. This is an issue because common guidelines for using Kafka recommend small messages. The easiest solution might be to switch from pushing one Kafka message at a time from the Kafka connector to the parser to batching multiple messages when there's more than one available from the Kafka consumer.  In addition, we should look more closely into per-buffer overheads in our input chain.

**Comment by blp** [comment]
@ryzhyk Do you have a test workload in mind?

**Comment by ryzhyk** [comment]
@blp , not yet in this repo. Will try to add another demo in the next few days where batching multiple updates in one Kafka message improves Feldera throughput 5x. Haven't profiled it in detail, so not sure where exactly the overhead is.

**Comment by blp** [comment]
Do we have a race in our accounting for input data? A casual reading of the controller code suggests that, by default, we do something like this:

1. Wait for some input data to arrive (there are min batch size and max delay knobs but by default they are both zero).
2. Zero input counters (by calling `controller.status.consume_buffered_inputs()`).
3. Run the circuit.

If data arrives between steps 1 and 2, I think it might just get ignored in our accounting, so that it ends up like this:

0. Input connector pushes small record number 1.
1. Wait for some input data to arrive.
1.5. Input connector pushes small record numbers 2 and 3.
3. Zero input counters (by calling `controller.status.consume_buffered_inputs()`).
4. Run the circuit.
5. Wait for some input data to arrive, but our counters say zero so we wait for something new, which might take a while.

Maybe something prevents this, I will look closer.

**Comment by blp** [comment]
> Maybe something prevents this, I will look closer.

Hmm, but in this case records 2 and 3 should end up in the current batch anyway. Normally, anyhow. I guess there might be a small race but probably not big enough to explain bad throughput in the common case.

**Comment by ryzhyk** [comment]
I think there is a race condition, but it's a benign one: `consume_buffered_inputs` can account for fewer records than what actually gets ingested in the next line, so the controller will wake up again even though the buffers are empty.

**Comment by blp** [comment]
Kafka input adapter performance needs work for large messages too: the e2e benchmark currently uses 512 kB messages and its input performance is not good. I'm going to add this to the next sprint.

**Comment by blp** [comment]
I've been experimenting with different Kafka topic configurations and message sizes.

Here are the times I got for reading 92,000,000 records (lines) that amount to 1.6 GB when I divided them up into records of different sizes and different numbers of partitions, using both a simple Rust program based on [`rdkafka`](https://docs.rs/rdkafka/latest/rdkafka/) and `rpk topic consume -f '' -o :end`  to read them:

```
partitions  msg size  rdkafka     rpk
----------  --------  -------  ------
     1       512 kiB   1.7 s    2.2 s
     1        64 kiB   2.0 s    2.0 s
     1         4 kiB   1.7 s    2.2 s
    16       512 kiB   1.7 s     n/a
    16        64 kiB   1.7 s     n/a
    16         4 kiB   1.8 s     n/a
```

I could not find a way to make rpk read all of a multi-partition Kafka topic and then exit, so there are no timings for `rpk` with 16 partitions.

**Comment by blp** [comment]
Some more comparisons, using a 1.6 GB file that contains the data transferred via Kafka:

- `time wc foo.txt`: 4.4 s
- `time wc -l foo.txt`: 0.3 s (my rust program based on `rdkafka` counts the lines as a way to check that it's reading the data properly)
- `time cat foo.txt | wc -l`: 0.8 s

**Comment by ryzhyk** [comment]
So this seems to suggest that our Kafka connector does not read from Kafka as efficiently as it could or has some other bottleneck (parsing)?

@blp , does your simple client use multiple threads to read multiple partitions?

**Comment by ryzhyk** [comment]
As for message sizes, it makes sense that bigger message sizes don't help.  Kafka is supposed to be optimized for small messages. In my experience <=1KB is where it becomes inefficient.

**Comment by blp** [comment]
> So this seems to suggest that our Kafka connector does not read from Kafka as efficiently as it could or has some other bottleneck (parsing?)

That's my hypothesis. I'm going to write another program that uses `dbsp_adapters` to read data to see how the adapter does.

> @blp , does your simple client use multiple threads to read multiple partitions?

No. Kafka makes that difficult. Based on the results (throughput of about 1 GB/s or about 6 million records/s), I now doubt it's the current bottleneck. I don't want to go that direction unless or until we have to, based on the ft kafka connector experience thus far.

**Comment by blp** [comment]
> As for message sizes, it makes sense that bigger message sizes don't help. Kafka is supposed to be optimized for small messages. In my experience <=1KB is where it becomes inefficient.

I'll try some smaller messages sizes then. The average record size here is about 172 bytes.

**Comment by ryzhyk** [comment]
> No. Kafka makes that difficult. Based on the results (throughput of about 1 GB/s or about 6 million records/s), I now doubt it's the current bottleneck. I don't want to go that direction unless or until we have to, based on the ft kafka connector experience thus far.

Oh, fair enough, we need to squeeze more perf out of a single partition first. I was just trying to explain why the perf was the same for one an multiple partitions.

**Comment by blp** [comment]
OK, results for more record sizes. `consume` is my simple Rust `rdkafka` client:

```
events,partitions,size,command,time
10000000,1,524288,consume,1.82
10000000,1,65536,consume,1.58
10000000,1,4096,consume,2.29
10000000,1,512,consume,4.48
10000000,1,256,consume,14.32
10000000,16,524288,consume,1.74
10000000,16,65536,consume,1.77
10000000,16,4096,consume,1.91
10000000,16,512,consume,4.49
10000000,16,256,consume,51.90
10000000,1,524288,rpk,2.02
10000000,1,65536,rpk,2.06
10000000,1,4096,rpk,2.19
10000000,1,512,rpk,5.28
10000000,1,256,rpk,10.67
```

There is a crossover point where `rpk` becomes faster than the Rust program. This might be a weakness in the `rdkafka` crate because I think that my program is doing the same thing as `rpk` (which is written in Go). I'm going to tweak my program though (it uses one more thread than it really needs and that might be expensive for small record sizes).

**Comment by blp** [comment]
> I'm going to tweak my program though (it uses one more thread than it really needs and that might be expensive for small record sizes).

I take it back, it doesn't do that.

**Comment by blp** [comment]
OK, here's a comparison table with a quick-and-dirty threaded consumer. Results are mixed:

```
                                 Custom Tables
╭──────────────────────────────────────────────┬──────────────────────────────╮
│                                              │            command           │
│                                              ├───────┬────────────────┬─────┤
│                                              │consume│consume-threaded│ rpk │
│                                              ├───────┼────────────────┼─────┤
│                                              │  Mean │      Mean      │ Mean│
├──────────────────────────────────────────────┼───────┼────────────────┼─────┤
│events 10000000 partitions 1  size 256    time│  30.39│            6.24│10.68│
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   512    time│   4.59│            3.16│ 5.34│
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   4096   time│   1.74│            1.64│ 2.15│
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   65536  time│   1.78│            1.78│ 1.96│
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   524288 time│   1.81│            1.58│ 2.08│
│                          ╶───────────────────┼───────┼────────────────┼─────┤
│                           16 size 256    time│  48.50│           14.01│     │
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   512    time│   6.73│            7.12│     │
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   4096   time│   1.80│            2.22│     │
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   65536  time│   1.70│            1.67│     │
│                                  ╶───────────┼───────┼────────────────┼─────┤
│                                   524288 time│   1.69│            1.62│     │
╰──────────────────────────────────────────────┴───────┴────────────────┴─────╯
```

This is threaded in a way that `rdkafka` makes relatively easy: you can move individual partitions into queues that go to a particular thread. There's still just a fixed number of rdkafka threads (and a fixed number of network connections, I believe) doing the networking to and from the broker.

**Comment by blp** [comment]
I guess a useful way to summarize the results of the previous table is:
- For small message sizes, threading is much faster (up to 4-5x) regardless of the number of partitions.
- For larger message sizes, usually threading is about the same speed but sometimes it's a bit slower (up to about 25%).

**Comment by lalithsuresh** [comment]
@blp what sizes are the messages in our SQL-based nexmark benchmarks? And do the measurements here correspond to the slowdown you're seeing in those benchmarks?

**Comment by blp** [comment]
Now I wrote a program to consume from Kafka via the InputTransport from dbsp_adapters:

```
╭──────────────────────────────────────────────┬──────────────────────────────────────────────╮
│                                              │                    command                   │
│                                              ├───────┬───────────────┬────────────────┬─────┤
│                                              │consume│consume-adapter│consume-threaded│ rpk │
│                                              ├───────┼───────────────┼────────────────┼─────┤
│                                              │  Mean │      Mean     │      Mean      │ Mean│
├──────────────────────────────────────────────┼───────┼───────────────┼────────────────┼─────┤
│events 10000000 partitions 1  size 256    time│  30.39│          40.81│            6.24│10.68│
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   512    time│   4.59│           8.63│            3.16│ 5.34│
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   4096   time│   1.74│           1.68│            1.64│ 2.15│
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   65536  time│   1.78│           2.01│            1.78│ 1.96│
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   524288 time│   1.81│           1.62│            1.58│ 2.08│
│                          ╶───────────────────┼───────┼───────────────┼────────────────┼─────┤
│                           16 size 256    time│  48.50│          51.97│           14.01│     │
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   512    time│   6.73│          13.69│            7.12│     │
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   4096   time│   1.80│           1.81│            2.22│     │
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   65536  time│   1.70│           1.65│            1.67│     │
│                                  ╶───────────┼───────┼───────────────┼────────────────┼─────┤
│                                   524288 time│   1.69│           1.64│            1.62│     │
╰──────────────────────────────────────────────┴───────┴───────────────┴────────────────┴─────╯
```

**Comment by blp** [comment]
I figured out how to get threads to work in the input adapter reasonably.

The following chart shows the performance difference. Previous performance with the input adapter is `consume-adapter`. Performance after my changes (using 3 threads instead of 1) is `consume-adapter2`. Performance with 16 threads in a way that can't be integrated into the input adapter is `consume-threaded`:

```
╭──────────────────────────────────────────────┬───────────────────────────────────────────────────╮
│                                              │                      command                      │
│                                              ├───────┬───────────┬────────────┬────────────┬─────┤
│                                              │       │  consume- │  consume-  │  consume-  │     │
│                                              │consume│  adapter  │  adapter2  │  threaded  │ rpk │
│                                              ├───────┼───────────┼────────────┼────────────┼─────┤
│                                              │  Mean │    Mean   │    Mean    │    Mean    │ Mean│
├──────────────────────────────────────────────┼───────┼───────────┼────────────┼────────────┼─────┤
│events 10000000 partitions 1  size 256    time│  30.39│      40.81│       13.89│        6.24│10.68│
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   512    time│   4.59│       8.63│        6.26│        3.16│ 5.34│
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   4096   time│   1.74│       1.68│        1.76│        1.64│ 2.15│
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   65536  time│   1.78│       2.01│        1.99│        1.78│ 1.96│
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   524288 time│   1.81│       1.62│        1.64│        1.58│ 2.08│
│                          ╶───────────────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                           16 size 256    time│  48.50│      51.97│       14.32│       14.01│     │
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   512    time│   6.73│      13.69│        7.08│        7.12│     │
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   4096   time│   1.80│       1.81│        2.12│        2.22│     │
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   65536  time│   1.70│       1.65│        1.74│        1.67│     │
│                                  ╶───────────┼───────┼───────────┼────────────┼────────────┼─────┤
│                                   524288 time│   1.69│       1.64│        1.87│        1.62│     │
╰──────────────────────────────────────────────┴───────┴───────────┴────────────┴────────────┴─────╯
```

**Comment by mihaibudiu** [comment]
These would make a great blog post

**Comment by lalithsuresh** [comment]
> These would make a great blog post

100%
