### ISSUE TITLE
WebUI User Functionality

### ISSUE THREAD

**Issue by gz** [feldera/feldera#99]
- [ ] User UI functionality (support login, settings, permissions, etc.)
    - [ ] Backend: Coordinate with Lalith on login service, and API changes to existing API
    - [ ] UI: Include login page, user settings page, reset password page etc.
    - [ ] UI: Change pages to prevent seeing UI elements without login first
    - [ ] UI: Change API calls to include token/userauth
    - [ ] Backend: write tests that check for no information leakage
    - [ ] Legal/Backend: User deletion, figure out data retention etc.

**Comment by Karakatiza666** [comment]
09.12.2023 meeting w/ Lalith
> AWS Cognito for auth - exposes Oauth api
client_id, issuer_url
Send bearer in authorization header
Break up into: 1) login functionality 2) User management admin panel
Figure out the milestones
Figure out if we want login for "November release"

**Comment by lalithsuresh** [comment]
This is stale. Closing.
