### ISSUE TITLE
Replace list with combo-box or picklist

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/feldera#997]
This list will become long and not usable if there are many tables and views. Also the label says `Relation`. A table or view is better labelled as an `Entity`.

<kbd>![image](https://github.com/feldera/feldera/assets/28739668/ef02764d-9881-411c-b3b0-78bfeeb6d01c)<kbd/>

**Comment by Karakatiza666** [comment]
Is this something you had in mind?
![image](https://github.com/feldera/feldera/assets/8537259/5bbe1ed0-6492-4d95-8e5a-d855e82b5ad8)
![image](https://github.com/feldera/feldera/assets/8537259/45a4ec79-6157-4c18-96e1-234df0624a4d)

**Comment by lalithsuresh** [comment]
I prefer Relation over Entity.

@ryzhyk thoughts?

**Comment by mohsinbeg** [comment]
> I prefer Relation over Entity.
> 
> @ryzhyk thoughts?

User creates tables and views in the SQL programs and that is familiar. Relations are typically Foreign Key constraints.

**Comment by ryzhyk** [comment]
I think Entity is a modeling concept.  Tables and Views are Relations. But maybe we can just call it "Tables and Views"?

**Comment by Karakatiza666** [comment]
![image](https://github.com/feldera/feldera/assets/8537259/3ca6372d-09ff-4807-bf1d-acb3866c9b87)

**Comment by Karakatiza666** [comment]
Is there anything else to be improved in the scope of this issue?
